### ISSUE TITLE
開啟領取天書獎勵時遊戲崩潰

### ISSUE THREAD

**Issue by iveslazycat** [GpointChen/FFXIVChnTextPatch-GP#10]
使用的是 9/1 號的漢化，
是在跟『庫洛』講話後一開啟領取獎勵的介面時就崩潰了。
還沒選取獎勵。

不知道會不會跟  addon.csv 裡，
條目：
5604 裡的『・』
5605 裡的『·』
符號差異有關。

![unknown 1](https://user-images.githubusercontent.com/7374380/133568602-f48fdcb0-9108-4e8e-9c3f-96c30c657474.png)

**Comment by GpointChen** [comment]
確認為以非戰鬥職業領取獎勵時跳出的文本的問題，已修正。

感謝回報。

**Comment by kkjj116** [comment]
天书加载不出来一直在转圈怎么破
