### ISSUE TITLE
IL580裝備名稱顯示為日文

### ISSUE THREAD

**Issue by alvinyeung** [GpointChen/FFXIVChnTextPatch-GP#109]
首先感謝大佬製作CSV漢化，之前一直在用中國服檔案簡轉繁漢化
但有些字彙未能漢化顯示為簡體，強迫症的我一直在等大佬的CSV漢化

以下是我遇到的一個問題
在覆蓋原始檔案日文或英文的情況下，我的IL580裝備會顯示為日文，我沒有更高裝等所以不清楚其他更高裝等會否如此
![image](https://user-images.githubusercontent.com/14358600/159110098-42507493-3229-462e-8146-df4a1b071e5b.png)

**Comment by kalispp** [comment]
正常吧?  陸服還沒開零式...580製作綠裝是零式掉落一起上線的
如果要只能用私人的漢化版

**Comment by alvinyeung** [comment]
> 正常 陸服還沒開零式...580製作綠裝是零式掉落一起上線的 如果要只能用私人的漢化版

是這樣嗎？
我不太清楚，因為之前用簡體的中國服檔案時這些裝備是已翻譯的，所以以為陸服已經有相關裝備了

**Comment by GpointChen** [comment]
Fixed in [v2.55](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.55).

替未翻譯的裝備加上了之前的私譯。
