### ISSUE TITLE
商店不會顯示類型（例如防具商）

### ISSUE THREAD

**Issue by ryanho** [GpointChen/FFXIVChnTextPatch-GP#110]
3/19的版本NPC商店只會顯示人名，但不會顯示類型
![2022-03-19 16_50_14-FINAL FANTASY XIV](https://user-images.githubusercontent.com/204075/159114677-986ccecc-d0bd-460b-9daa-284e6f5d8ff1.png)

2/11之前的版本則會顯示類型
![2022-03-19 16_53_47-FINAL FANTASY XIV](https://user-images.githubusercontent.com/204075/159114685-184f5718-84bb-4a40-a346-3bb9d9bf5eff.png)

日文版則是在人名前顯示商店類型
![2022-03-19 16_47_43-FINAL FANTASY XIV](https://user-images.githubusercontent.com/204075/159114727-c68030d8-ebe6-4933-91b5-249e3b92542b.png)

**Comment by qwe3410475** [comment]
很多都是這樣，優雷卡也是

**Comment by GpointChen** [comment]
fixed in [v2.55](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.55).
