### ISSUE TITLE
報告翻譯錯誤

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#112]
錶演(X) 表演(O)
LucKbb231_03253 (rawexd\quest\032)
BanAll210_03161(rawexd\quest\031)
LucKbb201_03249(rawexd\quest\032)
LucKbb211_03251(rawexd\quest\032)
後續如有其他錯誤 會再提供分享 謝謝前輩

**Comment by Liteya** [comment]
娜休梅拉阁下给我寄来了书信，
希望我将心怀不安的贫民阶层中比较有影响力的人
聚集起来观看表演。这究竟是为了？
3/16中國原版
---------------------------------------------------------------------
69,"TEXT_LUCKBB231_03253_HANDELOUP_000_073",
"娜休梅拉閣下給我寄來了書信，<hex:02100103>
希望我將心懷不安的貧民階層中比較有影響力的人<hex:02100103>
聚集起來觀看錶演。這究竟是為了？"
------------------------
轉換器換錯了嗎  辛苦前輩檢查了

**Comment by liuedd** [comment]
借串回應，未轉繁體
金碟的廣播還是簡體，再麻煩作者了，感激不盡

![ffxiv_dx11_h2QGay4nQZ](https://user-images.githubusercontent.com/51795301/159156651-b1c95e8b-215b-4a2e-9fc9-625a9ea97331.png)

**Comment by GpointChen** [comment]
了解，預計下次更新時修正，感謝回報。

**Comment by GpointChen** [comment]
Fixed in v2.56.
