### ISSUE TITLE
翻譯錯誤

### ISSUE THREAD

**Issue by ooo-Jay** [GpointChen/FFXIVChnTextPatch-GP#115]
最近在重玩時發現的錯誤

1. 發現
![001](https://user-images.githubusercontent.com/72383445/159770052-32a8be6a-c610-4b8d-94a5-27f6bcf1442b.jpg)

2. 名字中的"采"字沒有統一
![002](https://user-images.githubusercontent.com/72383445/159770456-36064bdf-3196-4e04-b465-2997133f0a19.jpg)
![003](https://user-images.githubusercontent.com/72383445/159770482-8b2c23e8-fb07-43ec-bd29-e9dd8bcb286e.jpg)
![004](https://user-images.githubusercontent.com/72383445/159770504-7c9f0491-3120-48e7-a46a-a59f45d28661.jpg)

3. 關係
![005](https://user-images.githubusercontent.com/72383445/159770607-c201e8c4-955e-414e-9a54-78dc28e39bac.jpg)

4. 策劃
![006](https://user-images.githubusercontent.com/72383445/159770699-163694ae-f99b-4646-a0b4-a2fc81054c56.jpg)

5. 只要
![007](https://user-images.githubusercontent.com/72383445/159770746-94247ae5-01cb-476f-a6dc-fc05fe5736e6.jpg)

6. 乾了
![008](https://user-images.githubusercontent.com/72383445/159770798-676f481c-c983-4919-bd6a-1a1c5485a4cb.jpg)

7. 只不過
![009](https://user-images.githubusercontent.com/72383445/159770864-ae158e2f-2b8a-4ac4-86c6-a7f52a61671e.jpg)

8. 自發
![010](https://user-images.githubusercontent.com/72383445/159770944-7e03f495-fc77-4eb0-a8cd-25933407ae47.jpg)

9. 不捨
![011](https://user-images.githubusercontent.com/72383445/159770995-bc26c173-800e-43b7-b3cb-657038f59a6f.jpg)

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修復。

**Comment by ooo-Jay** [comment]
隨著劇情發展發現一些新的/存疑的

10. 形容地方時, 週邊, 周邊未有統一, 任務目標使用周邊來形容周邊地方, 對話則使用週邊
![012_2](https://user-images.githubusercontent.com/72383445/159985947-d82ce1d8-0b5f-4fd9-9910-3941d8efff6e.jpg)
![012](https://user-images.githubusercontent.com/72383445/159985976-334054e2-6ece-4630-89ba-34b77fbbacbb.jpg)
![015](https://user-images.githubusercontent.com/72383445/159986027-f585f905-5905-4b8c-b188-08304eebfee9.jpg)
![016](https://user-images.githubusercontent.com/72383445/159986035-7b846f2f-08f6-4cc4-bddc-aea4ce9fbc84.jpg)

11. 濃郁的郁被換成鬱
![013](https://user-images.githubusercontent.com/72383445/159986464-2e5e0643-4b91-4542-a7b4-b37e4a8a0162.jpg)

12. 說不準
![014](https://user-images.githubusercontent.com/72383445/159986511-cf28a85e-6a65-4094-8dd9-6780b0f7dbfb.jpg)

13. 雕像
![017](https://user-images.githubusercontent.com/72383445/159986590-fe318c46-2c19-467b-a2dc-97722df004ab.jpg)

14. 劇情中總督名字一直是阿希旺, 其中一段應該是因為讀音而變成阿斯旺?
![018](https://user-images.githubusercontent.com/72383445/159986686-f4e44e67-5c6a-4119-a81a-7c1c2887a0a6.jpg)

15. 香港和台灣應該比較常用詞彙
![019](https://user-images.githubusercontent.com/72383445/159987769-0c030bdb-b7c2-4991-9291-cefb9177e9be.jpg)

**Comment by GpointChen** [comment]
Fixed in v2.56.
