### ISSUE TITLE
關於6.0 說話頻道輸入有關的任務

### ISSUE THREAD

**Issue by qwe3410475** [GpointChen/FFXIVChnTextPatch-GP#118]
![image](https://user-images.githubusercontent.com/46574011/160326600-ab3eb678-bdc4-46e0-b1c9-decb87f6a4b0.png)
回報一下，6.0的任務有關說話頻道輸入的任務應該都沒辦法過
可能需要再調整一下

**Comment by qwe3410475** [comment]
順便回報，之前設定返回點沒對齊的部分又出現了～

**Comment by qwe3410475** [comment]
阿 其實打中文是可以過得
只不過在公共頻道打中文有些不妥

**Comment by GpointChen** [comment]
感謝回報，修正於v2.57。

開心胡蘿蔔改成用英文「carrot of happiness」。其他同類型任務暫時未修。

**Comment by cpureaz3958** [comment]
不好意思借串
想請問最大的貢獻里的說話能不能也修改成英文呢? 麻煩了不好意思 
![image](https://user-images.githubusercontent.com/95715370/163390837-6fcf4b05-7e4c-4b05-9491-82c2199e6d4f.png)

**Comment by GpointChen** [comment]
> 不好意思借串 想請問最大的貢獻里的說話能不能也修改成英文呢? 麻煩了不好意思 ![image](https://user-images.githubusercontent.com/95715370/163391004-5ff691b8-d0c2-46d9-b043-c58ce43dc19e.png)

了解，預計下版更新加上。

**Comment by plp001001** [comment]
同樣借個串回報一下，發現5.0裡「衛士的心得」這個任務需要輸入兩次對話，在第一次的對話輸入英文對話是沒有問題的。
但是在後續第二次需要透過輸入與新人衛士對話時，無論是對他輸入英文的「tuktu」和日文的「のばら」都沒有反應，只有使用中文的「野玫瑰」才能成功觸發事件。
![image](https://user-images.githubusercontent.com/104105781/164331601-4e204f0a-03ba-416c-8c59-41768effc8c3.png)

**Comment by GpointChen** [comment]
> 同樣借個串回報一下，發現5.0裡「衛士的心得」這個任務需要輸入兩次對話，在第一次的對話輸入英文對話是沒有問題的。 但是在後續第二次需要透過輸入與新人衛士對話時，無論是對他輸入英文的「tuktu」和日文的「のばら」都沒有反應，只有使用中文的「野玫瑰」才能成功觸發事件。 ![image](https://user-images.githubusercontent.com/104105781/164331601-4e204f0a-03ba-416c-8c59-41768effc8c3.png)

了解，預計下版更新加上。
