### ISSUE TITLE
6.0臨時版使用時出現問題集中串

### ISSUE THREAD

**Issue by samorisima** [GpointChen/FFXIVChnTextPatch-GP#12]
如題，使用CSV方式會跳出程式錯誤導致失敗，而使用文本替換方式雖然執行成功，但任務列表標題仍然維持日文，看了一下你的筆記這個問題似乎已經解決了，請問這是為什麼呢？

**Comment by lai909909911** [comment]
正常吧 6.0更新很多東西，只能等作者更新
我直接替換6個漢化檔案進遊戲直接就跳出了

**Comment by qwe3410475** [comment]
正常~ 等更新吧

**Comment by GpointChen** [comment]
先更新了一個臨時版，目前測試可以進遊戲。不過都還是舊的文本，請自行視需求使用。

https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30

**Comment by qwe3410475** [comment]
感謝~ 還沒到6.0 用舊的就夠了

**Comment by 3-season** [comment]
6.0剛更新, 舊漢化進不了很正常呀...等待更新吧

**Comment by awaww333** [comment]
辛苦啦~ 先好好享受遊戲吧
敲碗個技能翻譯
目前任務劇情都靠塔塔露

**Comment by samorisima** [comment]
感謝，不過我不是不能進遊戲，是任務列表那邊的漢化沒有成功，用了6.0臨時版，這次可以用CSV執行了，但任務列表整個消失

**Comment by qwe3410475** [comment]
看來任務方面會有問題~ 例如職業任務

**Comment by 3-season** [comment]
應該不只是職任, 蠻族任的NPC也會消失…我要轉用英文版才可以看到NPC

**Comment by Jason2321** [comment]
目前任務方面有問題，除了任務列表消失外，有任務記號的npc也全消失，無法接任務

**Comment by itsbosco1025** [comment]
任務列表和接任務npc消失了，按下主綫會顯示目前無法開啓地圖

**Comment by GpointChen** [comment]
Updated 12/3 11:50 可以接主線了，只是還不會顯示任務進度提示（FFXIVChnTextPatch-1203-temp-fixed.rar）

https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30

**Comment by syntex** [comment]
感覺是任務的順序有異動，我試著把Quest.csv 排除在中文化之外後，任務列表和NPC就回來了，任務內容也是正常的
但是任務列表的任務名稱還是日文就是
抽出日文版的Quest.csv 或許可以比對出問題

**Comment by GpointChen** [comment]
> 感覺是任務的順序有異動，我試著把Quest.csv 排除在中文化之外後，任務列表和NPC就回來了，任務內容也是正常的 但是任務列表的任務名稱還是日文就是 抽出日文版的Quest.csv 或許可以比對出問題

我也是這麼想XD 剛才經過測試修改已經修復了。

https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30

如使用上還有其他問題歡迎回報。

**Comment by syntex** [comment]
> > 感覺是任務的順序有異動，我試著把Quest.csv 排除在中文化之外後，任務列表和NPC就回來了，任務內容也是正常的 但是任務列表的任務名稱還是日文就是 抽出日文版的Quest.csv 或許可以比對出問題
> 
> 我也是這麼想XD 剛才經過測試修改已經修復了。
> 
> https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30
> 
> 如使用上還有其他問題歡迎回報。

辛苦了 
感謝你

**Comment by Aliline** [comment]
想請問一下 目前最新的FFXIVChnTextPatchGP.exe 與舊版的.exe有差別嗎? 我打開最新的FFXIVChnTextPatchGP.exe會叫我更新java至16.0.1 但目前的java最新版只到1.8.0

**Comment by GpointChen** [comment]
> 想請問一下 目前最新的FFXIVChnTextPatchGP.exe 與舊版的.exe有差別嗎? 我打開最新的FFXIVChnTextPatchGP.exe會叫我更新java至16.0.1 但目前的java最新版只到1.8.0

有修改幾行code應對更新
 
> 上午2:23編輯: 我把以前附帶的jre資料夾複製一份到exe的目錄下就可以正常開啟了 感謝!

基本上都要jre才能跑！最新版的應該也有附，如果有遺漏也歡迎回報。

**Comment by qwe3410475** [comment]
辛苦了 謝謝！

**Comment by Aliline** [comment]
> 基本上都要jre才能跑！最新版的應該也有附，如果有遺漏也歡迎回報。
我這裡看目錄只有找到類似source code的資料夾 沒有看到jre資料夾
辛苦了 謝謝您!

**Comment by yuli91225** [comment]
您好~ 目前我使用最新的版本開啟任務情報會跳錯誤 有朋友也會跳錯誤也有人沒問題
![image](https://user-images.githubusercontent.com/95512613/144693650-a4df87d7-8e7d-4059-bf5d-fb0e6def439c.png)

**Comment by GpointChen** [comment]
> 您好~ 目前我使用最新的版本開啟任務情報會跳錯誤 有朋友也會跳 也有人沒問題 ![image](https://user-images.githubusercontent.com/95512613/144693650-a4df87d7-8e7d-4059-bf5d-fb0e6def439c.png)

這可能是因為有某些任務文本變動導致了bug。你可以試著用未漢化的版本截圖你任務情報中所有的任務，方便我進行排查。

**Comment by yuli91225** [comment]
> > 你好~我用的是最新版本的爆料任務情報會跳錯有朋友也會跳也有人沒問題 ![圖片](https://user-images.githubusercontent.com/95512613/144693650-a4df87d7-8e7d-4059-bf5d-fb0e6def439c.png)
> 
> 這可能是因為有部分任務文本會導致了bug。

感謝您，辛苦了!
![image](https://user-images.githubusercontent.com/95512613/144694181-4aedebfa-e03e-48a1-a4e4-9d06d6356a55.png)

**Comment by GpointChen** [comment]
> 您好~ 目前我使用最新的版本開啟任務情報會跳錯誤 有朋友也會跳 也有人沒問題 ![image](https://user-images.githubusercontent.com/95512613/144693650-a4df87d7-8e7d-4059-bf5d-fb0e6def439c.png)

已修正於[fixed-v5](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)。

**Comment by itsbosco1025** [comment]
發現Journal的已完成任務名稱以及任務分類有出現錯位的問題

**Comment by 3-season** [comment]
已經發展到V5了lol....辛苦了

**Comment by Lother** [comment]
由於我的拆解CSV方式不同
我拉了你的中文5.58文本 
並從日版5.58原檔的格式重新建了CSV
然後再塞回日版6.0
目前蠻族NPC正常 沒有空白的選項出現
不過我懶得包工具的bin了 
直接上傳處理好的檔案... 
可以參考看看有什麼差異
https://github.com/Lother/FFXIVChnTextPatch/releases/tag/v1.0.2

**Comment by yuli91225** [comment]
發現了一個新錯誤
![Uploading image.png…]()

**Comment by yuli91225** [comment]
發現一個NPC名字出錯
![image](https://user-images.githubusercontent.com/95512613/144699467-7011393c-153e-43b6-9219-8e07af736bb5.png)

**Comment by AdiBKDWs** [comment]
https://imgur.com/6qy4law.png
打古武的時候突然找不到任務
後來發現任務名稱好像錯了

**Comment by KazeMai** [comment]
怪物通緝令的接取有問題
2.0地點變5.0 無法正確顯示
https://i.imgur.com/WzfD9qT.jpg
3.0地點變2.0 提示非所屬軍團無法接
https://i.imgur.com/VYuUt0T.jpg
4.0地點變3.0 可以接
5.0地點變4.0 可以接

**Comment by lai909909911** [comment]
裝了漢化好像新職業任務不能觸發？ 
我70級去找NPC不能對話
還是說主線要過到後面才能觸發？
我現在還在3.0

**Comment by HSIA0116** [comment]
![ffxiv_12042021_191209_352](https://user-images.githubusercontent.com/37303531/144707598-9281dba6-d1f7-46bd-9215-7c19950c86d0.png)
旅行筆記中的任務名稱對不上

**Comment by alvinyeung** [comment]
您好，感謝您的付出讓我們可以在更新第一天就可以繼續完成6.0以下內容。
以下是我遇到的問題，如果可以的話請修復，謝謝。
1. 在伊修加德接理符時，會類似進入拍攝模式，所有HUD都不見了，但就這樣卡住(可移動鏡頭，但人物不能移動)，不會彈出理符任務視窗。
註: 我是取代英文去漢化的。

**Comment by BQQ222** [comment]
感謝你的FF14中文漢化, 加油啊！！ 期待能看到之後的6.0漢化 
最後真的感謝你了：）

**Comment by YuuXuan** [comment]
感謝大大，這邊來回報一點小問題
要給雇員洗澡的話，會在選雇員性格後取消洗雇員的動作
正常的話，會跳出雇員台詞參考→確認→改名，但剛剛選完性格的台詞參考完全沒顯示，NPC就中斷對話，且幻想藥資格還沒使用掉
猜測是雇員這一串對話有改到(也有可能是因為我要洗兔男)

**Comment by 3-season** [comment]
今早試了也出現這個問題, 只好轉回日文了

> > 您好~ 目前我使用最新的版本開啟任務情報會跳錯誤 有朋友也會跳 也有人沒問題 ![image](https://user-images.githubusercontent.com/95512613/144693650-a4df87d7-8e7d-4059-bf5d-fb0e6def439c.png)
> 
> 已修正於[fixed-v5](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)。

**Comment by belle0976** [comment]
![v5版世界地圖錯誤](https://user-images.githubusercontent.com/95540085/144720097-daeb06c6-9196-4942-8657-a0705ba0ff1f.png)
您好，我有朋友使用了目前新的6.0-v5臨時檔，開大地圖時跳出錯誤，因為他有遇到這問題，所以我就不敢開世界地圖了，回報給您，再麻煩您看看是否有需調整的地方。謝謝您們，漢化很辛苦，要一直糾錯修正，感謝你們第一時間讓我們可以在6.0看到中文介面，期待你們6.0的主線漢化，支持你們！

**Comment by Jason2321** [comment]
發現問題優雷卡進不去

**Comment by Jason2321** [comment]
發現一個問題進優雷卡島的npc沒辦法講話

**Comment by GpointChen** [comment]
[fixed-v6](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)
修正：
- 任務錯位
- 優雷卡等NPC無法說話
- 理符NPC無法說話
- 僱員洗澡
- 職業任務
- 提升覆蓋英文的兼容性

尚未修正：
- 怪物狩獵（暫時還沒找到問題在哪）
- 可露兒

無法觸發：
- 大地圖
（我沒遇到這個問題，如果使用最新版仍然有類似狀況發生，請詳述再現步驟）

**Comment by GpointChen** [comment]
> 怪物通緝令的接取有問題 2.0地點變5.0 無法正確顯示 https://i.imgur.com/WzfD9qT.jpg 3.0地點變2.0 提示非所屬軍團無法接 https://i.imgur.com/VYuUt0T.jpg 4.0地點變3.0 可以接 5.0地點變4.0 可以接

修正於[fixed-v7](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)。

**Comment by systen002131** [comment]
![擷取001](https://user-images.githubusercontent.com/95570624/144744924-24877cd9-bf62-4799-8901-680a3b7f0c8a.PNG)
我漢化完之後開起來會長這樣  把漢化復原就好了  只有我這樣嗎?

**Comment by YuuXuan** [comment]
> ![擷取001](https://user-images.githubusercontent.com/95570624/144744924-24877cd9-bf62-4799-8901-680a3b7f0c8a.PNG) 我漢化完之後開起來會長這樣 把漢化復原就好了 只有我這樣嗎?

不是，那應該是伺服器偶爾抽風，我殛登入第一天就遇過了
![Uploading Screenshot_20211203-201842153.jpg…]()

**Comment by jayhormes** [comment]
> 發現一個NPC名字出錯 石之家內 ![image](https://user-images.githubusercontent.com/95512613/144699467-7011393c-153e-43b6-9219-8e07af736bb5.png)

可露兒問題看是不是在 ENpcResident.csv 的 1031818 offset 問題，
對照日文原文是 エフェミ 但是翻譯文本是可露兒

**Comment by Barry0731** [comment]
![ffxiv_12072021_092036_683](https://user-images.githubusercontent.com/95480134/144948970-29da8c05-f77f-4fab-b51a-7a3348b51fe7.png)
想請問目前的漢化 新物品名稱都是空白的是正常的嗎
第一版開始用就是這個狀況~

**Comment by e23456780** [comment]
fixed-v7
伊修加德主城理符任務npc對話後 
無出現彈窗 會卡住 
只能透過關閉遊戲視窗退出遊戲
還原翻譯檔後 即可正常使用理符任務npc
====其他附註====
黑森主城的理符任務npc應該是正常的
v7只與黑森理符/伊修加德理符npc對話過
其餘理符npc尚未嘗試

**Comment by GpointChen** [comment]
> ![ffxiv_12072021_092036_683](https://user-images.githubusercontent.com/95480134/144948970-29da8c05-f77f-4fab-b51a-7a3348b51fe7.png) 想請問目前的漢化 新物品名稱都是空白的是正常的嗎 第一版開始用就是這個狀況~

不太正常，我會正常顯示

![螢幕擷取畫面 (1516)](https://user-images.githubusercontent.com/34565875/144959634-10db0a81-90b5-41e0-9d83-20d57357621f.png)

可能要請你確認有沒有使用最新的exe以及原本是否是乾淨的遊戲檔案？

**Comment by GpointChen** [comment]
> fixed-v7 伊修加德主城理符任務npc對話後 無出現彈窗 會卡住 只能透過關閉遊戲視窗退出遊戲 還原翻譯檔後 即可正常使用理符任務npc ====其他附註==== 黑森主城的理符任務npc應該是正常的 v7只與黑森理符/伊修加德理符npc對話過 其餘理符npc尚未嘗試

我目前使用上這個問題已經修復

![螢幕擷取畫面 (1517)](https://user-images.githubusercontent.com/34565875/144959987-4c153dd4-691d-408f-93f9-8b4718085a8c.png)

同樣的，可能要請你確認有沒有使用最新的exe以及原本是否是乾淨的遊戲檔案？

**Comment by GpointChen** [comment]
> > 發現一個NPC名字出錯 石之家內 ![image](https://user-images.githubusercontent.com/95512613/144699467-7011393c-153e-43b6-9219-8e07af736bb5.png)
> 
> 可露兒問題看是不是在 ENpcResident.csv 的 1031818 offset 問題， 對照日文原文是 エフェミ 但是翻譯文本是可露兒

OK 預計於下一版一起修復

**Comment by Barry0731** [comment]
> 

因為期間我也有重新安裝遊戲,但一直這樣覺得不太正常
我再試試看,感謝!

**Comment by Barry0731** [comment]
> > ![ffxiv_12072021_092036_683](https://user-images.githubusercontent.com/95480134/144948970-29da8c05-f77f-4fab-b51a-7a3348b51fe7.png) 想請問目前的漢化 新物品名稱都是空白的是正常的嗎 第一版開始用就是這個狀況~
> 
> 不太正常，我會正常顯示
> 
> ![螢幕擷取畫面 (1516)](https://user-images.githubusercontent.com/34565875/144959634-10db0a81-90b5-41e0-9d83-20d57357621f.png)
> 
> 可能要請你確認有沒有使用最新的exe以及原本是否是乾淨的遊戲檔案？

因為期間我也有重新安裝遊戲兩次,但一直這樣覺得不太正常
或許沒移除乾淨,我再試試看,感謝!

**Comment by GpointChen** [comment]
> 



> > > ![ffxiv_12072021_092036_683](https://user-images.githubusercontent.com/95480134/144948970-29da8c05-f77f-4fab-b51a-7a3348b51fe7.png) 想請問目前的漢化 新物品名稱都是空白的是正常的嗎 第一版開始用就是這個狀況~
> > 
> > 
> > 不太正常，我會正常顯示
> > ![螢幕擷取畫面 (1516)](https://user-images.githubusercontent.com/34565875/144959634-10db0a81-90b5-41e0-9d83-20d57357621f.png)
> > 可能要請你確認有沒有使用最新的exe以及原本是否是乾淨的遊戲檔案？
> 
> 因為期間我也有重新安裝遊戲兩次,但一直這樣覺得不太正常 或許沒移除乾淨,我再試試看,感謝!

又或者可以請你提供你的三個0a0000給我
或許我可以找出問題在哪

**Comment by e23456780** [comment]
> > fixed-v7 伊修加德主城理符任務npc洞後無出現彈窗會卡住只能通過關閉遊戲視窗退出遊戲翻譯檔後正常使用理符任務npc ====其他附註還原== ==黑森主城的理符任務npc應該是正常的v7只與黑森理符/伊修加德理符npc譯文過其他理符npc尚未嘗試
> 
> 我現在使用上的這個問題已經修復
> 
> ![螢幕擷取畫面 (1517)](https://user-images.githubusercontent.com/34565875/144959987-4c153dd4-691d-408f-93f9-8b4718085a8c.png)
> 
> 的，可能要請你確認有沒有使用過最新的exe文件以及是否是乾淨的遊戲？

好的 我在排除看看
有問題再回報 沒回報就是排除了 感謝

**Comment by dugonpot** [comment]
不確定是不是漢化包的問題，但因為除了漢化跟gshade沒裝別的，還是來回報下
在旅館看過去任務動畫到一半會crash，因為是昨天睡前遇到的所以代碼忘記記了，似乎是9009（吧

**Comment by Ruaww** [comment]
有一個小問題，CSV覆蓋到EN版後，新任務的名稱會是日文。

**Comment by Bos-hunting** [comment]
![image](https://user-images.githubusercontent.com/95756995/145216005-1a45d2a0-24db-4970-9c71-d682a671b973.png)
魂武和有部分24人任務（尼爾、巴哈）顯示日文

**Comment by Bally0886** [comment]
非常感謝原PO提供方案讓我們遊玩!我也有發現一個問題。就是若任務是需要打字的。若使用繁體中文的打繁體中文是沒有反應的。需要切換至簡體還是英文(不太確定因為我是一起簡體和英文一起打出去)，才能順利繼續任務。提供給原PO參考

**Comment by GpointChen** [comment]
> 非常感謝原PO提供方案讓我們遊玩!我也有發現一個問題。就是若任務是需要打字的。若使用繁體中文的打繁體中文是沒有反應的。需要切換至簡體還是英文(不太確定因為我是一起簡體和英文一起打出去)，才能順利繼續任務。提供給原PO參考

理論上是英文，同時任務進度提示會顯示應該輸入的英文。

如果有任務不是這樣，歡迎回報是哪個任務，我會進行排查。

**Comment by GpointChen** [comment]
> 有一個小問題，CSV覆蓋到EN版後，新任務的名稱會是日文。



> ![image](https://user-images.githubusercontent.com/95756995/145216005-1a45d2a0-24db-4970-9c71-d682a671b973.png) 魂武和有部分24人任務（尼爾、巴哈）顯示日文

新任務與舊任務名稱的問題預計於下一版一起修復。感謝回報。

**Comment by Bally0886** [comment]
> > 非常感謝原PO提供方案讓我們遊玩!我也有發現一個問題。就是若任務是需要打字的。若使用繁體中文的打繁體中文是沒有反應的。需要切換至簡體還是英文(不太確定因為我是一起簡體和英文一起打出去)，才能順利繼續任務。提供給原PO參考
> 
> 理論上是英文，同時任務進度提示會顯示應該輸入的英文。
> 
> 如果有任務不是這樣，歡迎回報是哪個任務，我會進行排查。

感謝大大回覆，以下兩個任務都是有遇到一樣的問題。
任務會顯示繁體中文，之前我都是直接複製貼上對話欄的系統提示。感謝

https://ff14.huijiwiki.com/wiki/%E4%BB%BB%E5%8A%A1:%E8%BF%B7%E8%B7%AF%E7%9A%84%E7%A2%A7%E7%94%B2%E6%97%8F

**Comment by Bos-hunting** [comment]
感謝大大的付出以及努力讓我們這些中文玩家有更好的體驗。
在最新的1207漢化包，同一部隊的成員頭上面標示是路人的藍色而非平時的橙色。
我用csv 進行漢化的（日翻正體），由於私隱問題不方便截圖。
十分感謝您的付出！

**Comment by GpointChen** [comment]
> ![image](https://user-images.githubusercontent.com/95756995/145216005-1a45d2a0-24db-4970-9c71-d682a671b973.png) 魂武和有部分24人任務（尼爾、巴哈）顯示日文

我剛粗略看了一下，但是我的這個任務是顯示中文，CSV中也是中文。

可能要麻煩你檢查一下你的`resource/rawexd/quest/039/LucKta301_03952.csv`是不是中文？

**Comment by Bos-hunting** [comment]
> > ![image](https://user-images.githubusercontent.com/95756995/145216005-1a45d2a0-24db-4970-9c71-d682a671b973.png) 魂武和有部分24人任務（尼爾、巴哈）顯示日文
> 
> 我剛粗略看了一下，但是我的這個任務是顯示中文，CSV中也是中文。
> 
> 可能要麻煩你檢查一下你的`resource/rawexd/quest/039/LucKta301_03952.csv`是不是中文？

是中文誒，奇怪了。我還原再漢化看看能不能修好。 謝謝大大！

**Comment by GpointChen** [comment]
能排查的問題基本已排查完畢。
如有遺漏或遇到新問題可以開新帖回報。
