### ISSUE TITLE
csv翻译失败

### ISSUE THREAD

**Issue by lincTHU** [GpointChen/FFXIVChnTextPatch-GP#123]
因为想自用先行翻译，所以使用saintconinach.cmd编译运行以后解出来的rawexd文件夹，替换ChnTextPatch/resource里的rawexd文件夹
点击翻译后虽然正常跑进度条并且显示汉化成功
但是实际进游戏还是日文
请问是还需要修改什么吗

**Comment by lincTHU** [comment]
对比了一下文件，似乎是缺少了一行offset。
请问能告知cmd需要修改什么吗；或者可否分享一下修改后的cmd

**Comment by Souma-Sumire** [comment]
> 修改了ExdHelper，成功输出了offset了。感谢笔记！

您好，我也遇到了这个问题，请问是具体如何解决的，是需要修改ExdHelper.cs相关的源码重新编译吗？感谢！
