### ISSUE TITLE
6.1 版 程式錯誤

### ISSUE THREAD

**Issue by Paul332300** [GpointChen/FFXIVChnTextPatch-GP#124]
![001](https://user-images.githubusercontent.com/103493209/162925808-e4af6b7d-c26e-4c58-bdbb-fb461b18e194.png)

**Comment by Paul332300** [comment]
Log File :
[debug.log](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/8471564/debug.log)

**Comment by GpointChen** [comment]
改版改了不少東西，我先弄一個相容版出來。

**Comment by gracechiang07010** [comment]
謝謝， 辛苦你了.

**Comment by jeff1139** [comment]
谢谢 GpointChen了。 ！！

**Comment by GpointChen** [comment]
已更新v2.58。
