### ISSUE TITLE
6.1版汉化错误

### ISSUE THREAD

**Issue by lincTHU** [GpointChen/FFXIVChnTextPatch-GP#125]
用国服6.05版本包汉化6.1国际服出现乱码
![image](https://user-images.githubusercontent.com/8018928/162932618-5f8a56a5-30b8-4cc2-b5ce-f09ac567fe77.png)
用CSV则会报程式错误 卡的位置和这个问题相同 #124

**Comment by qwe3410475** [comment]
正常 過一個版本都要等更新

**Comment by GpointChen** [comment]
是的，改版改了不少東西，我先弄一個相容版出來。

**Comment by lincTHU** [comment]
> 是的，改版改了不少東西，我先弄一個相容版出來。

感恩！

**Comment by loey890802** [comment]
> 是的，改版改了不少東西，我先弄一個相容版出來。

萬分感謝，多晚都等!

**Comment by Yingyucho** [comment]
感恩大師

**Comment by jiyuanfu** [comment]
感谢大佬

**Comment by sai750310** [comment]
辛苦了

**Comment by jiyuanfu** [comment]
您好，谢谢您的来信，我已收到。傅纪元。

**Comment by GpointChen** [comment]
已更新v2.58。仍有問題可至Discussion或另開新串。
