### ISSUE TITLE
6.1中文化出現錯誤

### ISSUE THREAD

**Issue by skog12345** [GpointChen/FFXIVChnTextPatch-GP#129]
4/13更新的中文化 登入後跳出一排錯誤就強制關掉了

**Comment by loey890802** [comment]
![image](https://user-images.githubusercontent.com/103520791/163095861-6ea29908-307c-4860-8ae7-96e08348bf1d.png)
麻煩大大了

**Comment by corey924** [comment]
https://github.com/GpointChen/FFXIVChnTextPatch-GP/issues/130#issuecomment-1097606719

**Comment by GpointChen** [comment]
應於v2.59中修正，仍有問題請另開新串。
