### ISSUE TITLE
和進入南方戰線的NPC講話會卡住

### ISSUE THREAD

**Issue by class2u** [GpointChen/FFXIVChnTextPatch-GP#13]
您好！
非常感謝這麼快速的製作中文化，目前發現一個問題，和進入南方戰線（排女王古殿）的NPC講話會卡住，完全不能操作，也不能退出，必須強制關閉遊戲。
我使用 FFXIVChnTextPatch-1203-fixed 的版本。

**Comment by GpointChen** [comment]
已修正於[fixed-v4](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)。

感謝回報。

**Comment by class2u** [comment]
太有效率了!!! 非常感謝!!
