### ISSUE TITLE
> 剛用了上面方法還是失敗 然後把漢化工具關了就成功了

### ISSUE THREAD

**Issue by 1016821151** [GpointChen/FFXIVChnTextPatch-GP#132]
> 剛用了上面方法還是失敗 然後把漢化工具關了就成功了

你就是沒開第二次

_Originally posted by @cydad111 in https://github.com/GpointChen/FFXIVChnTextPatch-GP/issues/130#issuecomment-1098052938_

**Comment by asdfghjtyuio** [comment]
您好請問遇到這個是甚麼問題呢? 
![錯誤ff14](https://user-images.githubusercontent.com/103890302/163718914-d07398bf-5a4f-49a6-8ecc-147ca3c403e3.jpg)
