### ISSUE TITLE
新的0413汉化器汉化后打开游戏出现游戏框瞬间消失崩溃的情况

### ISSUE THREAD

**Issue by pearcehao** [GpointChen/FFXIVChnTextPatch-GP#134]
新的0413汉化器汉化后打开游戏出现游戏框瞬间消失崩溃的情况。
在这之前的两个小时汉化还是正常打开游戏的，现在打不开了。

**Comment by kingyo1014** [comment]
也有 一樣的問題 漢化第一次還能盡遊戲 我跟我朋友遊戲關掉再開就打不開了

**Comment by kalispp** [comment]
#130 

有大佬回覆
＊後續注意(04/13的版本)：
漢化完成後，開啟遊戲偶然會出現錯誤視窗，多開幾次即可。需要等待新版本的漢化修正解決。

**Comment by mapleleafyzq** [comment]
等修正了 赞美大佬

**Comment by GpointChen** [comment]
應修正於v2.59，如仍有問題請開新串回報。
