### ISSUE TITLE
使用英文介面，但萬魔殿 BOSS 技能讀條為日文顯示問題。

### ISSUE THREAD

**Issue by ACZife** [GpointChen/FFXIVChnTextPatch-GP#139]
如下圖所示，使用英文語言介面時，BOSS 的技能讀條為日文呈現。
目前於萬魔殿1層~萬魔殿4層有發現此問題；
尚未清楚其他副本與英文語言介面是否有相同問題。

![unknown](https://user-images.githubusercontent.com/101320623/163601874-19911008-15e1-4785-8fa2-bcf75d1ecd61.png)

**Comment by ACZife** [comment]
6.1 Endsing 高難 BOSS 技能條正常為英文顯示。

**Comment by GpointChen** [comment]
確實有一部份技能可能有此問題，已找出問題所在，預計於下版修正。

**Comment by GpointChen** [comment]
已修正於v2.60。

**Comment by ACZife** [comment]
目前跑團P1S~P4S 技能讀條已為中文顯示。
Endsinger 也同樣有中文顯示，僅一兩個技能為英文讀條。

**Comment by ACZife** [comment]
今天打P2S的時候有發現部分技能讀條為日文@@
