### ISSUE TITLE
點選單中的任務回顧，會發生 DX11 的錯誤

### ISSUE THREAD

**Issue by class2u** [GpointChen/FFXIVChnTextPatch-GP#14]
這個不確定是不是 NVIDIA 的鍋
我原本用 496.76 版本的顯示卡驅動程式，點選單 "任務情報 > 任務回顧" 時是正常的。
顯示卡驅動程式更新到最新的 497.09 版本後，點 "任務回顧" 會跳出 DX11 的錯誤，然後遊戲關閉（如圖）。
再重新安裝回 496.76 版本的驅動程式，還是一樣會發生 DX11 的錯誤。
但是把漢化還原成原始的日文版，是正常的。
又要麻煩你有空再看看了，再次感謝！

![2021-12-04](https://user-images.githubusercontent.com/420378/144695081-c27b40b0-ab55-482f-99d1-beb36e4f518e.png)

**Comment by GpointChen** [comment]
這個提示是漢化問題沒錯。

剛更新的[fixed-v5](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)目前點任務回顧沒有問題，你可以試著使用最新版看看。如果還有問題歡迎回報。

**Comment by class2u** [comment]
測試沒問題了！十分感謝，辛苦了！！
