### ISSUE TITLE
saintcoinach rawexd部分报错

### ISSUE THREAD

**Issue by lincTHU** [GpointChen/FFXIVChnTextPatch-GP#141]
![image](https://user-images.githubusercontent.com/8018928/163666789-276f20bb-c5e2-4113-9630-eda8cca80994.png)
汉化客户端后再生成rawexd会报上列错误 请问有遇到类似的问题吗

我是想先用国服官方翻译，然后在基础上生成rawexd，在自行汉化剩余部分

**Comment by GpointChen** [comment]
你是要輸出國服檔案？

如果是，國服是6.0，Definition和國際服6.1不同，要用舊版本的Definition。

**Comment by lincTHU** [comment]
> 

是输出国际服的档案。我是先用国服档案汉化了国际服，然后把国际服档案再输出成rawexd。这样csv里就有大部分汉化，然后我再把最新的部分个人汉化掉。
不过输出的时候用最新版的cmd报错了。

**Comment by GpointChen** [comment]
用6.0國服檔案漢化6.1國際服理論上也會出錯，道理同上。

其實release有附簡體CSV，也是基於官中來的，你可以參考。

**Comment by lincTHU** [comment]
> 用6.0國服檔案漢化6.1國際服理論上也會出錯，道理同上。
> 
> 其實release有附簡體CSV，也是基於官中來的，你可以參考。

嗯 release里的简体csv我有看到
这个csv是怎么获得的呢？我以为是先用国服档案汉化国际服以后，再将国际服档案用saintcoinach输出rawexd?
所以才想尝试自己跑一套

**Comment by GpointChen** [comment]
> > 用6.0國服檔案漢化6.1國際服理論上也會出錯，道理同上。
> > 其實release有附簡體CSV，也是基於官中來的，你可以參考。
> 
> 嗯 release里的简体csv我有看到 这个csv是怎么获得的呢？我以为是先用国服档案汉化国际服以后，再将国际服档案用saintcoinach输出rawexd? 所以才想尝试自己跑一套

是這樣沒錯。

之前5.x的時候國服與國際服結構沒有太大差異，所以可以直接套用。5.x更新至6.0和6.0更新至6.1時均有調整結構，所以無法直接使用。

現有的CSV是利用類似補丁的方式獲得，類似於拿5.x生成的CSV逐步加入6.0後更新內容。

如果你想要自己跑一套，理論上可以用SaintCoinach（with 6.0版的Definition）先輸出6.0中國服的CSV，然後修改幾個有改Def的檔案（如DawnMember什麼的），以及指令碼有變化的檔案（如completion.csv）後，使用漢化器漢化國際服，然後再拿Coinach（6.1 Definition）輸出國際服CSV。

**Comment by lincTHU** [comment]
> > > 用6.0國服檔案漢化6.1國際服理論上也會出錯，道理同上。
> > > 其實release有附簡體CSV，也是基於官中來的，你可以參考。
> > 
> > 
> > 嗯 release里的简体csv我有看到 这个csv是怎么获得的呢？我以为是先用国服档案汉化国际服以后，再将国际服档案用saintcoinach输出rawexd? 所以才想尝试自己跑一套
> 
> 是這樣沒錯。
> 
> 之前5.x的時候國服與國際服結構沒有太大差異，所以可以直接套用。5.x更新至6.0和6.0更新至6.1時均有調整結構，所以無法直接使用。
> 
> 現有的CSV是利用類似補丁的方式獲得，類似於拿5.x生成的CSV逐步加入6.0後更新內容。
> 
> 如果你想要自己跑一套，理論上可以用SaintCoinach（with 6.0版的Definition）先輸出6.0中國服的CSV，然後修改幾個有改Def的檔案（如DawnMember什麼的），以及指令碼有變化的檔案（如completion.csv）後，使用漢化器漢化國際服，然後再拿Coinach（6.1 Definition）輸出國際服CSV。

我把国际服包体还原成日语了，但是无论用4.7还是一月份的definition输出csv还是会报错诶。你又遇到类似的问题嘛？
![image](https://user-images.githubusercontent.com/8018928/164373770-3060a0b5-8bfc-4cc3-9387-af989c0ba08a.png)

**Comment by lincTHU** [comment]
> > > 用6.0國服檔案漢化6.1國際服理論上也會出錯，道理同上。
> > > 其實release有附簡體CSV，也是基於官中來的，你可以參考。
> > 
> > 
> > 嗯 release里的简体csv我有看到 这个csv是怎么获得的呢？我以为是先用国服档案汉化国际服以后，再将国际服档案用saintcoinach输出rawexd? 所以才想尝试自己跑一套
> 
> 是這樣沒錯。
> 
> 之前5.x的時候國服與國際服結構沒有太大差異，所以可以直接套用。5.x更新至6.0和6.0更新至6.1時均有調整結構，所以無法直接使用。
> 
> 現有的CSV是利用類似補丁的方式獲得，類似於拿5.x生成的CSV逐步加入6.0後更新內容。
> 
> 如果你想要自己跑一套，理論上可以用SaintCoinach（with 6.0版的Definition）先輸出6.0中國服的CSV，然後修改幾個有改Def的檔案（如DawnMember什麼的），以及指令碼有變化的檔案（如completion.csv）後，使用漢化器漢化國際服，然後再拿Coinach（6.1 Definition）輸出國際服CSV。

恩 我用了release里提供的简体csv汉化国际服档案后，再尝试输出新的csv 会报上面三个错误
测试了一下应该就是这三个文件有修改但是汉化没有更新的原因
替换成日语csv汉化再重新输出就没有报错了

所幸这三个文件里的汉化内容不是特别重要
