### ISSUE TITLE
漢化之後，一些副本任務沒辦法開始

### ISSUE THREAD

**Issue by tim71502** [GpointChen/FFXIVChnTextPatch-GP#142]
漢化之後 2.0的某些任務跟副本會沒辦法開始。可能跟更新有關吧?

**Comment by qwe3410475** [comment]
還是指出哪些部分沒辦法開始比較好
比較好除錯
我這邊暫時沒有發現這個問題

**Comment by tim71502** [comment]
> qwe3410475

像是在前面的主線有一個要去找熟練的老教官，跟他對話，結果啥事都沒有發生，然後就跳出一個紅字寫說無法開始過場動畫。要打副本，發現會沒辦法進入。我把他還原之後，就可以了

**Comment by GpointChen** [comment]
瞭解，之後遇到可以記一下任務名稱，方便我排查，感謝。

**Comment by tim71502** [comment]
> 

![image](https://user-images.githubusercontent.com/103833403/163707287-0ee8e06b-6134-4d83-9923-24727f6309aa.png)

**Comment by Mirage1102** [comment]
我也遇到相同的問題，使用0416漢化版本
也是相同的任務 點NPC右鍵後會卡很久 在聊天室出現 "無法開始過場劇情" 的訊息
切換回美版可以跟NPC正常互動

**Comment by GpointChen** [comment]
Fixed in v2.66.
