### ISSUE TITLE
0415更新完後可以玩 0416更新後出現6D錯誤

### ISSUE THREAD

**Issue by Yingyucho** [GpointChen/FFXIVChnTextPatch-GP#143]
復原後以原文可以進遊戲 漢化後還是會出現6D錯誤
回裝0415版還是不行
在出現6D錯誤後 我都直接還原 但是直接再啟遊戲還是會出現6D錯誤
所以都重啟電腦後再重複一次漢化 結果都是一樣6D
後來解決了 
在0416漢化後登入遊戲出現6D後 直接登出再登入
再登入遊戲已經可以玩了 分享給遇到相同6D錯誤的玩家參考一下

**Comment by HardCoreLewis** [comment]
![Uploading image.png…]()
國際服目前漢化會出現這個錯誤

**Comment by HardCoreLewis** [comment]
![Uploading image.png…]()
國際服目前漢化會出現這個錯誤

**Comment by GpointChen** [comment]
我目前沒有再遇過dx11問題了，不確定你是遇到什麼情況。

**Comment by GpointChen** [comment]
> 



> ![image](https://user-images.githubusercontent.com/73514041/163686159-edf575cd-3f9a-49f3-ac3b-42295ffe8256.png)
> 
> 國際服目前漢化會出現這個錯誤

你是用哪個版本？有log嗎？

**Comment by asdfghjtyuio** [comment]
我也是直接出現這個   目前已用使用[FFXIVChnTextPatch-0416.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.60/FFXIVChnTextPatch-0416.rar) 

![Uploading 錯誤ff14.jpg…]()

**Comment by asdfghjtyuio** [comment]
![Uploading 錯誤ff14.jpg…]()

**Comment by GpointChen** [comment]
> 我也是直接出現這個 目前已用使用[FFXIVChnTextPatch-0416.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.60/FFXIVChnTextPatch-0416.rar)
> 
> ![123](https://user-images.githubusercontent.com/103890302/163719063-3cf8bb3d-2b64-429c-9f25-8bfa02b12fe5.jpg)

有log嗎？

**Comment by HardCoreLewis** [comment]
> > 我也是直接出現這個 目前已用使用[FFXIVChnTextPatch-0416.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.60/FFXIVChnTextPatch-0416.rar)
> > ![123](https://user-images.githubusercontent.com/103890302/163719063-3cf8bb3d-2b64-429c-9f25-8bfa02b12fe5.jpg)
> 
> 有log嗎？

[2022-04-18 21:37:22] [INFO   ] Replace File : DawnGrowMember 
[2022-04-18 21:37:22] [INFO   ] [ReplaceEXDF] Now File : EXD/DawnMemberUIParam.EXH 
[2022-04-18 21:37:22] [INFO   ] Replace File : DawnMemberUIParam 
[2022-04-18 21:37:28] [SEVERE ] Patch failed! 
[2022-04-18 21:37:28] [SEVERE ] Error Messages: 

log最後幾行只到這
好像沒記錄到啥訊息@@

**Comment by Yingyucho** [comment]
> > > 我也是直接出現這個 目前已用使用[FFXIVChnTextPatch-0416.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.60/FFXIVChnTextPatch-0416.rar)
> > > ![123](https://user-images.githubusercontent.com/103890302/163719063-3cf8bb3d-2b64-429c-9f25-8bfa02b12fe5.jpg)
> > 
> > 
> > 有log嗎？
> 
> [2022-04-18 21:37:22] [INFO ] Replace File : DawnGrowMember [2022-04-18 21:37:22] [INFO ] [ReplaceEXDF] Now File : EXD/DawnMemberUIParam.EXH [2022-04-18 21:37:22] [INFO ] Replace File : DawnMemberUIParam [2022-04-18 21:37:28] [SEVERE ] Patch failed! [2022-04-18 21:37:28] [SEVERE ] Error Messages:
> 
> log最後幾行只到這 好像沒記錄到啥訊息@@
> 
> 抱歉回報一下，我不知道有0416版本了，一直還是用0325 還原後再用0416漢化已經沒問題了


= =

**Comment by GpointChen** [comment]
關閉本串，如使用新版仍有問題請另開新串。
