### ISSUE TITLE
请问能提供下CSV的提取工具吗

### ISSUE THREAD

**Issue by wingchaos** [GpointChen/FFXIVChnTextPatch-GP#15]
看了大佬的开发日志，发现不太会修改SC，，，，，

**Comment by GpointChen** [comment]
CSV是由修改過的SaintCoinach提取，如果需要日文原文的CSV，我附在[這裡](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)

如果想要做簡體中文的csv，也可以直接用工具對繁體CSV文本進行繁轉簡
