### ISSUE TITLE
沒有察看旅行筆錄的許可權

### ISSUE THREAD

**Issue by belle0976** [GpointChen/FFXIVChnTextPatch-GP#153]
在此回報一下我剛剛遇到的問題：這次我載了FFXIVChnTextPatch-0422-full.rar版來使用，目前我6.1主線都跑完了，之前漢化版本都可觀看旅行筆錄，但這次卻跳『沒有察看旅行筆錄的許可權』的提示出來，所以完全無法觀看，想說是否因漢化所產生的bug?再麻煩漢化組測試了，非常感謝您，辛苦了～

補充一下：我另外又載了『FFXIVChnTextPatch-0422.rar』來使用，結果一樣是無法觀看的情形。

![Final Fantasy XIV  A Realm Reborn Screenshot 2022 04 24 - 18 12 40 92 (2)](https://user-images.githubusercontent.com/95540085/164971613-f727f1f5-5576-44df-94a9-958f95e4111f.png)

**Comment by lewisyuk** [comment]
遇到同一問題

**Comment by HSIA0116** [comment]
也遇到相同問題，拔除漢化後可正常觀看

**Comment by belle0976** [comment]
更新一下資訊，現在我的旅行筆錄不知為何又可以看了，漢化版本沒有變更，不知道是否跟上次維護後有關？但不確定其他人是否問題還存在，雖目前漢化版本一直還是沒有更新，但還是非常感謝漢化組一直以來的除錯與漢化，謝謝您，真的辛苦你們了。

**Comment by Lxhen** [comment]
請問你是用哪個版本的?我目前還是無法看

**Comment by belle0976** [comment]
我用的是上面寫的版本『FFXIVChnTextPatch-0422.rar』沒有變更。可能這期間官方有維護，但我看沒有新版本的翻譯補丁，所以就沒有去動它，任由官方覆蓋更新，想說有問題再還原拔除漢化，因為我都有習慣在旅館上下線，前幾天我心血來潮又摸了一下旅行筆錄，突然就發現可以正常開啟了; 因為沒有更換版本就可以開啟了，覺得很奇怪，但還是來此更新一下資訊，順便給漢化組做個除錯參考，謝謝。

**Comment by Lxhen** [comment]
了解，感謝建議

**Comment by GpointChen** [comment]
應已修正於新版本。
