### ISSUE TITLE
80進戰職能任務翻譯錯誤

### ISSUE THREAD

**Issue by loey890802** [GpointChen/FFXIVChnTextPatch-GP#156]
![image](https://user-images.githubusercontent.com/103520791/165151223-0d0b5b79-b4d7-4713-9e10-6473dba93bac.png)
任妲。芮變成勇德大叔惹

**Comment by itsbosco1025** [comment]
沒錯啊，他原本不是就叫勇德？

**Comment by qwe3410475** [comment]
他在5.0就叫勇德
其他的叫 智德 義德 節德
叫做四樞德 
所以沒錯

**Comment by GpointChen** [comment]
感謝以上回覆。
