### ISSUE TITLE
發現一個問題進優雷卡島的npc沒辦法講話

### ISSUE THREAD

**Issue by Jason2321** [GpointChen/FFXIVChnTextPatch-GP#16]
發現問題優雷卡進不去

_Originally posted by @Jason2321 in https://github.com/GpointChen/FFXIVChnTextPatch-GP/issues/12#issuecomment-986075510_

**Comment by GpointChen** [comment]
修正於[fixed-v6](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.30)
