### ISSUE TITLE
5.5 主線 踏上旅途的決心

### ISSUE THREAD

**Issue by lolxpr** [GpointChen/FFXIVChnTextPatch-GP#162]
已完成主線任務''另一個未來'',接續下一個主線''踏上旅途的決心''時 石之家 阿莉塞消失 還原漢化也無法顯示NPC

**Comment by GpointChen** [comment]
不確定你是遇到什麼問題，但還原漢化是直接還原成你原本的遊戲檔案，如果還原漢化也有問題，可能是你原本的檔案就有損毀。

**Comment by lolxpr** [comment]
我再試試看,謝謝您!
