### ISSUE TITLE
最新版好像 InstanceContentTextData.csv 有特殊字元造成 exd 寫入格式錯誤

### ISSUE THREAD

**Issue by qwer20108** [GpointChen/FFXIVChnTextPatch-GP#166]
如備註
https://github.com/GpointChen/FFXIVChnTextPatch-GP/commit/4767ab7ed8ea6ffd3d0978cb5b69ae73dfe9745a#r73310139
這個8900 8901 這兩行疑似有特殊字元造成 exd 寫入格式錯誤,

手動 revert 後重新寫入 exd 就沒事了

**Comment by GpointChen** [comment]
應已修正於v2.63。
