### ISSUE TITLE
萬魔殿零式四層，近思/遠見的魔擊沒有顯示出來

### ISSUE THREAD

**Issue by NekoMilkTea** [GpointChen/FFXIVChnTextPatch-GP#167]
版本：6.11 5/8
![ffxiv_10052022_233313_105](https://user-images.githubusercontent.com/26368090/167669832-78839c1b-bd07-4a4a-aece-6f4fde292692.png)

萬魔殿零式四層，近思/遠見的魔擊沒有顯示出來，不知道是不是只有我有這個問題

**Comment by Bos-hunting** [comment]
我也是 希望可以快點修復

**Comment by kalispp** [comment]
急的話可以自己先修改一下Action.csv

27174,"_rsv_27174_-1_4_C0_0Action",    改為   27174:"近思魔擊",
27175,"_rsv_27175_-1_4_C0_0Action",    改為   27175,"遠見魔擊",
27176,"_rsv_27176_-1_4_C0_0Action",    改為   27176:"近思魔擊",

然後再重跑一次漢化應該可以

**Comment by GpointChen** [comment]
應已修正於v2.63。
