### ISSUE TITLE
簡體中文版中的戰士技能"重噼"應為"重劈"。

### ISSUE THREAD

**Issue by Souma-Sumire** [GpointChen/FFXIVChnTextPatch-GP#168]
如題。
該字段出現在
Action.csv
ActionTransient.csv
ActionComboRouteTransient.csv
TextCommand.csv
TraitTransient.csv
quest\003\ClsExc050_00313.csv
quest\003\ClsExc150_00316.csv
quest\032\LucKbc003_03212.csv
custom\003\RegSeaBeginnerTankGuide_00337.csv

**Comment by GpointChen** [comment]
應已修正於v2.63。

**Comment by Souma-Sumire** [comment]
感謝修復，但令人抱歉的是，我後續發現大量技能名中的“劈”字都不應該為“噼”，並不只有重劈這一個單例。
