### ISSUE TITLE
遊玩到一半突然閃退後跑出問題

### ISSUE THREAD

**Issue by Fubuki520** [GpointChen/FFXIVChnTextPatch-GP#169]
玩到一半閃退後就一直跑出問題了
有試過多次重新翻譯和重載
不知道有沒有人也有一樣的問題
![image](https://user-images.githubusercontent.com/103637448/168488123-0e5c1930-e570-4ffa-b2bb-3218d27fa0da.png)

**Comment by lolxpr** [comment]
跟你一樣的問題,搞了好多天搞不定,應該跟漢化無關;不知道是顯卡更新還是系統更新某個驅動之後就一直跑出這條訊息

**Comment by GpointChen** [comment]
Closed as inactive.
