### ISSUE TITLE
英文版漢化後任務對話文字大小

### ISSUE THREAD

**Issue by class2u** [GpointChen/FFXIVChnTextPatch-GP#17]
您好！
對英文版進行漢化後，和 NPC 對話時（畫面下方中間那個白底大大的）對話框內的文字大小似乎被縮小了（和日文版漢化後比較起來），有點模糊也看不太清楚，不知道等您有空時，這部分是否能夠調整一下，非常感謝！

第一張圖是英文版漢化，第二張圖是日文版漢化
![ffxiv_12052021_104822_831](https://user-images.githubusercontent.com/420378/144731612-9e7d69b7-bdc2-4693-ba66-4b320448b629.png)

![ffxiv_12052021_110130_468](https://user-images.githubusercontent.com/420378/144731761-dee23b79-62cc-4e8b-a9e6-8b8615eca448.png)

**Comment by GpointChen** [comment]
文字的大小是與語言綁定的，目前沒有考慮研究和處理這個部分

建議去設定手動放大對話框（介面尺寸）

**Comment by class2u** [comment]
好的，我瞭解了，非常感謝您！
