### ISSUE TITLE
壓縮檔無法開啟

### ISSUE THREAD

**Issue by momo0217** [GpointChen/FFXIVChnTextPatch-GP#175]
下載壓縮檔後解壓縮都會顯示(壓縮檔錯誤)和(找不到壓縮檔)
想問版上的大大有沒有遇到這樣的問題

**Comment by GpointChen** [comment]
你是使用什麼解壓縮軟體？我是winrar

**Comment by GpointChen** [comment]
Closed as inactive. 如有類似問題可另開新串。
