### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by michaaeq** [GpointChen/FFXIVChnTextPatch-GP#177]
挑戰沙斯塔夏之人無法觀看任務動畫以及有些文本看完任務無法完成

**Comment by GpointChen** [comment]
應與 #142 是相同問題，
有空的時候會進行排查，感謝回報。

**Comment by GpointChen** [comment]
測試於v2.64漢化中的昔日重現模式可以正常進行任務。如仍有問題可回覆或另開新帖。
