### ISSUE TITLE
無法和老練冒險者對話

### ISSUE THREAD

**Issue by neil921228** [GpointChen/FFXIVChnTextPatch-GP#178]
主線任務-挑戰沙斯塔夏之人
無法進行"和初學者學堂的公會的老練冒險者對話"

錯誤訊息:無法開始過場劇情

**Comment by neil921228** [comment]
Patch Tool 6.11 5/22
語言包:CSV
語言:正體中文
還原後可以正常接任務 接完再次漢化

**Comment by GpointChen** [comment]
應與 #142 是相同問題，
有空的時候會進行排查，感謝回報。

**Comment by GpointChen** [comment]
> Patch Tool 6.11 5/22 語言包:CSV 語言:正體中文 還原後可以正常接任務 接完再次漢化

請問是接完任務、跑過第一段過場後切回來就正常了嗎？

**Comment by GpointChen** [comment]
測試於v2.64漢化中的昔日重現模式可以正常進行任務。如仍有問題可回覆或另開新帖。
