### ISSUE TITLE
汉化后偶尔会出现游戏崩溃的问题

### ISSUE THREAD

**Issue by Tachyonwing** [GpointChen/FFXIVChnTextPatch-GP#180]
使用CSV、简体中文资源、4K字体对<英语客户端>进行汉化，

偶尔会出现dx11错误导致游戏崩溃。在旧萨雷安这张地图特别容易崩溃。

![1](https://user-images.githubusercontent.com/107910749/174733106-9bb7a8f0-7243-458f-abe7-830055816df7.png)

**Comment by GpointChen** [comment]
感謝回報，我會進行排查，如有固定會崩潰處也歡迎回報。

**Comment by GpointChen** [comment]
Fixed in v2.66. 如仍有問題可另開新串。
