### ISSUE TITLE
此章節無漢化

### ISSUE THREAD

**Issue by rioyoru** [GpointChen/FFXIVChnTextPatch-GP#182]
![image](https://user-images.githubusercontent.com/108154588/175664143-48449ac2-48f7-48d7-91f9-23bc0a1b2475.png)
此章節未被漢化到不知道是否是原本就沒漢化檔，後面章節尚未打到不確定是否也沒有漢化到

**Comment by rioyoru** [comment]
目前看是任務內容沒被漢化到，故事內容有漢化

**Comment by itsbosco1025** [comment]
這個是因爲6.1有針對2.0的内容做了些許的調整（主要是後面副本改了，更加User Friendly），因此只有這段内容是日文,後面應該不會有問題。

**Comment by GpointChen** [comment]
如上所答，感謝回報。
