### ISSUE TITLE
取迴 -> 取回

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#183]
https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/823adc2726a2a92967415eb730bc14d220c9eb5f/resource/rawexd/Addon.csv#L9754

https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/ContentFinderConditionTransient.csv#L724

**Comment by GpointChen** [comment]
感謝回報，將於下次更新修正。

**Comment by GpointChen** [comment]
已修正於v2.64。
