### ISSUE TITLE
汉化后游戏闪退

### ISSUE THREAD

**Issue by shadowshadow725** [GpointChen/FFXIVChnTextPatch-GP#187]
![image](https://user-images.githubusercontent.com/20177304/177056387-fa3fe3f3-ca98-469b-b6e9-a92aaa331af1.png)

步骤如下：

- 把国服客户端的6个文件复制到 resource/text
- 启动汉化程序
- 设置如下

![image](https://user-images.githubusercontent.com/20177304/177056494-d8052971-7bfe-4915-ad7d-128011aa52c5.png)

- 点汉化
- 打开游戏然后crash

已确认国服文件没有问题

**Comment by GpointChen** [comment]
中國服現在應該是6.0吧？6.0到6.1之間檔案結構有些許改變，所以目前建議使用簡體CSV。
