### ISSUE TITLE
品質轉換 -> 質量轉換

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#190]
Action.csv
`23054,"品質轉換",False,405,4,0,8,24,3208,1875,0,-1,0,0,False,0,True,False,False,False,False,False,False,False,False,0,False,False,1,0,0,False,0,0,0,0,0,False,40,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,0,0,False,False,True,False,False,True,False,False,True,0,False,False,False`

Status.csv
`2447,"品質轉換","將品質進行轉換，重物變輕，輕物變重",15317,0,0,1,2,17,0,False,False,False,False,False,False,False,False,False,200,0,False,False,0,0,False,0,False,False,0,0,0,False`

由於技能描述提及重物變輕, 所以品質應為質量

**Comment by GpointChen** [comment]
感謝回報，將於下次更新修正。

**Comment by GpointChen** [comment]
Fixed in v2.66.
