### ISSUE TITLE
limsa lominsa軍需官裝備換軍票時卡住

### ISSUE THREAD

**Issue by souhang** [GpointChen/FFXIVChnTextPatch-GP#193]
在limsa lominsa軍需官處選擇兌換軍票的對話後並沒有出現相對應的兌換界面，但此時系統會判定為已經進入兌換頁面的狀態，而且人物無法移動，無法esc取消，無法透過遊戲内所提供的方式離開遊戲。
目前只有測試日文轉繁中。

**Comment by GpointChen** [comment]
我不是所屬利姆薩，我個人測試和格里達尼亞的軍需官兌換沒有遇到任何問題，而和利姆薩軍需官說話也沒有卡住。

![image](https://user-images.githubusercontent.com/34565875/183504294-3ef230a6-faaf-49bb-bc3c-ad6a9b47c7da.png)

↑你是跟這個人對話的時候遇到問題嗎？

順便可能要麻煩你幫我確認：你是使用哪個release版本？還原漢化後能否正常兌換？

**Comment by souhang** [comment]
測試環境：
1. 漢化工具：FFXIVChnTextPatch-0706
2. 遊戲用戶端： 2022.03.25.0000.0001(7522205) - 3.3.0
3. 原有漢化： 英文轉繁體中文
4. 測試時用戶端語言： 日文

測試項目：
1. 還原漢化（繁體中文轉英文）後，與目標（利姆薩·羅敏撒 軍需官、摩杜納 收藏品交易員 ）進行對話
發生了回報内容中描述的錯誤

2. 使用漢化工具（日文轉繁體中文）後，與相同目標對話
發生了回報内容中描述的錯誤

3. 還原漢化（繁體中文轉日文）後，與相同目標對話

發生了回報内容中描述的錯誤


為了確認漢化工具與0a0000檔案沒有受到其他因素影響，我重新下載了漢化工具，並對遊戲替換了乾淨的0a0000檔案，再次做了以下測試：
1. 在替換了乾净的0a0000檔案檔案（日文）後，與目標（利姆薩·羅敏撒 軍需官、摩杜納 收藏品交易員 ）進行對話
未發生回報内容中描述的錯誤

2. 使用漢化工具（日文轉繁體中文）後，與相同目標對話
未發生回報内容中描述的錯誤

3. 還原漢化後，與相同目標進行對話
未發生回報内容中描述的錯誤

結論：
漢化工具沒有問題，是0a0000檔案受到了汙染，非常抱歉浪費了你的時間，以後我會做完詳盡的測試後再回報錯誤的

**Comment by GpointChen** [comment]
解決就好！
