### ISSUE TITLE
安裝時彈出java錯誤該如何解決？

### ISSUE THREAD

**Issue by sakotap** [GpointChen/FFXIVChnTextPatch-GP#194]

**Comment by mosluce** [comment]
@sakotap  給個截圖或顯示的訊息吧 ... 不然不知道你是啥問題

**Comment by pearcehao** [comment]
![image](https://user-images.githubusercontent.com/103523684/181833981-68cc1b5d-54b2-4221-873c-a4c348399697.png)
 both

**Comment by mosluce** [comment]
@pearcehao 你需要先安裝 JRE 至少 16 以上，現在最新應該是 18

**Comment by GpointChen** [comment]
你可以試著安裝 openjdk version 16.0.1以上的版本。

如果已經安裝，請確認是否有其他舊版的Java，以及環境變數是否設置正確。

你可以先透過`java -version`來測試自己的Java環境。

**Comment by BBC30** [comment]
我的java己更新成這樣, 同樣出現 "" This application requires a Java Runtime Environment 16.0.1 ""
要怎樣解決呢?  
![18](https://user-images.githubusercontent.com/111221445/184528521-454967df-4de4-4e1a-a9e9-473a5e297e31.PNG)

**Comment by GpointChen** [comment]
> 我的java己更新成這樣, 同樣出現 "" This application requires a Java Runtime Environment 16.0.1 "" 要怎樣解決呢? ![18](https://user-images.githubusercontent.com/111221445/184528521-454967df-4de4-4e1a-a9e9-473a5e297e31.PNG)

你這個是Java 8，這個系列9以後的版本需要付費，
可以試著搜尋並安裝OpenJDK 16以後的版本

**Comment by BBC30** [comment]
> > 我的java己更新成這樣, 同樣出現 "" This application requires a Java Runtime Environment 16.0.1 "" 要怎樣解決呢? ![18](https://user-images.githubusercontent.com/111221445/184528521-454967df-4de4-4e1a-a9e9-473a5e297e31.PNG)
> 
> 你這個是Java 8，這個系列9以後的版本需要付費， 可以試著搜尋並安裝OpenJDK 16以後的版本

要不要先uninstall原來的Java 8呢?

**Comment by GpointChen** [comment]
> > > 我的java己更新成這樣, 同樣出現 "" This application requires a Java Runtime Environment 16.0.1 "" 要怎樣解決呢? ![18](https://user-images.githubusercontent.com/111221445/184528521-454967df-4de4-4e1a-a9e9-473a5e297e31.PNG)
> > 
> > 
> > 你這個是Java 8，這個系列9以後的版本需要付費， 可以試著搜尋並安裝OpenJDK 16以後的版本
> 
> 要不要先uninstall原來的Java 8呢?

要喔，不然裝兩個版本的Java可能會導致讀到舊版。

**Comment by BBC30** [comment]
> > > > 我的java己更新成這樣, 同樣出現 "" This application requires a Java Runtime Environment 16.0.1 "" 要怎樣解決呢? ![18](https://user-images.githubusercontent.com/111221445/184528521-454967df-4de4-4e1a-a9e9-473a5e297e31.PNG)
> > > 
> > > 
> > > 你這個是Java 8，這個系列9以後的版本需要付費， 可以試著搜尋並安裝OpenJDK 16以後的版本
> > 
> > 
> > 要不要先uninstall原來的Java 8呢?
> 
> 要喔，不然裝兩個版本的Java可能會導致讀到舊版。

沒有exe或msi檔, 知道要怎樣install嗎?
![Uploading 擷取.JPG…]()

**Comment by GpointChen** [comment]
https://www.java.com/zh-TW/download/help/uninstall_java.html

試試看這個？
