### ISSUE TITLE
挑戰沙斯塔夏之人，任務的問題又出現了

### ISSUE THREAD

**Issue by peckcat** [GpointChen/FFXIVChnTextPatch-GP#197]
於07/27 使用 7/6 v2.65 版本
發生了同樣問題

情況如下

使用新角色開始遊玩，而非昔日重現。
1. 無法與老練的冒險者開啟對話，換成其他語言後即可正常對話完成。
2. 自上述條目與『老練得冒險者』對話後，切換回中文化。
    下一位 NPC 『黃衫隊警備兵』雖然可以正常對話，但是對話完無法開啟副本，
    切換其他語言對話後則可以正常開啟副本。

經比對 Quest.csv 檔案
65781 條目
rawexd-ja-618 與 v2.65 內容有明顯差異

![image](https://user-images.githubusercontent.com/7374380/181078613-e806e385-d25a-43e0-b2f9-4d42bac84184.png)

**Comment by GpointChen** [comment]
感謝找出原因！會於下次更新修正。

**Comment by GpointChen** [comment]
Fixed in v2.66.
