### ISSUE TITLE
漢化中卡住

### ISSUE THREAD

**Issue by Kz155** [GpointChen/FFXIVChnTextPatch-GP#205]
用csv漢化會卡死在EXD/quest.EXH

**Comment by peckcat** [comment]
這邊正常執行，看是否有還原乾淨的 000000開頭 以及 0a0000開頭 等共六個檔案

**Comment by GpointChen** [comment]
同上所回覆，可以先確認漢化前是否為乾淨的原始檔案，release頁面也可以找到原始檔的下載連結。

所謂的卡住是跳出漢化錯誤還是？麻煩附上log方便診斷。

**Comment by GpointChen** [comment]
Closed due to inactivity.
