### ISSUE TITLE
部分翻譯問題回報

### ISSUE THREAD

**Issue by liuedd** [GpointChen/FFXIVChnTextPatch-GP#206]
1."云游" (雲遊)四方

武士 80等職業任務 仗劍行俠無雙齋傳
![ffxiv_dx11_LyDEl37GeT](https://user-images.githubusercontent.com/51795301/184629964-f826b6f3-e73c-4d8e-9837-18cf259d7ef9.png)

2.天工釣竿複製品

原始天工釣竿為中文，複製品仍是日文

![ffxiv_dx11_zn9AZY2DMW](https://user-images.githubusercontent.com/51795301/184630349-0db4ca32-69a7-4974-b1ab-d299ee15fc91.png)

3. 部分補師的Dot技能持續時間應為30秒

白魔的 疾風、烈風/ 占星的燒灼 說明寫18秒，應為30秒

4.九宮幻卡 no.241 "採"(采)夫婦
![ffxiv_dx11_eJu9ZmaWYv](https://user-images.githubusercontent.com/51795301/184631169-fc0c35af-9543-41e8-ad9a-1d9d34edddc5.png)

5.犯"困"(睏)的魔法大學學生

在舊薩雷安的支線任務 "秘密就在木箱中" 的其中一位NPC

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

**Comment by GpointChen** [comment]
> 3\. 部分補師的Dot技能持續時間應為30秒
> 
> 白魔的 疾風、烈風/ 占星的燒灼 說明寫18秒，應為30秒

我這邊看都是30秒欸

還是你是在其他地方看到別的秒數

```
121,"對目標發動風屬性魔法攻擊　<hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>50<hex:02100103><hex:024804F201F803><hex:024904F201F903>追加效果：<hex:0249020103><hex:0248020103>風屬性持續傷害<hex:02100103><hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>30　<hex:024804F201F803><hex:024904F201F903>持續時間：<hex:0249020103><hex:0248020103>30秒"
```
```
132,"對目標發動風屬性魔法攻擊　<hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>50<hex:02100103><hex:024804F201F803><hex:024904F201F903>追加效果：<hex:0249020103><hex:0248020103>風屬性持續傷害<hex:02100103><hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>50　<hex:024804F201F803><hex:024904F201F903>持續時間：<hex:0249020103><hex:0248020103>30秒"
```
```
3599,"對目標附加無屬性持續傷害狀態<hex:02100103><hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>40　<hex:024804F201F803><hex:024904F201F903>持續時間：<hex:0249020103><hex:0248020103>30秒"
```

**Comment by liuedd** [comment]
> > 3. 部分補師的Dot技能持續時間應為30秒
> > 白魔的 疾風、烈風/ 占星的燒灼 說明寫18秒，應為30秒
> 
> 我這邊看都是30秒欸
> 
> 還是你是在其他地方看到別的秒數
> 
> ```
> 121,"對目標發動風屬性魔法攻擊　<hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>50<hex:02100103><hex:024804F201F803><hex:024904F201F903>追加效果：<hex:0249020103><hex:0248020103>風屬性持續傷害<hex:02100103><hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>30　<hex:024804F201F803><hex:024904F201F903>持續時間：<hex:0249020103><hex:0248020103>30秒"
> ```
> 
> ```
> 132,"對目標發動風屬性魔法攻擊　<hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>50<hex:02100103><hex:024804F201F803><hex:024904F201F903>追加效果：<hex:0249020103><hex:0248020103>風屬性持續傷害<hex:02100103><hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>50　<hex:024804F201F803><hex:024904F201F903>持續時間：<hex:0249020103><hex:0248020103>30秒"
> ```
> 
> ```
> 3599,"對目標附加無屬性持續傷害狀態<hex:02100103><hex:024804F201F803><hex:024904F201F903>威力：<hex:0249020103><hex:0248020103>40　<hex:024804F201F803><hex:024904F201F903>持續時間：<hex:0249020103><hex:0248020103>30秒"
> ```

剛剛才發現原來我還是0706舊版，安裝0809版本秒數是正確的，烏龍回報相當抱歉

**Comment by GpointChen** [comment]
已修正於v2.67。
