### ISSUE TITLE
英文游戏覆盖后打开某些UI会出现奇妙的日文？

### ISSUE THREAD

**Issue by invinciberry** [GpointChen/FFXIVChnTextPatch-GP#21]
FF14海外区新人，感谢大佬的翻译工具
——————
昨天用英文版游戏翻译后成功，但很多菜单出现了日文，不知道是不是bug，也不知道是否印象游戏。还在排队。

**Comment by GpointChen** [comment]
因為一開始我忘記有些人會用來覆蓋英文，轉完檔後直接拿日文的檔案覆蓋了一部份文本，所以可能會有部分文字出現這樣的情況。

你也可以舉例或截圖出現日文的地方，方便排查。

**Comment by howie901216** [comment]
![image](https://user-images.githubusercontent.com/65068993/145661316-5fdf3e04-4317-4479-8a23-453f6a0420b9.png)
好像一部份UI有這種情況
不過個人感覺影響不大
辛苦了！

**Comment by Bos-hunting** [comment]
![image](https://user-images.githubusercontent.com/95756995/145689633-3025d066-0e70-41d3-94bd-843c40dbacf2.png)
用英譯中 魂武的任務是英文 麻煩大佬了

**Comment by AdiBKDWs** [comment]
https://imgur.com/ZW5xtmA.png
查看成就時發現完全空白

**Comment by GpointChen** [comment]
> ![image](https://user-images.githubusercontent.com/95756995/145689633-3025d066-0e70-41d3-94bd-843c40dbacf2.png) 用英譯中 魂武的任務是英文 麻煩大佬了

![螢幕擷取畫面 (1526)](https://user-images.githubusercontent.com/34565875/145701066-7bfa8791-a2cf-4f0c-a04c-227f9672f7cc.png)

我看是正常的。
請問你的`resource\rawexd\quest\022\JobRel101_02212.csv`是中文嗎？

**Comment by GpointChen** [comment]
> https://imgur.com/ZW5xtmA.png 查看成就時發現除了中間其他都是空白

![螢幕擷取畫面 (1527)](https://user-images.githubusercontent.com/34565875/145701177-242a1df7-a6ef-4ecf-9c13-02001ea31311.png)

我這裡是有東西的，雖然還沒翻譯。

你是使用[最新的exe](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.40)嗎？

**Comment by GpointChen** [comment]
> ![image](https://user-images.githubusercontent.com/65068993/145661316-5fdf3e04-4317-4479-8a23-453f6a0420b9.png) 好像一部份UI有這種情況 不過個人感覺影響不大 辛苦了！

基本上副標應該都是這樣的日文，目前預計不會花時間改這部份。
這些UI文字都在`Addon.csv`裡面，如果想去除的話也可以自行找改。

**Comment by Bos-hunting** [comment]
> > ![image](https://user-images.githubusercontent.com/95756995/145689633-3025d066-0e70-41d3-94bd-843c40dbacf2.png) 用英譯中 魂武的任務是英文 麻煩大佬了
> 
> ![螢幕擷取畫面 (1526)](https://user-images.githubusercontent.com/34565875/145701066-7bfa8791-a2cf-4f0c-a04c-227f9672f7cc.png)
> 
> 我看是正常的。 請問你的`resource\rawexd\quest\022\JobRel101_02212.csv`是中文嗎？

檢查了的確是中文，我再試多幾次還原漢化看看行不行。麻煩了，謝謝大佬！

**Comment by Bos-hunting** [comment]
> > > ![image](https://user-images.githubusercontent.com/95756995/145689633-3025d066-0e70-41d3-94bd-843c40dbacf2.png) 用英譯中 魂武的任務是英文 麻煩大佬了
> > 
> > 
> > ![螢幕擷取畫面 (1526)](https://user-images.githubusercontent.com/34565875/145701066-7bfa8791-a2cf-4f0c-a04c-227f9672f7cc.png)
> > 我看是正常的。 請問你的`resource\rawexd\quest\022\JobRel101_02212.csv`是中文嗎？
> 
> 檢查了的確是中文，我再試多幾次還原漢化看看行不行。麻煩了，謝謝大佬！

![image](https://user-images.githubusercontent.com/95756995/145708528-f393a68e-526f-4308-8cd2-4f09e8c45038.png)
![image](https://user-images.githubusercontent.com/95756995/145708566-30e31aec-d57b-4898-b3c4-8a9ed601ac1c.png)
修好了，感謝您的耐心。但是英譯中好像有這些小問題，不過無傷大雅。
