### ISSUE TITLE
6.2 傳到游末邦會報錯閃退

### ISSUE THREAD

**Issue by liuedd** [GpointChen/FFXIVChnTextPatch-GP#211]
![ERROR](https://user-images.githubusercontent.com/51795301/186151500-b976aa0e-13f8-487a-b38c-87d351248151.png)

移除後就能正常登入了，再麻煩作者了，謝謝

**Comment by GpointChen** [comment]
了解，先讓我載一下6.2 XD

**Comment by maaapp56** [comment]
已確認
確定會閃退
可能指令碼有異動

**Comment by GpointChen** [comment]
已修正於v2.67。
