### ISSUE TITLE
更新6.2后汉化进入游戏出现问题

### ISSUE THREAD

**Issue by NMSLCAO** [GpointChen/FFXIVChnTextPatch-GP#212]
![Screenshot 2022-08-23 075236](https://user-images.githubusercontent.com/77854038/186152155-7a9653d3-5ae0-4e3a-b9dd-746e9e399b38.png)
尝试过论坛里提出的方法二，重试了十次依旧报错。希望大大帮忙解决一下，谢谢！！！

**Comment by GpointChen** [comment]
了解，先讓我載一下6.2 XD

**Comment by GpointChen** [comment]
已修正於v2.67。
