### ISSUE TITLE
关于6.2之后汉化报错

### ISSUE THREAD

**Issue by ultimateomega** [GpointChen/FFXIVChnTextPatch-GP#213]
我大概找到了问题，就是国际服对于主线任务可能又进行了修改。因为我用国服文件替换一开始是可以正常进入游戏的，但是到了主线披雪大冰壁结束后的CG，就开始报错，推测是之后的任务文本和剧情演出与国服现版本文件有差异导致的。

**Comment by GpointChen** [comment]
已修正於v2.67。
