### ISSUE TITLE
女王古殿無法進入

### ISSUE THREAD

**Issue by minatoshiro** [GpointChen/FFXIVChnTextPatch-GP#215]
您好，在利用8/24日的更新檔之後
想要排隊進入女王古殿會無法進入。
情境和之前挑戰沙斯塔夏之人的情況基本相同。
個人情況是也是初見利用水琴npc進入的初見有這樣的情況。

**Comment by minatoshiro** [comment]
> 您好，在利用8/24日的更新檔之後 想要排隊進入女王古殿會無法進入。 情境和之前挑戰沙斯塔夏之人的情況基本相同。 個人情況是也是初見利用水琴npc進入的初見有這樣的情況。

經由測試後發現是整個伯茲雅副本都無法進入，遊戲會直接卡死無法進行互動。

**Comment by GpointChen** [comment]
你是使用 9:00 更新的fixed版本嗎？我剛才測試可以進入博茲雅

**Comment by minatoshiro** [comment]
您好，是我沒留意到九點有新的更新資料，取代昨日resource的資料夾後已經可以正常進入。
非常謝謝您的抽空回覆，辛苦了。
