### ISSUE TITLE
与进入优雷卡的npc对话后卡住

### ISSUE THREAD

**Issue by miciix** [GpointChen/FFXIVChnTextPatch-GP#220]
不显示对话内容，鼠标也无法使用只能强退游戏。

**Comment by GpointChen** [comment]
請確定你是下載帶fixed版本的rar，這個問題應該已經於該更新中修復。

**Comment by GpointChen** [comment]
![image](https://user-images.githubusercontent.com/34565875/187013881-3b000099-132b-4c06-be7f-428872b46d7a.png)
