### ISSUE TITLE
伊修加德住宅區，購買公寓失敗

### ISSUE THREAD

**Issue by peckcat** [GpointChen/FFXIVChnTextPatch-GP#222]
使用 FFXIVChnTextPatch-0823-fixed.rar
購買伊修加德公寓的時候，會購買失敗。
單純換成英文後則購買成功。

**Comment by GpointChen** [comment]
應該是Addon.csv中下面這行的問題
```
6710,"公寓"
```
應該改成下面這樣，然後儲存、還原、重新漢化就可以了。我會在下次更新時修正，有遇到問題的人可以試試看。
```
6710,"Apartment"
```
