### ISSUE TITLE
和博兹亚入口npc对话卡住

### ISSUE THREAD

**Issue by DragonMyth** [GpointChen/FFXIVChnTextPatch-GP#223]
使用 FFXIVChnTextPatch-0823-fixed.rar 的简体汉化，
和博兹亚门口npc谢罗斯对话后卡住不出现对话框， 之后没办法进行任何操作。
换成英文版后没有这个问题

**Comment by GpointChen** [comment]
請確認使用的是rawexd-zhcn-0823-fixed.rar的簡體csv，這個問題應已於該版本修復

你也可以檢查自己的檔案是否如 https://github.com/GpointChen/FFXIVChnTextPatch-GP/commit/3fa1e117ab4d67e8b560bad1a8b5fc218b42f0f3 更新

例如博茲雅入口的對話應該在
* resource/rawexd/custom/007/CtsMycEntranceHard_00706.csv
* resource/rawexd/custom/007/CtsMycEntranceNormal_00705.csv

**Comment by DragonMyth** [comment]
换成新csv就能用了！ 谢谢！
