### ISSUE TITLE
任務搜尋器隨機任務翻譯錯誤

### ISSUE THREAD

**Issue by meyeryu** [GpointChen/FFXIVChnTextPatch-GP#225]
如下圖，應為90級，但文字和內文均為80級
<img width="945" alt="FINAL FANTASY XIV 2022_8_29 下午 06_16_36" src="https://user-images.githubusercontent.com/16871756/187182302-9b9d3be4-be0a-4663-be12-7d4a02aea6fc.png">

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修復。

**Comment by GpointChen** [comment]
Fixed in v2.69.
