### ISSUE TITLE
人魚發->人魚髮

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#226]
resource/rawexd/Item.csv

`29766,"人魚發",0,"",0,0,1,0,0,"一種大型頭足類生物，船員們稱之為人魚的頭髮。<hex:02100103>加拉迪翁灣外海的稀有魚。<hex:02100103>可以拓印在中型魚拓畫框上。","人魚發",29072,1,2,16,0,47,46,0,15,30000,999,False,False,False,False,533,16,False,False,False,0,2,0,15,0,0,6443,False,False,0,1,0,0,0,0,0,0,"0, 0, 0, 0","0, 0, 0, 0",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,0,False`

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

**Comment by GpointChen** [comment]
Fixed in v2.69.
