### ISSUE TITLE
4K字體包問題 (在進入厄爾庇斯出現了錯誤，還原後依然沒辦法進入遊戲)

### ISSUE THREAD

**Issue by ddt454130** [GpointChen/FFXIVChnTextPatch-GP#227]
![未命名](https://user-images.githubusercontent.com/109537072/188224753-f9c37440-8db8-4a40-b550-5dce9ddb6eb0.png)

**Comment by GpointChen** [comment]
1. 請確認你是否是使用最新版的漢化。
2. 還原後仍無法進入遊戲代表你原本的遊戲檔案有問題，可使用release所附的backup-0823.rar還原。

**Comment by ddt454130** [comment]
感謝您的回覆~!
我是用新版和話沒錯。
另外還原的部分用backup-0823.rar自動跟手動狀況還一樣...
目前正在讓遊戲修復中。

**Comment by GpointChen** [comment]
遊戲在維護時有不影響漢化的小更新，如果你在未還原的情況下更新了遊戲，可能會導致出現問題。

我剛才測試可以進入厄爾庇斯。

我待會上傳一個新的release和backup檔案。

**Comment by GpointChen** [comment]
v2.69 已上傳。

**Comment by ddt454130** [comment]
感謝您的協助！
關於小更新的部分，這點我有注意到，所以都會在更新前一天做還原的動作。
另外想請教一點，我和朋友都是用您這邊的漢化進行遊戲，唯一不同的地方是我有裝"第三方4K字體包"。
關於字體包的部分，是否會有可能造成這次錯誤的原因呢？

**Comment by GpointChen** [comment]
不無可能，我也沒有裝4K字體。

**Comment by GpointChen** [comment]
應該確實是4K字體包的問題，我用自製的4K字體嘗試了一下也有問題。

之後有空會處理。

**Comment by GpointChen** [comment]
[v2.72.2](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.2)重增高畫質字體包。

**Comment by ddt454130** [comment]
> [v2.72.2](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.2)增加高質量字體包。

Oh!YA!!
先跟你說聲：辛苦了～
非常感謝您的告知！
我這就立即去安裝體驗。
