### ISSUE TITLE
遊戲路徑設定好像會跑掉

### ISSUE THREAD

**Issue by davyblue** [GpointChen/FFXIVChnTextPatch-GP#23]
第一次選好路徑按漢化後關掉，重新開啟按還原，再按漢化就會顯示程式錯誤
此時只要重新選擇遊戲路徑就會好

**Comment by GpointChen** [comment]
這部份應該是原專案的設定，預計之後修正。

**Comment by GpointChen** [comment]
修正於[12/16-fixed](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.42)。

如仍有問題歡迎回報。
