### ISSUE TITLE
武士技能 花車 技能敘述錯誤 

### ISSUE THREAD

**Issue by LuminousT** [GpointChen/FFXIVChnTextPatch-GP#232]
![image](https://user-images.githubusercontent.com/114006504/191294668-c765b54b-900b-4dc5-88f6-22c474a9691b.png)

上圖第2行與第4行
應該是側面而不是背面

![image](https://user-images.githubusercontent.com/114006504/191295338-b046e1a4-f5e3-4a4a-826e-2f2b8929d7d7.png)

**Comment by karaipsum** [comment]
這個問題好像是國服更新後就有的文字錯誤，可能要等待作者修正或者等國服更新後修正再繁化

**Comment by GpointChen** [comment]
已修正。感謝回報。
