### ISSUE TITLE
建議將 6.1友好部族任務白頻對話換成英語

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#237]
`將聊天頻道設定為「說話」頻道後，
使用鍵盤或軟鍵盤輸入含有「我就是人趣諸神」的詞句。`

`Your god is come`

相關任務
[灰機](https://ff14.huijiwiki.com/wiki/%E4%BB%BB%E5%8A%A1:%E6%8B%9C%E6%89%98%E4%BA%86%EF%BC%8C%E4%BA%BA%E8%B6%A3%E8%AF%B8%E7%A5%9E%EF%BC%81)

**Comment by GpointChen** [comment]
已修正。感謝回報。
