### ISSUE TITLE
啟動時跳出JAVA錯誤提示

### ISSUE THREAD

**Issue by M4Jason** [GpointChen/FFXIVChnTextPatch-GP#238]
[https://i.imgur.com/vvldsaV.png](url)
[https://i.imgur.com/qkxv0iV.png](url)

分別跳出上開兩個錯誤提示 有查過環境變量 只有一個JAVA
用CMD查java跟javac運行同樣版本的16.01
但還是跳出錯誤提示 想詢問如何解決

**Comment by GpointChen** [comment]
你有試過 #90 這篇下面的解決方案嗎？

**Comment by M4Jason** [comment]
> 你有#90這個下面的解決方案嗎？

問題已解決 謝謝
