### ISSUE TITLE
任務：博茲雅堡壘蒸發事件 西德追憶戰的部分 沒翻譯到的地方

### ISSUE THREAD

**Issue by qwe3410475** [GpointChen/FFXIVChnTextPatch-GP#24]
![image](https://user-images.githubusercontent.com/46574011/146034191-d890f018-6c73-4784-8355-28211c9ecfd4.png)

博茲雅堡壘蒸發事件 西德記憶的部分

**Comment by qwe3410475** [comment]
![image](https://user-images.githubusercontent.com/46574011/146034526-dde5cf87-e75c-4bd2-a36b-6a03c74a1d89.png)

**Comment by qwe3410475** [comment]
![image](https://user-images.githubusercontent.com/46574011/146036490-3f5c2968-5a00-4655-9b68-2ccc725e9cbb.png)

**Comment by GpointChen** [comment]
這些文本在`GimmickTalk.csv`，麻煩確認一下你的csv是否為中文？

**Comment by GpointChen** [comment]
目前無法確定是哪裡的問題，之後我找時間看有沒有辦法再做一次這個任務好了

**Comment by Kitterato** [comment]
好的 麻煩了。簡繁轉化機翻已經足夠使用。除了一些因為國際服字庫不足的原因導致的缺字外沒有什麼問題。

日文任務文本可能是我以前誤操作導致的，今天還原打了簡體包之後就沒有了。

**Comment by AdiBKDWs** [comment]
今天解到這個任務調查周邊武器跟魔導裝甲幫助回憶以及後面的筆記內容也是原文
https://imgur.com/L9eRdWc.png

**Comment by GpointChen** [comment]
似乎已經找到問題原因，預計於下一版修正。

**Comment by GpointChen** [comment]
已修正於v2.51。
