### ISSUE TITLE
6.28 更新后无法汉化

### ISSUE THREAD

**Issue by Lumiseth** [GpointChen/FFXIVChnTextPatch-GP#240]
更新后重新汉化的时候出现了汉化错误的提示

![hhcw](https://user-images.githubusercontent.com/117214406/199314172-be17b73e-916d-434b-9f78-a642d053ba36.png)
每次汉化到替换文本的时候，到EXD/Item.EXH 都会提示程序错误

**Comment by xlinshan** [comment]
我更新后汉化没出报错，用的是简体CSV汉化英文，10/12的版本

**Comment by Lumiseth** [comment]
我也是简体csv汉化英文，10/12版本，但是就是跳出了我截图的错误，是和4k字体包有关系吗？

**Comment by Lumiseth** [comment]
我还尝试了用国服文本汉化，依然是同样的地方跳出错误提示，EXD/Item.EXH, 还原汉化后重新下载重新安装依然有这个问题

**Comment by xlinshan** [comment]
> 我也是简体csv汉化英文，10/12版本，但是就是跳出了我截图的错误，是和4k字体包有关系吗？

我用的是自制的4k字体包，确实有可能有影响。但是字体包有问题的话，应该会在处理字体文件时就报错，而不是等到处理csv？

也有可能会是原始文件本身有问题。你在更新前有还原文件再更新吗？有试过从别处获取6.28的原始文件来汉化吗？

**Comment by Lumiseth** [comment]
> > 我也是简体csv汉化英文，10/12版本，但是就是跳出了我截图的错误，是和4k字体包有关系吗？
> 
> 我用的是自制的4k字体包，确实有可能有影响。但是字体包有问题的话，应该会在处理字体文件时就报错，而不是等到处理csv？
> 
> 也有可能会是原始文件本身有问题。你在更新前有还原文件再更新吗？有试过从别处获取6.28的原始文件来汉化吗？

我在更新前还原了再更新的，没从别处获取6.28的原始文件来汉化

尝试无汉化打开游戏出现了dx11的错误，我觉得有可能是我的游戏文件出了错误，所以现在在尝试重新安装游戏，然后再试着汉化试试

**Comment by Lumiseth** [comment]
没事了，是游戏文件坏了，所以才无法重新安装汉化。
重装游戏后就可以装了。
