### ISSUE TITLE
幾天后 -> 幾天後

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#242]
https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/cut_scene/053/VoiceMan_05300.csv#L577
`572,"TEXT_VOICEMAN_05300_005270_SYSTEM_NONE_VOICE","幾天后"`

https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/quest/002/SubPst021_00241.csv#L56
`51,"TEXT_SUBPST021_00241_LETTERMOOGLE_000_003","不過，那個人提了個奇怪的要求庫啵……<hex:02100103>他要求不要馬上就送過去，等過幾天后再送庫啵。<hex:02100103>這封信非常可疑，所以這裡就該輪到後輩你出場啦庫啵！"`

https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/quest/019/ClsWdk502_01997.csv#L72
`67,"TEXT_CLSWDK502_01997_BARTHOVIEU_000_033","幾天后，父親的遺體被發現，上面有無數的爪痕。<hex:02100103>據說是被魔物殺死的……<hex:02100103>哼……真是個沒用的男人。"`

**Comment by GpointChen** [comment]
已更新於[v2.71.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.71.0)。
