### ISSUE TITLE
诗人职业量谱的ui汉化有误

### ISSUE THREAD

**Issue by xlinshan** [GpointChen/FFXIVChnTextPatch-GP#243]
![QQ截图20221117003054](https://user-images.githubusercontent.com/4050147/202392546-d4c60f14-ee77-4cf1-8e4f-00cb2da60f04.png)
窗口左上角的文字“职业量谱说明”后跟着的日文”xxxHUD解说“应该是有问题的。我使用的是英文客户端，汉化成简体中文，这里应该是英文原文，或者是汉化后的中文，出现日文应当是出错了。这一部分文本处于GuideTitle.csv中。

**Comment by xlinshan** [comment]
这一部分文本处于GuideTitle.csv中

**Comment by GpointChen** [comment]
已更新於[v2.71.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.71.0)。
