### ISSUE TITLE
幹了>乾了

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#247]
https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/quest/043/AktKmb111_04390.csv#L122
`衣服也差不多幹了。`
換成
`衣服也差不多乾了。`

**Comment by GpointChen** [comment]
已更新於[v2.71.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.71.0)。
