### ISSUE TITLE
其中一段對話沒有正確顯示翻譯

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#248]
疲憊的星戰士 : 辛苦你了。
我看見你帶著人回來了，
他就是和我一起躲藏在墳墓那裡的那個人。
疲憊的星戰士 : 謝謝你幫助了他。
你真是一位既勇敢又勇猛的冒險者啊。
就像是薩維奈傳說中登場的阿迦瑪一樣。
疲憊的星戰士 : 傳說他曾是悌陽象族的一名苦行僧，
就在人族來到這座島引發了戰爭時，
據說是他不分種族拯救了人們。
疲憊的星戰士 : 毫不猶豫地投身於危機之中拯救他人。
你簡直就像是重生於現代的阿迦瑪一樣！
疲憊的星戰士 : どうか、これを受け取って。
私も見張りの交代が終わったら、森の巡回に行ってみるわ。

但是現有檔案中擁有該段文字翻譯
`68,"TEXT_AKTKZF002_04257_SOLDIER04257_000_025","請你收下這個，<hex:02100103>等我值崗結束後，也會去森林那邊巡視一圈的。"`
https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/quest/042/AktKzf002_04257.csv#L73

**Comment by GpointChen** [comment]
這是因為原文文本有改動過順序，導致舊漢化錯位。

已更新於[v2.71.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.71.0)。
