### ISSUE TITLE
[錯別字回報]影隱忍法貼

### ISSUE THREAD

**Issue by SagoAvery** [GpointChen/FFXIVChnTextPatch-GP#249]
您好，
影隱忍法貼的[貼]字應為誤植，應為[帖]字，影隱忍法帖。
謝謝您的無私翻譯。

**Comment by GpointChen** [comment]
已更新於[v2.71.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.71.0)。
