### ISSUE TITLE
南方博兹雅戰線進不去

### ISSUE THREAD

**Issue by chesuta0413** [GpointChen/FFXIVChnTextPatch-GP#25]
![螢幕擷取畫面 2021-12-15 001957](https://user-images.githubusercontent.com/95544385/146037543-52815025-f755-496f-99c5-68e162e5d8c0.png)
跟入口NPC對話後會卡住動不了。

**Comment by ayimayday** [comment]
我高原跟南方都進得去喔~~你再試試

**Comment by chesuta0413** [comment]
我原來是用中國服檔案中文化，使用CSV中文化就可以進入了，謝謝~

**Comment by GpointChen** [comment]
補充說明，因為6.0改版部份指令碼有變，所以用5.5的中國服檔案漢化會出現問題。
