### ISSUE TITLE
」、「符號反轉使用

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#250]
`71,TEXT_AKTKMG103_04452_BLOEWYDA_000_078,而那個裝置則能夠<hex:02100103>在起點和終點之間強制產生超高密度的乙太流。<hex:02100103>這條」一瀉千里之河「是地脈無法比擬的。`
https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/quest/044/AktKmg103_04452.csv#L76

**Comment by GpointChen** [comment]
已更新於[v2.71.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.71.0)。
