### ISSUE TITLE
請問此中文化有機會在Steam deck上使用嗎

### ISSUE THREAD

**Issue by Knox30663** [GpointChen/FFXIVChnTextPatch-GP#252]
如提，不能確定此中文化能不能在Linux系統上的Steam deck做更新QQ

**Comment by WonderWinny** [comment]
我也非常需要！求有機會可以在 Steam deck 上漢化

**Comment by Knox30663** [comment]
目前把0a0000.win32等三個檔案丟進去是可以漢化，但有缺文字OTZ

**Comment by WonderWinny** [comment]
> 

請問你是參考這篇丟的嗎？https://github.com/GpointChen/FFXIVChnTextPatch-GP/discussions/246
我丟了後登入遊戲都沒中文化成功
是我原本在Windows 漢化時原始語言選日文才會導致這樣嗎？

**Comment by Knox30663** [comment]
這個我就不確定了，我目前是使用XIVLauncher的登入器
因為我不知道大大的000000.win32是怎麼生成的
這個版本確實是使用PC轉好，再把檔案弄去Deck覆蓋過去，是有成功，但很多缺字
而且手把之類的設置存檔也找不到.....沒辦法把PC版的移植過去...
目前正在安裝FF14官網的原版
看看能不能突破
另提，GP大的安裝檔，用Steam掛非Steam遊戲，把環境參數改掉可以勉強運行，但會一直閃黑頻，只能說是在硬用
但因為我的不是原廠的FF14  漢化打不上去  要等安裝好才能在測試...

**Comment by WonderWinny** [comment]
> 這個我就不確定了，我目前是使用XIVLauncher的登入器 因為我不知道大大的000000.win32是怎麼生成的 這個版本確實是使用PC轉好，再把檔案弄去Deck覆蓋過去，是有成功，但很多缺字 而且手把之類的設置存檔也找不到.....沒辦法把PC版的移植過去... 目前正在安裝FF14官網的原版 看看能不能突破 另提，GP大的安裝檔，用Steam掛非Steam遊戲，把環境參數改掉可以勉強運行，但會一直閃黑頻，只能說是在硬用 但因為我的不是原廠的FF14 漢化打不上去 要等安裝好才能在測試...

我剛剛嘗試成功了，我把大大的6個檔案透過windows轉好檔的中文化覆蓋到steam deck上去，然後就中文化好了
至於搖桿設置，我先在pc上先上傳，steam 下載下來後就有了

**Comment by Knox30663** [comment]
請問你有缺文字嗎

**Comment by chun1324** [comment]
使用SteamDeck的桌面模式, 由Windows複製下面這些檔案到 /home/deck/.steam/steam/steamapps/common/FINAL FANTASY XIV Online/game/sqpack/ffxiv
其中 .steam為隱藏項目, 按下 Ctrl + H 顯示
(另外: 如果使用第三方啟動器XIVLauncher: ~/.xlcore/ffxiv/game/sqpack/ffxiv)
000000.win32.dat0
000000.win32.index
000000.win32.index2
0a0000.win32.dat0
0a0000.win32.index
0a0000.win32.index2

**Comment by WonderWinny** [comment]
> 請問你有缺文字嗎 並且我說的是有紀錄FF14快捷鍵紀錄的紀錄檔QQ

1.你是說遊戲內的一些文字顯示不出來嗎？我目前在 Steam deck 上玩到現在沒有看到特別異常的文字耶，我個人主線只玩到6.0大約一半而已，今天晚上玩了約5個小時(在steam deck 上)把每日任務搜尋器都打完，沒有看到特別異狀出現，不知道你是指哪一個部分會缺字，我會再去幫你看看。順便提一下，我從電腦版轉出來的檔案原始語言是英文的(因為一開始steam deck 我選了英文)，我剛剛把steam deck 的版本轉成日文，我以為電腦版要在轉一份日文的檔案出來，結果steam deck的日文版自己就中文化好了 @@

2.你是說熱鍵 Hotbar 的按鈕嗎？我在電腦版上傳了自己的設定紀錄，然後steam deck下載回來，我的鍵盤模式該有的快捷列上的技能都有(跟電腦版的鍵盤模式介面一樣)，Macro的功能也都正常運作，不過因為我平常電腦不用手把玩，所以沒有測試手把的快捷列是否有一樣，搞不好像你說的一樣真的沒辦法上傳手把的紀錄。我現在被限制上傳紀錄，明天會再幫你測試看看。

**Comment by Knox30663** [comment]
> 

請問你是怎麼做到的，電腦上傳自己的設定記錄在下載下來
我以前的做法都是My Games\FINAL FANTASY XIV - A Realm Reborn把這裡的資料夾copy走
但Deck的部分我不知道它放在哪裡所以無從下手...

**Comment by WonderWinny** [comment]
> 

我是裝在本機

**Comment by Knox30663** [comment]
> > 
> 
> 我是裝在本機，我參考這個影片安裝的 https://www.youtube.com/watch?v=7ROdDu8EnMw

感謝  目前都搞定了
只差在遊戲外接鍵盤不能打中文比較麻煩ORZ

**Comment by sif941025** [comment]
因為我手邊沒有windows的裝置可以用
所以我直接把6個漢化檔案（他附的）直接覆蓋到/.xlcore/ffxiv/game/sqpack/ffxiv
直接覆蓋6個檔案就可以用了
除了大廳的一些字會變成=以外
目前遊戲裡沒遇到什麼問題
不需要特地用windows電腦載遊戲再漢化複製檔案（但是高畫質包好像沒辦法

000000.win32.dat0
000000.win32.index
000000.win32.index2
0a0000.win32.dat0
0a0000.win32.index
0a0000.win32.index2

**Comment by akasakakona** [comment]
直接覆蓋漢化檔案後遊戲在標題畫面報錯
請問有什麼解決方法嗎？
感謝！

![image](https://github.com/user-attachments/assets/7909bfa3-0129-4096-aab2-f486c0c06711)

**Comment by chun1324** [comment]
> 直接覆蓋漢化檔案後遊戲在標題畫面報錯
> 請問有什麼解決方法嗎？
> 感謝！
> 
> ![image](https://github.com/user-attachments/assets/7909bfa3-0129-4096-aab2-f486c0c06711)

你有把遊戲介面設定成4K嗎

**Comment by akasakakona** [comment]
> > 直接覆蓋漢化檔案後遊戲在標題畫面報錯
> > 請問有什麼解決方法嗎？
> > 感謝！
> > 
> > ![image](https://github.com/user-attachments/assets/7909bfa3-0129-4096-aab2-f486c0c06711)
> 
> 你有把遊戲介面設定成4K嗎

抱歉⋯⋯ 問了一個很傻的問題⋯⋯
設定成4K後問題解決了⋯⋯
