### ISSUE TITLE
6.2任務NPC名字沒有中文化

### ISSUE THREAD

**Issue by itsbosco1025** [GpointChen/FFXIVChnTextPatch-GP#256]
如題

**Comment by chun1324** [comment]
補充
主線6.2任務名: 追尋阿珠達雅的蹤跡
角色名稱沒有翻譯, 但對話內容有. 參考圖片如下
![image](https://user-images.githubusercontent.com/15475075/210103817-519f7bb0-d47d-4bc9-921f-1234931e0d5f.png)
![image](https://user-images.githubusercontent.com/15475075/210103833-999fcbed-199f-4136-ac65-048f1e7e3941.png)

**Comment by chun1324** [comment]
參考對話紀錄 (注意內含劇透內容)
`エスティニアン : 這就是人造妖異……
沒想到連妖異都能製作出來，
真不愧是拉札罕的煉金術士。
ヴァルシャン : 我也叫加隆德煉鐵廠的人來遺烈鄉了。
看來他們還沒到呢。
エスティニアン : 這就是人造妖異……
沒想到連妖異都能製作出來，
真不愧是拉札罕的煉金術士。
ヤ・シュトラ : 等你好久了，<<玩家名>>。
ヤ・シュトラ : 快來看看這個，
這就是煉金術士們努力的成果——人造阿托莫斯。
ヤ・シュトラ : 雖然目前還沒有進行過實際測試，
不過從乙太看來，
它的完成度已經無限接近真正的阿托莫斯了。
ヴァルシャン : 能在如此短時間內做出這樣的成果，
作為拉札罕的一份子，我感到十分驕傲。
ヴァルシャン : 我想直接向尼答娜道謝，
但她好像不在這裡……
ヤ・シュトラ : 嗯，她好像還有別的工作，
把人造阿托莫斯交給我們之後就趕回去了。
ヤ・シュトラ : 我已經迫不及待地想見到加隆德煉鐵廠的使者了。
只要拿到改良後的靈鱗，
我們就能立刻嘗試擴大虛無界之門了。
西德 : 這可是個好消息。
看來我提前結束工作過來是對的。
ヤ・シュトラ : 哎呀，這話音剛落……
很高興能再見到你們。
ヤ・シュトラ : 沒想到會長會親自過來交貨，
看來您對這次的計劃相當感興趣啊？
西德 : 嗯，畢竟打開希爾科斯塔的虛無界之門時也費了不少精力嘛。
這回我想親眼看看你們的嘗試結果如何。
西德 : 方便的話，能讓我們的人一起見證嗎？
畢竟這麼快完工都是他們的功勞。
尼祿 : 哼……他們能改良護魂靈鱗，
可多虧了本大爺親自收集到的寶貴數據。
尼祿 : 我敢保證，即便是帶到陰氣沉沉的虛無界，
過個5年10年也不會出問題。
不過，要是打算在那邊定居就另當別論了。
比格斯 : 我們兩個實際動手參與改良的人
也可以保證品質絕對不會出問題。
魏吉 : 請收下，這就是改良後的成品！
ヴァルシャン : 謝謝你們……
這樣我就可以放心地去尋找姐姐了。
西德 : 好！就讓我們加隆德煉鐵廠見證虛無界之門的擴張，
然後目送你們前往虛無界吧！
尼答娜 : 等一下！
ヴァルシャン : 尼答娜……有什麼事嗎？
尼答娜 : 其實我有一樣東西不論如何都想交給您。
尼答娜 : 很抱歉在臨行前打亂了您的行程，
您能和我來一趟嗎？
ヴァルシャン : 嗯……
你現在來找我，想必也是有原因的。
ヴァルシャン : 抱歉各位，能請你們在這裡稍等片刻嗎？
尼祿 : 怎麼這麼慢啊，到底是什麼東西要花這麼長時間？
西德 : 畢竟要去的是虛無界，
不管怎麼說，多做些準備總是沒錯的。
西德 : 你應該比任何人都清楚那裡有多危險吧？
？？？？ : 抱歉，讓你們久等了。
埃斯蒂尼安 : 你是……弗栗多？
瓦爾桑 : 是的。
我將龍眼從那個少年身體內取了出來，
放到了這個新身體裡。
瓦爾桑 : 我之前還奇怪你們這陣子是在忙什麼，
沒想到是在為我準備這個……
尼答娜 : 我們的總督大人可是要親自上陣，
當然要以最完美的狀態出發啦！
尼答娜 : 這可是我們煉金術士竭盡全力製作出來的人偶，
各方面都做了最適合戰鬥的調整。
用這個新的身體，能夠更流暢地使用武器和魔法！
尼答娜 : 本來我們想要快點調整好的，
不過越做越想要再多改良一些……
真是對不起，最後還是很晚才交給您。
瓦爾桑 : 你無需道歉，
反而是我應該向你們表示感謝。
讓你們操心了，我會好好使用這副身體。
瓦爾桑 : 這邊的防衛就交給你們了，如果在那邊遭遇戰鬥，
我必定會將大部分意識都集中在這個身體上，
可能無法兼顧兩邊的情況。
瓦爾桑 : 虛無界之門一旦開放，
可能會有妖異入侵到這一側，
必須時刻保持警戒。
納卜狄恩 : 不必擔心這一點，我們已經做好了萬全的準備。
納卜狄恩 : 我們都接受了龍騎士閣下的嚴格訓練，
是時候展現最終成果了。
星戰士團絕不會放過任何一隻妖異！
納卜狄恩 : 所以你就放心吧，瓦爾桑！
納卜狄恩 : 啊，等等，你現在又換了個身體，
我們需要換一個稱呼方式嗎？
瓦爾桑 : 繼續叫我瓦爾桑就可以了，
就當是弟弟長大成人了吧。
納卜狄恩 : 沒問題！
那就祝你一路順風吧，瓦爾桑！路上小心！
雅·修特拉 : 耽誤你一點時間，我也有東西想給你。
雅·修特拉 : 你不在的時候，於里昂熱過來了一趟。
雅·修特拉 : 你還記得上次去寶物殿探險吧，
他當時為了幫兔兔族調查，也和我們一起去了。
雅·修特拉 : 兔兔族聽了他的報告之後都特別開心，
好像已經開始積極探討月球寶物殿的改良方案了。
雅·修特拉 : 雖然可能算不上是回禮吧，
但是生命威還是給了他一個東西。
雅·修特拉 : 沒錯，這正是海德林在星海託付給你的——
記錄了梅蒂恩行動軌跡的水晶。
雅·修特拉 : 兔兔族已經分析出了天外天垓的位置，
他們也就不再需要這塊水晶了，
於是把它交給了於里昂熱。
雅·修特拉 : 這個水晶中寄宿著強大的光之力，
所以於里昂熱認為還是交給你比較好。
說不定能在暗之世界的探索中發揮作用。
雅·修特拉 : 收下吧，它凝聚了海德林的思念，理應由你保管。
瓦爾桑 : 一切都已準備就緒。
我們出發吧，船已經在白濱村等著了。`

**Comment by GpointChen** [comment]
此串有提及的NPC已修正，如仍有問題可再回報。
