### ISSUE TITLE
漢化後 ACT - Cactbot 用不了

### ISSUE THREAD

**Issue by Kennyvicbour** [GpointChen/FFXIVChnTextPatch-GP#257]
是不是因為王的出招漢化了繁體, 而CACTBOT 文件只有簡體字 , 所以用不了?

**Comment by GpointChen** [comment]
應該是這樣。

**Comment by chun1324** [comment]
如果你會自行build的話可以下載cactbot原代碼, 將裡面所有簡體轉成繁體, 可以同時也下載這邊中文包對比, 修正一些簡體差異再build即可.

如果不行的話也可以將遊戲切換成英語, ffxiv act plugin 也切換成英語運行.

**Comment by GpointChen** [comment]
這個部分不屬於BUG，關閉此串。
