### ISSUE TITLE
定型文無法選巴爾巴莉希婭殲滅戰

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#258]
![image](https://user-images.githubusercontent.com/15475075/210164705-7175ec87-34dc-46ad-a0f7-e4b20dc961a9.png)
如題

**Comment by chun1324** [comment]
![image](https://user-images.githubusercontent.com/15475075/210165124-b8e8f822-1a0a-41dd-a079-40e4e6b02849.png)
實祭上也未轉換成中文

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

**Comment by GpointChen** [comment]
應已於[v2.72.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.0)修正。

如有問題可繼續回報。

**Comment by chun1324** [comment]
![image](https://user-images.githubusercontent.com/15475075/215021149-104aa7ef-567a-403b-b793-3035e959d0cf.png)
6.31 [v3.0.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/tree/v3.0.0) 版依然未能選取中文定型文

**Comment by GpointChen** [comment]
修正於[v3.0.1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v3.0.1)。
