### ISSUE TITLE
1216 patch 打新極本問題

### ISSUE THREAD

**Issue by 3-season** [GpointChen/FFXIVChnTextPatch-GP#26]
剛用到來打極武器本, 發現左右刀技能名(即名字比較長的那一個)前面的字會消失
令我以為是左右刀…細看下才會發現。ＸＸＸＸＸＸ的那個點是前後刀的最重要提示，因前面日文字都消失了

（隨機出現，有時候又會正常）

**Comment by GpointChen** [comment]
找到了，`Action.csv`裡面有幾個字沒有刪乾淨。預計下版修正。

感謝回報。

**Comment by GpointChen** [comment]
[Fixed.](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.43)
