### ISSUE TITLE
一部分道具的道具说明用日文替换了原文

### ISSUE THREAD

**Issue by xlinshan** [GpointChen/FFXIVChnTextPatch-GP#261]
我使用的是英文客户端。星芒节的驯鹿坐骑的号角的道具说明被替换成了日文，但是使用道具后在坐骑页面的坐骑信息是原文的英文。另外，6.3更新前这一季的稀少神典石也是如此，道具信息被替换成了日文。除了这两个被发现的道具外，也有其它道具有类似情况的可能。
![image](https://user-images.githubusercontent.com/4050147/210511115-0063eed3-b724-4c18-99c1-1f1d94526331.png)
![image](https://user-images.githubusercontent.com/4050147/210511187-f5f0b11d-1371-4e4c-a770-3eeb2270800b.png)
两张图分别为一个被日文替换了原文的道具的道具说明，以及一个未汉化保留了原文的道具说明。

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

**Comment by GpointChen** [comment]
應已於[v2.72.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.0)修正。

如有問題可繼續回報。
