### ISSUE TITLE
部份無人島對白未有翻譯

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#262]
耕種小員 : やぁ！　ねこみみさんから話は聞いているよ。
耕作地の開墾を始めてもいいかな？
耕種小員 : 耕作地の開墾を始めるね！

耕種小員 : 耕作地が完成したね！
この耕作地に植えられる種を、特別にプレゼントするよ！
種を植えて水をあげると育てることができるから、試してみてね。
耕種小員 : 耕作地のことで何か困ったら、ぼくに声をかけてね！
「種まきモード」が開放されました！
開拓管理ボードより「種まきモード」に切り替えることで、
作物が植えられていない畝に種をまくことができます。
「水やりモード」が開放されました！
開拓管理ボードより、水やりモードに切り替えることで、
耕作地に植えた種に水をやることが出来ます。

耕種小員 : 作物のお世話、お疲れさま！
まず基本的なお世話をしてもらったけど、どうだったかな？
新しい種が手に入ったら、耕作地にまいて育ててみてね！
作物は水やりをすることで、時間をかけて成長していきます。
水を与えないと、作物の成長は止まってしまいます。
なお降雨中は、自動的に水をあげた状態となります。
成長した作物は、「収穫モード」で収穫したり、
不要であれば「鋤き返しモード」で処分することも可能です。

![image](https://user-images.githubusercontent.com/15475075/211047999-0b9ef56e-03b2-4fd8-9514-5b1a59984254.png)

耕種小員 : 「栽培委託」についてだね！
栽培委託は、ぼくらが君の代わりに、
耕作地のお世話をさせてもらうことだよ。
耕種小員 : ただ、今はまだぼくらの仲間が足りなくて、
すぐにお手伝いが始められないんだ。
耕作地が大きくなって仲間が増えたら、また聞いてみてね！

耕種小員 : この耕作地では、種を植えて作物を育てることができるよ。
育った作物は、料理や動物たちの餌なんかに使えるんだ！

**Comment by GpointChen** [comment]
應已於[v2.72.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.0)修正。

如有問題可繼續回報。
