### ISSUE TITLE
替換 lobby.csv 內容後沒有變化

### ISSUE THREAD

**Issue by peckcat** [GpointChen/FFXIVChnTextPatch-GP#263]
試著將 lobby.csv 換成中文的內容
也將 conf/global.properties  內的 "exd/Lobby" 給取消
但大廳文字還是維持日文

**Comment by GpointChen** [comment]
![image](https://user-images.githubusercontent.com/34565875/211699423-558f88db-5cc7-437a-a60a-f798a56bf850.png)

我是可以替換成中文內容的（圖中出現＝為大廳字體缺字的正常現象），或者你可以說一下你的操作過程？

**Comment by peckcat** [comment]
更改的檔案與設定
`FFXIVChnTextPatch-20230111-v2\conf\global.properties`
檔案內這項改為 `SkipFiles=exd/Quest|exd/CompleteJournal|exd/WebURL`

Lobby.csv 替換的路徑
`FFXIVChnTextPatch-20230111-v2\resource\rawexd\Lobby.csv`
我替換的檔案
[Lobby.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/10390840/Lobby.csv)

程式的設定(不含路徑)
![image](https://user-images.githubusercontent.com/7374380/211771618-337548d8-bc21-4f3c-ae63-4ee2767bd05f.png)

這樣的話應該是我替換的 Lobby.csv 的格式錯誤?

**Comment by GpointChen** [comment]
也許

你可以先試試看這個檔案，我還沒有檢查完每一條文本，但使用上可以替換成功。（當然字體要另外處理）

[Lobby.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/10391601/Lobby.csv)

另外理論上不用修改global.properties，目前該檔案只對非csv模式生效。

**Comment by peckcat** [comment]
改用提供的檔案，有成功替換了，
看來應該就是我的 csv 裡有格式錯誤，
感謝。

另外想問有沒有辦法增加一個可勾選的選項，
可以不對字型進行替換？

這樣有另外自備字體的人就可以避免重複替換字型。
不過可能要預設進行替換，以免新手沒有可用字型。

如果太麻煩就可以不用家沒關係，
畢竟自己另外覆蓋也不會太麻煩。

**Comment by GpointChen** [comment]
不錯的想法，已加。
