### ISSUE TITLE
Ctrl + U的Timers報錯

### ISSUE THREAD

**Issue by WaiHong7327** [GpointChen/FFXIVChnTextPatch-GP#264]
![222](https://user-images.githubusercontent.com/18750225/211552424-af24b3d7-08c2-48e1-8c15-7841800f5f24.png)
![image](https://user-images.githubusercontent.com/18750225/211553008-8fe3b357-6b87-46be-9f89-6db2e151c1cb.png)
似乎是加載The Masked Carnivale的時間導致?

**Comment by GpointChen** [comment]
國際服更新至6.3後部分指令碼改動所致，應已於[v2.72.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.0)修正。

如仍有問題可繼續回報。
