### ISSUE TITLE
传送游末邦时会报错

### ISSUE THREAD

**Issue by FengJiQ** [GpointChen/FFXIVChnTextPatch-GP#265]
传送游末邦时会报错，导致游戏一直进不去，需要先恢复，在传送到其他地图，再行汉化，目前暂未发现其他地图报错。
![~GCBS(E) ~$UL% @G2P8NHT](https://user-images.githubusercontent.com/57966526/211563837-6d322ac0-850d-4189-801f-002e7a798b33.png)

**Comment by Zhong0514** [comment]
我也遇到同樣問題 我是在傳送到烏爾達哈停機坪那裏的時候
![image](https://user-images.githubusercontent.com/121940592/211591198-9f4f2e80-0312-47f4-a834-220d23a65cab.png)

**Comment by GpointChen** [comment]
國際服更新至6.3後部分指令碼改動所致，應已於[v2.72.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.0)修正。

如有問題可繼續回報。
