### ISSUE TITLE
漢化後遊戲錯誤問題

### ISSUE THREAD

**Issue by Ghostbear102910** [GpointChen/FFXIVChnTextPatch-GP#266]
您好，我在安裝漢化包後遊戲進行沒多久便出現以下錯誤，目前已經刪除遊戲再重新安裝多次，並且出現在typhon的角色會出現錯誤，但Atomos的角色可正常遊玩的情況

![9F583ABE-D0FA-4EB6-9540-DEEEA7737A7B](https://user-images.githubusercontent.com/122384572/211603309-f0124064-456a-48a4-bccc-133a029ea7ca.jpeg)

因為對程式上面不太熟悉，故上來詢問，
謝謝您！

**Comment by cs5886147** [comment]
Atomos的漢化能用?還是原文才能用?我目前用也出現這問題，可能要等官方更新到6.3的樣子

**Comment by Ghostbear102910** [comment]
> Atomos的漢化能用?還是原文才能用?我目前用也出現這問題，可能要等官方更新到6.3的樣子

Atomos的漢化過後也是可以用的！

**Comment by cs5886147** [comment]
> > Atomos的漢化能用？還是原文才能用？我之前用的也出現這個問題，可能要等官方更新到6.3的樣子
> 
> Atomos的漢化過後也是可以用的！

那可能是我在更新過程沒用好，目前在重新下載試看看，感謝解惑

**Comment by GpointChen** [comment]
國際服更新至6.3後部分指令碼改動所致，應已於[v2.72.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.0)修正。

如有問題可繼續回報。
