### ISSUE TITLE
6.3 主線報錯

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#267]
![image](https://user-images.githubusercontent.com/15475075/211614809-cb6ec212-86e8-42f9-a7c8-99d4a4cd8ff5.png)
任務: 気配の正体
每當接近上圖一帶空間時即會出現以下錯誤
![image](https://user-images.githubusercontent.com/15475075/211614835-10d8511f-c0b4-4251-ab76-be8a04dd27ec.png)

使用英語啟動則可遇見以下NPC
![image](https://user-images.githubusercontent.com/15475075/211616253-ad095b75-5248-4571-9262-d2e9c4983994.png)

**Comment by GpointChen** [comment]
國際服更新至6.3後部分指令碼改動所致，應已於[v2.72.0](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.0)修正。

如有問題可繼續回報。
