### ISSUE TITLE
6.3版本吟游诗人技能描述未变更

### ISSUE THREAD

**Issue by zjq9714** [GpointChen/FFXIVChnTextPatch-GP#269]
大地神的抒情恋歌 
依然描述为“令自身或其他一名队员所受的体力恢复效果提高20%”
6.3版本应为“令自身与周围队员所受的体力恢复效果提高15%”

**Comment by GpointChen** [comment]
已修正於[v2.72.1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.1)。

**Comment by zjq9714** [comment]
> 已修正於[v2.72.1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.1)。

该版本只将20%变更为15%，并没有修正单体和群体的描述。

**Comment by GpointChen** [comment]
沒注意看，一併於下次更新時修正。
