### ISSUE TITLE
任務日誌>職業及特職任務

### ISSUE THREAD

**Issue by lewisyuk** [GpointChen/FFXIVChnTextPatch-GP#27]
為什麼中庸工藝館任務下面是寫著園藝理符?

**Comment by GpointChen** [comment]
有截圖嗎？方便我確認是哪裡的文本

**Comment by lewisyuk** [comment]
馬上到
![error](https://user-images.githubusercontent.com/96244250/146385072-7b4f2a45-1d89-4d0e-91d9-4c6f2e416902.png)

**Comment by awaww333** [comment]
同12/16 我正常啊
![image](https://user-images.githubusercontent.com/74402698/146388181-507d5ebf-683d-48f7-8a34-5365c5e56edc.png)

**Comment by GpointChen** [comment]
![ffxiv_12162021_220544_631](https://user-images.githubusercontent.com/34565875/146387179-cc5938d3-df25-4f53-9288-fa3779195824.png)

這裡的文本在`JournalCategory.csv`，改版後文本和編號有更動過，你可以確認一下是否用的是最新版

**Comment by lewisyuk** [comment]
我應該是最新版的, 會因為主線還未解完5.0嗎?

**Comment by GpointChen** [comment]
> 我應該是最新版的, 會因為主線還未解完5.0嗎?

這我就不確定了，但通常不是這個原因。

5.58日文文本
```
69,"リーヴ：園芸師",3,2,8,0
```
6.0日文文本
```
69,"クラスクエスト：魔法大学取引",2,1,6,0
```
又或者是你在漢化前沒有先還原成乾淨的版本？

**Comment by lewisyuk** [comment]
我相信是這個原因了, 現在還有辦法可以還原乾淨版本嗎?  我忘了backup

**Comment by GpointChen** [comment]
> 我相信是這個原因了, 現在還有辦法可以還原乾淨版本嗎? 我忘了backup

你可以用之前的release中有一個600 ja的檔案，那是純淨日文版導出的csv，用那個漢化一次，等同還原。
