### ISSUE TITLE
6.3海島上和貿易小員對話有bug

### ISSUE THREAD

**Issue by zue37511** [GpointChen/FFXIVChnTextPatch-GP#270]
選第一個 交換報酬(謝爾達萊青船幣) 之後跳出來的視窗是空白的
原文中有幾類物品可以選擇( 特殊物品 衣服外觀  染料雜項)

**Comment by GpointChen** [comment]
我還沒開無人島XD

你可以截個正常情況下的圖方便我debug嗎？

**Comment by zue37511** [comment]
![zh1](https://user-images.githubusercontent.com/122430257/211744558-ccfd4db0-1541-42c8-88a2-2e52b38efde3.jpg)
![zh2](https://user-images.githubusercontent.com/122430257/211744567-6448326f-9ac5-4745-a0f2-78475be44f90.jpg)
還原成英文的話是
![en1](https://user-images.githubusercontent.com/122430257/211744625-91c28672-b587-4fdf-b363-59209410398d.jpg)
![en2](https://user-images.githubusercontent.com/122430257/211744638-21e1dd94-700e-4365-b806-186c7e55fcba.jpg)

**Comment by GpointChen** [comment]
已修正於[v2.72.1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.1)。

感謝回報。
