### ISSUE TITLE
PLD 騎士技能說明尚未更新

### ISSUE THREAD

**Issue by peckcat** [GpointChen/FFXIVChnTextPatch-GP#272]
僅先列出部分，晚點會慢慢補上，如果不用協助列出可以再跟我說

**ActionTransient.csv**

20 戰逃反應
-目前: 一定時間內，自身發動物理攻擊造成的傷害提高25%
-更新: 一定時間內，自身發動攻擊造成的傷害提高25%
-註: 現在不論是魔法/物理都會有增傷了

15 暴亂劍
-目前: 威力：170，連擊威力：300，恢復自身魔力
-更新: 威力：120，連擊威力：280，恢復自身魔力
-註: 

3545 盾陣
-目前: 一定時間內，受到攻擊必定發動格擋
-更新: 一定時間內，將自身所受到的傷害減輕 15 %
-註: 

### Status.csv

76 戰逃反應
-目前: 物理攻擊所造成的傷害提高
-更新: 攻擊所造成的傷害提高
-註: 現在不論是魔法/物理都會有增傷了

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

**Comment by GpointChen** [comment]
修正於[v2.72.2](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.72.2)。
