### ISSUE TITLE
[錯誤回報] 這次的漢化FFXIVChnTextPatch-1222.rar，人物到伊修加德就會當機

### ISSUE THREAD

**Issue by SagoAvery** [GpointChen/FFXIVChnTextPatch-GP#275]
您好，這次的漢化FFXIVChnTextPatch-1222.rar，人物到伊修加德就會當機，並出現下列錯誤，供參考XD 謝謝您。
![2023-01-11_231208](https://user-images.githubusercontent.com/120916091/211843797-0370b3d5-da18-42a7-a2c4-b379f1014935.png)

**Comment by GpointChen** [comment]
1222是6.28的漢化，請使用最新的版本。

**Comment by SagoAvery** [comment]
好的。剛剛才發現今天有新版本，謝謝您。
