### ISSUE TITLE
Data Center 名字無法顯示

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#276]
![image](https://user-images.githubusercontent.com/15475075/211879187-7a3b0a79-abf4-4c09-99ff-bc2133c8cbc5.png)
Data Center 名字變成 - - - - -

**Comment by GpointChen** [comment]
因為原始字體包中大廳字體沒有非日文漢字，如果想要正常顯示需下載高畫質字體包。

或者你可以刪除resource/rawexd中的Lobby.csv再進行漢化，這樣會顯示原文。

**Comment by chun1324** [comment]
> 因為原始字體包中大廳字體沒有非日文漢字，如果想要正常顯示需下載高畫質字體包。
> 
> 
> 
> 或者你可以刪除resource/rawexd中的Lobby.csv再進行漢化，這樣會顯示原文。

保持現狀就好, 沒問題
