### ISSUE TITLE
csv如何安裝簡體中文？

### ISSUE THREAD

**Issue by Kitterato** [GpointChen/FFXIVChnTextPatch-GP#28]
嘗試過將csv補丁打好的0000文件
複製後放入text裡
使用  使用別人已經漢化過的（0a0000等）檔案進行漢化  的方法
選擇簡體中文 但是軟件會報錯
有什麼方法麼？

**Comment by Kitterato** [comment]
考慮過這個方法，但是5000+在沒有批處理工具的情況下並不是很好做到。

**Comment by Kitterato** [comment]
同時發現選擇目標為英文時，會有很多對話和任務文本變成日文的情況，是哪裡操作錯誤了麼？

**Comment by GpointChen** [comment]
> 考慮過這個方法，但是5000+在沒有批處理工具的情況下並不是很好做到。

機翻了一個，你可以湊合用看看。
https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.43

**Comment by GpointChen** [comment]
> 同時發現選擇目標為英文時，會有很多對話和任務文本變成日文的情況，是哪裡操作錯誤了麼？

可能是我起初有些未翻譯的文本沒有刪乾淨，你可以說是哪些任務出現原文或者直接截圖，方便我排查。
