### ISSUE TITLE
mac m1 使用 pd18虚拟机 arm win11使用汉化报错

### ISSUE THREAD

**Issue by Caikishi** [GpointChen/FFXIVChnTextPatch-GP#280]
mac m1 使用 pd18虚拟机安装arm win11使用汉化报错
版本是 20230111

**Comment by GpointChen** [comment]
是在哪個階段報錯？可以貼一下log嗎？

**Comment by Caikishi** [comment]
> 是在哪個階段報錯？可以貼一下log嗎？

不好意思，应该是pd18的问题，我把所有有关文件，应用共享关闭后就可以汉化，之前是出现在点击汉化时会弹出一个错误框。错误信息我忘记是什么了
