### ISSUE TITLE
大厅的订阅等级文本被替换成了日文

### ISSUE THREAD

**Issue by xlinshan** [GpointChen/FFXIVChnTextPatch-GP#281]
![Z0 5VE$O6{RH~YEOAOSYP%L](https://user-images.githubusercontent.com/4050147/212480040-60dd9055-1816-4e6b-9395-c4128a37a6f9.png)
英文客户端，汉化后，这一部分文本被替换成了日文。

**Comment by GpointChen** [comment]
感謝回報，預計下次更新修正。

**Comment by GpointChen** [comment]
修正於[v3.0.1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v3.0.1)。
