### ISSUE TITLE
6.31 購買房屋時出現空白對話框

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#286]
當遞交現金投標房屋時, 有一段對話變成空白. 下面是紀錄

[23:03]參與了XXX 第XX區 XX號的抽選。
申請號碼為X號。
結果可於2023/1/29 23:00之後進行確認。
[23:03]                      (此處空白)

**Comment by GpointChen** [comment]
了解，感謝回報，預計下次更新修正。

**Comment by GpointChen** [comment]
修正於[v3.0.1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v3.0.1)。
