### ISSUE TITLE
為藏寶圖名稱加上數字

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#287]
根據早前的討論, 請為藏寶圖名稱補上代號方便辨別

參考
https://github.com/GpointChen/FFXIVChnTextPatch-GP/issues/6

例子
陳舊的綠飄龍革地圖（G11）
陳舊的纏尾蛟革地圖（G12）

G13 地圖
陳舊的賽加羚羊革地圖
G14 地圖
陳舊的金毗羅鱷革地圖

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時加上。

**Comment by GpointChen** [comment]
添加於[v3.0.1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v3.0.1)。
