### ISSUE TITLE
漢化出現程式錯誤提示框

### ISSUE THREAD

**Issue by ueuuop8591** [GpointChen/FFXIVChnTextPatch-GP#29]
請問如果在漢化時跳出漢化錯誤的提示框(在用新版漢化時，已經有先還原)，有error log可以看嗎?

**Comment by GpointChen** [comment]
目前沒有，如果有需要之後會實作

**Comment by GpointChen** [comment]
實現於[v2.50](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.50)。
