### ISSUE TITLE
阿梅莉安丝(老主顧)，進行第一次繳交收藏品對話時對話會於中途停止內容，無法繼續。

### ISSUE THREAD

**Issue by MODIKARO** [GpointChen/FFXIVChnTextPatch-GP#298]
阿梅莉安丝(老主顧)，進行第一次繳交收藏品對話時對話會於中途停止內容，無法繼續。
![ffxiv_02252023_152406_615](https://user-images.githubusercontent.com/109712520/221345141-bf689425-b26a-46cf-8f06-2c2f4baeae5e.png)

**Comment by GpointChen** [comment]
用[最新版本](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v3.0.2.0)測試沒有出現這個問題了。

如果使用新版本後仍有類似問題可以再於此處回報。
