### ISSUE TITLE
24 人本內的人數說明錯誤

### ISSUE THREAD

**Issue by iveslazycat** [GpointChen/FFXIVChnTextPatch-GP#3]
https://imgur.com/a/uzZtLrz
紅框內的人數錯誤。
目前看起來 24 人本都是同樣的錯誤。

應該是在 addon.csv 裡，
編號 102585 位置的參數設置問題。

另外想問有辦法增加拆包功能嗎？
輸出的 csv 格式好像跟其他的不太一樣，
這樣可以拆日文˙包來對照文本，
應該會比較好比較。

**Comment by GpointChen** [comment]
感謝回報，已經修正於[新的release](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.12)。

另外，日文原文的csv同樣附於該release中，有需要可額外下載。

關於拆包功能，我是修改另一個開源程式SaintCoinach的程式碼中文字處理的部分（`text`資料夾下的程式碼）來產出CSV，目前沒有將C#移植到Java的打算。如果你有興趣，可以參考readme中我寫的[這篇筆記](https://hackmd.io/@GpointChen/SJi_gv-ad)的相關章節，有大概說明我的修改過程。

**Comment by iveslazycat** [comment]
好的，沒有注意到 release 裡有日文文本。
非常感謝如此用心的維護及更新。
