### ISSUE TITLE
6.25 新增的的特殊迷宮探索漢化沒有同步

### ISSUE THREAD

**Issue by Bos-hunting** [GpointChen/FFXIVChnTextPatch-GP#306]
![image](https://user-images.githubusercontent.com/95756995/224002271-81332d85-6ebc-42c5-a48f-e12fcae3349a.png)
 6.25新增的下水道，圖中應該是漢化才是正設，因為關卡名稱和內容都有漢化唯獨選單的這個位置沒有漢化

**Comment by Bos-hunting** [comment]
![image](https://user-images.githubusercontent.com/95756995/224003204-f05ec827-433c-4a25-af52-6586ef3810b7.png)
下水道兌換的這個表情也沒有漢化

**Comment by GpointChen** [comment]
忘記改了，預計下次更新時補上。

**Comment by GpointChen** [comment]
已修正於新的release。
