### ISSUE TITLE
mac系統  執行漢化過程中遇到這個報錯

### ISSUE THREAD

**Issue by trulynb** [GpointChen/FFXIVChnTextPatch-GP#309]
<img width="833" alt="Xnip2023-04-04_19-33-50" src="https://user-images.githubusercontent.com/17597573/229779481-e96b45b8-06c4-48a3-b5d3-0b0dafbd31b7.png">
不知道該怎麼解決了

**Comment by trulynb** [comment]
到這一步  
<img width="336" alt="Xnip2023-04-04_19-36-44" src="https://user-images.githubusercontent.com/17597573/229779645-3e1b44bf-c3ac-415b-8b89-c373d6e1cb3a.png">

**Comment by trulynb** [comment]
解决了  虽然不知道自己做了什么

**Comment by mslauky** [comment]
> 解决了 虽然不知道自己做了什么

請問怎樣解決的? 我卡在font6

**Comment by trulynb** [comment]
> 

做了很多事  不确定哪件事是解决办法——环境命令重新敲了、gradle重新启用了、多次重试执行汉化程序
