### ISSUE TITLE
一直顯示請選擇正確的根目錄

### ISSUE THREAD

**Issue by ALamQwQ** [GpointChen/FFXIVChnTextPatch-GP#311]
我選擇了正確的路徑之後他仍然顯示請選擇正確的根目錄

**Comment by EugneZhou** [comment]
大概率是sb onedrive的问题

**Comment by TCXIII** [comment]
Got the same problem

**Comment by GpointChen** [comment]
選擇的路徑長怎樣，是全英文嗎？

**Comment by babyilula** [comment]
> 選擇的路徑長怎樣，是全英文嗎？

對是全英文的我的是 C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by GpointChen** [comment]
那遊戲資料夾路徑內找得到ffxiv.exe嗎？

應該要位於`SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxiv.exe`

**Comment by LordofDiabetes** [comment]
遇到一模一樣的問題，路徑也是 C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by wwingYu** [comment]
請問一下使用 XIV on Mac 的話路徑應該是甚麼？因為 `/Users/使用者帳號/Library/Application Support/XIV on Mac/` 下沒有 ffxiv

**Comment by hydai** [comment]
Hi @wwingYu 請確認一下 `XIV on Mac` 資料夾的內容，我的資料內容如下：

![CleanShot 2023-05-27 at 19 11 47](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/2776756/151f063f-15b2-4eb7-b236-970465d98760)

**Comment by wwingYu** [comment]
> Hi @wwingYu 請確認一下 `XIV on Mac` 資料夾的內容，我的資料內容如下：
> 
> ![CleanShot 2023-05-27 at 19 11 47](https://user-images.githubusercontent.com/2776756/241384726-151f063f-15b2-4eb7-b236-970465d98760.png)

我的是這樣的，目前是version 4.9
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/22545788/7bacaa21-81c9-4c5d-a81d-59faa1fcc4ee)

**Comment by wwingYu** [comment]
最後使用了`/Users/使用者帳號/Library/Application Support/FINAL FANTASY XIV ONLINE/Bottles/published_Final_Fantasy/drive_c/Program Files (x86)/SquareEnix/FINAL FANTASY XIV - A Realm Reborn` 作為根目錄終於成功了，供大家參考
