### ISSUE TITLE
零式萬魔殿部分技能沒有漢化

### ISSUE THREAD

**Issue by itistimetobed** [GpointChen/FFXIVChnTextPatch-GP#312]
如題，覆蓋的語言是英文
如P6S的軟體細胞流惡病質，P8S的四分八分核爆，用到現在一直都還是顯示英文原文，想請問是原檔沒有加上還是覆蓋英文文本的關係

**Comment by Souma-Sumire** [comment]
rsv部分gp应该都没写吧。
我发一份附件，可以自己对照修改一下csv。只不过是简体中文的。
[6.2国服RSV.xlsx](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/11183211/6.2.RSV.xlsx)

**Comment by GpointChen** [comment]
通常就是原檔沒有加上。

通常會這樣是如上所述，原文是RSV類格式，我無法單從遊戲檔案確定原文或翻譯為何，所以這部分不予覆蓋。

**Comment by GpointChen** [comment]
已修正於之前的pull requests和6.3翻譯更新，關閉本串。
