### ISSUE TITLE
Error: Unable to access jarfile XXXXX

### ISSUE THREAD

**Issue by TaurusWater** [GpointChen/FFXIVChnTextPatch-GP#313]
如上, 請問應該怎解決. 謝謝

**Comment by GpointChen** [comment]
你是開啟exe然後跳出這個訊息嗎？

**Comment by TaurusWater** [comment]
> 你是開啟exe然後跳出這個訊息嗎？

對呀

**Comment by GpointChen** [comment]
你可以在command line輸入`java -version`檢查一下電腦裡有沒有安裝Java。

如果有且版本正確，可以參考這篇 #90 看看得到的結果。

**Comment by GpointChen** [comment]
Closed as inactive.
