### ISSUE TITLE
关于汉化后act的cactbot无法使用的问题

### ISSUE THREAD

**Issue by mokeling** [GpointChen/FFXIVChnTextPatch-GP#314]
souma大佬[https://github.com/Souma-Sumire/FFXIVChnTextPatch-Souma]有进行针对act的关键词汉化，但是汉化不全，请问作者大大你们俩的汉化有办法能互补吗_(:з」∠)_
另外中国服的汉化打不上去，进去后只会显示源语言

**Comment by GpointChen** [comment]
沒有用過cactbot，只能說之後研究看看

如果是用中國服的檔案漢化，只要中國服和國際服檔案結構不同就容易打不上去，所以通常還是推薦使用CSV。

**Comment by mokeling** [comment]
好的，感谢大大，cactbot的正则应该是和BnpcName和PlaceName有关，应该是只能通过改cactbot才能解决了

**Comment by mokeling** [comment]
好的，感谢大大，cactbot的正则应该是和BnpcName和PlaceName有关，应该是只能通过改cactbot才能解决了发件人: ***@***.*** ***@***.***> 代表 GpointChen ***@***.***>发送时间: 2023年4月21日星期五 18:27收件人: FFXIVChnTextPatch-GP ***@***.***>抄送: 1391100387 ***@***.***>; author ***@***.***>主题: Re: [GpointChen/FFXIVChnTextPatch-GP] 关于汉化后act的cactbot无法使用的问题 (Issue #314)
沒有用過cactbot，只能說之後研究看看
如果是用中國服的檔案漢化，只要中國服和國際服檔案結構不同就容易打不上去，所以通常還是推薦使用CSV。
