### ISSUE TITLE
游戏CG字幕没有汉化

### ISSUE THREAD

**Issue by yyang135** [GpointChen/FFXIVChnTextPatch-GP#318]
装完了最新版的csv和高画质字体, CG的字幕没有翻译, 依旧是日语. 请问这个是不是没法翻译CG的字幕?

**Comment by GpointChen** [comment]
哪一段的CG？

**Comment by chun1324** [comment]
![image](https://user-images.githubusercontent.com/15475075/233844134-f8b90976-aaf8-4b57-bda0-bd5de714217e.png)
你說的是5.0這段嗎?

**Comment by yyang135** [comment]
![image](https://user-images.githubusercontent.com/40533047/234186518-3f12b257-240d-4c90-a18c-3df7936111d4.png)
我才开始玩, 像2.0一开始的这一段.

**Comment by yyang135** [comment]
> 有部分cg的文字是图片的，你用Textools就能看到

原来是图片, 谢谢!
