### ISSUE TITLE
生產技能名稱問題

### ISSUE THREAD

**Issue by awaww333** [GpointChen/FFXIVChnTextPatch-GP#32]
因製作會用到macro
希望能統一日文或是簡體原文
像是LV84 原文是上級加工但遊戲內是高級
![image](https://user-images.githubusercontent.com/74402698/146637254-88e2c671-c366-4bc7-a414-ee10bc82b282.png)
雖說英文advanced也是可以翻成高級
但"掌握" 翻成 "緊握" 完全是另一種意思了...

另外附上生產模擬器供參考 右上能切換語言
http://ffxiv.tk/crafterbeta/#/crafter-attributes

**Comment by GpointChen** [comment]
我查了一下，因為文本內有另外一個日文原文和掌握一樣的技能被翻譯成緊握，所以用程式跑批量替換的時候被一起改成緊握了。預計下版修正。

至於高級加工，我這邊看是上級加工欸
![ffxiv_12182021_184804_949](https://user-images.githubusercontent.com/34565875/146638365-4270e674-495d-4304-8856-b310cc8a9498.png)
