### ISSUE TITLE
情感動作-嚇唬人的聊天室訊息未翻譯

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#326]
當玩家使用嚇唬人的表情時聊天室會出現以下訊息
`XXXはYYYに驚かしてみせた。`

**Comment by GpointChen** [comment]
你是用最新版本嗎？我看CSV是有翻譯的。

**Comment by chun1324** [comment]
我是昨天下載的, 「嚇唬人」動作也從日文翻譯成中文

**Comment by GpointChen** [comment]
你確認一下是不是v3.0.3.1，開遊戲的情報中心有顯示。

v3.0.3.0也有翻譯但我沒處理好，聊天室log和技能可能會出現原文。

**Comment by chun1324** [comment]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/1887df9d-7786-4f09-b422-d74329ac0826)

**Comment by chun1324** [comment]
明白了, 我等等再更新一次
