### ISSUE TITLE
目錄未翻譯特殊迷宮探索器

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#327]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/0ea3e017-6bc4-48f4-bb30-3189a606ab4f)

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

MainCommand.csv的最後一行應改成：
```
94,特殊迷宮探索器,可以設定和申請參加多變迷宮等特殊迷宮的探索器，也可以查看在特殊迷宮中發現的故事。
```

**Comment by GpointChen** [comment]
於最新版中修正。
