### ISSUE TITLE
黑騎技能說明錯誤

### ISSUE THREAD

**Issue by ndk28319** [GpointChen/FFXIVChnTextPatch-GP#33]
![FINAL FANTASY XIV 2021_12_18 下午 07_23_09](https://user-images.githubusercontent.com/95951780/146639218-442598e1-25af-43af-944a-5e7207c8b35a.png)
是跳斬的複唱時間減少5秒才對

**Comment by GpointChen** [comment]
感謝回報，預計下版修正。
