### ISSUE TITLE
回報：對話筆誤

### ISSUE THREAD

**Issue by SagoAvery** [GpointChen/FFXIVChnTextPatch-GP#331]
回報：對話筆誤
游末邦座標X:11.6 Y:11.9
羅伊登NPC：菁靈族少年所說的話，真是感觸頗深啊......
筆誤，應為精靈族

謝謝您

**Comment by xlinshan** [comment]
第一世界的所有种族叫法和原初世界不同，菁靈族应该是没错的

**Comment by chun1324** [comment]
任務 第一世界的城市
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/4b9f05d5-cc2a-488f-adc0-2da4f31ae2aa)

**Comment by GpointChen** [comment]
如上所述，關閉本串。
