### ISSUE TITLE
無人島一處翻譯

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#332]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/20c87a36-ca84-4d70-b61c-df1712ade7d5)
Addon.csv
`15216,放牧中：<hex:022003E80203>/<hex:022003E80303>只`

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

**Comment by GpointChen** [comment]
於最新版中修正。
