### ISSUE TITLE
報名出海垂釣時的文字為空白

### ISSUE THREAD

**Issue by zue37511** [GpointChen/FFXIVChnTextPatch-GP#335]
一時忘記截圖 但缺少的文字大概是 選擇近海釣魚 或是前往紅玉海釣魚 這兩條航線的選項

**Comment by GpointChen** [comment]
找到問題了，預計下次更新時修正。

如有需要可先自行將下面的檔案解壓後放到`resource\rawexd\custom\006`取代同名檔案，然後還原、重新漢化。

[CtsIkdEntrance_00663.zip](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/11550466/CtsIkdEntrance_00663.zip)
