### ISSUE TITLE
漢化後有些字體會有== 

### ISSUE THREAD

**Issue by jamonstar** [GpointChen/FFXIVChnTextPatch-GP#337]
想問一下解決辦法 已經重灌了一次

**Comment by GpointChen** [comment]
如果你是使用預設的字體包，在大廳會有這樣的問題沒錯，但在遊戲中會是正常的。

如果想要大廳也正常顯示，[需要下載release中的高畫質字體包並調整設定](https://github.com/GpointChen/FFXIVChnTextPatch-GP/wiki/6.-%E5%AD%97%E9%AB%94)。

**Comment by a80818123** [comment]
裝了高畫質字體包都會出錯 正常嗎

**Comment by GpointChen** [comment]
> 裝了高畫質字體包都會出錯 正常嗎

有截圖嗎？

**Comment by a80818123** [comment]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/134535480/22d29c85-1925-4aaf-b40e-374b274e8c6b)

**Comment by GpointChen** [comment]
> ![image](https://user-images.githubusercontent.com/134535480/240680998-22d29c85-1925-4aaf-b40e-374b274e8c6b.png)

請參照[說明](https://github.com/GpointChen/FFXIVChnTextPatch-GP/wiki/6.-%E5%AD%97%E9%AB%94)，在漢化前先調整設定

**Comment by GpointChen** [comment]
Closed as inactive.
