### ISSUE TITLE
您好，想問一下能不能推出一個只漢化定型文的版本呢

### ISSUE THREAD

**Issue by subjadeites** [GpointChen/FFXIVChnTextPatch-GP#34]
或者可以簡單說一下製作思路麼，我自己動手做也可以。
因為全部漢化的話，發送坐標和發送物品可能會在別人那邊看到是中文的，另外本來鄙人就能簡單看懂一些日基的隊伍交流，但是回復苦手，有漢化定型文的話會方便很多這樣子……

**Comment by subjadeites** [comment]
是只導入Completion.csv這個文件就可以了麼~

**Comment by subjadeites** [comment]
試了一下，解決了，需要把剩下所有的csv全部清空，但是保留文件。明天白天寫個腳本處理這個，然後我創建個倉庫丟進去

**Comment by GpointChen** [comment]
理論上除了completion.csv以外全部刪掉就可以了。應該不需要建空檔。

**Comment by subjadeites** [comment]
> 等除了完成。csv以外的全部掉就可以了。不需要建空档。

我之前試了全部刪掉不行，寫了個py腳本把所有csv清空就可以了，已經把resource文件夾打包成zip放在我自己fork一份的項目裡了
https://github.com/subjadeites/FFXIVChnTextPatch-GP

**Comment by GpointChen** [comment]
我之前嘗試是可以的。那就要等我之後再來重新測試。感謝。
