### ISSUE TITLE
無人島NPC空白對白

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#346]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/49639e02-fa3f-488a-a403-6a72396a8811)

**Comment by GpointChen** [comment]
是只有這句空白嗎？有沒有前後的對話

**Comment by chun1324** [comment]
暫時只發現一段空白, 這是剛從開拓小員5號解鎖新發展區域的情況

[1:01]開拓小員5號 : 看來你身上有正適合這裡的開拓用具呢！
[1:01]開拓小員5號 : 只要花費3000枚謝爾達萊青船幣，
就能讓魔法人偶開拓這裡，你看怎麼樣？

[1:01]據點開拓完成！
[1:01]無人島庭具の投影数上限が増加した！
[1:01]可以建造新的地標建築了！
[1:03]かいたくくん6号 :

**Comment by GpointChen** [comment]
這個應該在最新版本（v3.1.0.1）中修復了，可以檢查一下是不是最新版？
