### ISSUE TITLE
無人島-探索目的地未翻譯

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#348]
無人島-採集小員-屯貨倉庫中浜辺一詞未翻譯
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/06729009-f3a8-4092-8129-c4f6c7566ebf)

**Comment by chun1324** [comment]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/97280c00-947c-4974-b203-f565fe7bbdf3)
其他位置都有對應詞

**Comment by GpointChen** [comment]
這個應該是新增的`MJIName.csv`的內容，所以全部沒有翻譯，只是剛好其他原文和中文長得一樣XD

預計下次更新時加入。

**Comment by GpointChen** [comment]
Updated in v3.1.1.0.
