### ISSUE TITLE
[忍者] 技能說明有一處錯誤,望修正 

### ISSUE THREAD

**Issue by ksledu** [GpointChen/FFXIVChnTextPatch-GP#35]
作者你好, 首先感謝你偉大的奉獻精神, 我是用"簡體翻譯"1217版本的,發現忍者某個技能有一處翻譯錯誤,圖片紅框里是錯誤,正確應該是發動條件為"月影雷獸爪預備" 狀態中. 請參考第二張圖片的職業特性說明.謝謝!
![ffxiv_21122021_022621_596](https://user-images.githubusercontent.com/96337656/146793229-30bf4693-2e1f-430d-984b-a496f65697e7.jpg)

![ffxiv_21122021_022643_658](https://user-images.githubusercontent.com/96337656/146793250-3b016b90-332b-4f52-94ac-9b4bf7a867b7.jpg)

**Comment by GpointChen** [comment]
了解，預計下版修正，感謝回報。

**Comment by GpointChen** [comment]
修正於[v2.44](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.44)。
