### ISSUE TITLE
轉移數據中心中的一個對話框會令遊戲崩潰

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#351]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/96cedc82-e6e4-4381-bea9-9801e8a7b4d5)
6.4版在轉移時會出現一個新的按鈕, 按下會立即崩潰

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/d0360efd-4c89-4d13-8b1e-64d48dd69fd4)
切回日文原檔則會正常運作

**Comment by chun1324** [comment]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/61ce534c-d86e-41e1-b07a-b03405600a4e)
我留意到最近有把大區字眼更換成數據中心, 可以順便更換一下

**Comment by chun1324** [comment]
原來我不小心換成舊版檔案
我先再重試看看

**Comment by chun1324** [comment]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/891190df-5bab-44e1-8ac9-690e24154488)
使用3.1.0.1 版依然會出現崩潰狀況

**Comment by GpointChen** [comment]
v3.1.0.2也會嗎？

**Comment by chun1324** [comment]
v3.1.0.2 可以正常顯示, 謝謝提醒
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/b5c4178f-ff7d-444b-91eb-06adf3478603)
