### ISSUE TITLE
遊戲根目錄選擇錯誤 求救

### ISSUE THREAD

**Issue by timcook321** [GpointChen/FFXIVChnTextPatch-GP#357]
我是下載了FFXIVChnTextPatch-20230620rar
然後丟到Winrar解壓
之後在選擇路徑的時候
就一直彈窗請選擇正確的遊戲根目錄
![2C4AF953-6476-4F60-BA81-7040AB7E0832](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/138396255/33e11aad-ebee-45cb-aeda-862a32f66a7d)

然後每次解壓的時候都會彈出這樣的東西
![6866C123-2CF2-40E6-806E-7C38F45AEE55](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/138396255/228b4a95-da33-4f89-8c69-817915b9395c)

已有爬文看到可以在global裡面修改
可是電腦白痴完全不懂要幹嘛߹ㅁ߹)

![CB4C337F-A714-41AB-BCEF-D53E40F3E88C](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/138396255/b985f8c0-e164-4ed6-bef0-56a93e30ca0b)

然後也有看到說要先確認有沒有ffxiv.exe的程式在裡面
![10B6D614-483B-4E91-9DA9-7C5C2094D81D](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/138396255/179f4abb-d9ae-4897-a1ee-742b3befdb92)

我在電腦裡好像都沒有搜到過ffxiv.exe
附上我ff14的檔案 煩請大師過目..
請求各位大大指點迷津 也辛苦作者了TvT 
感激不盡！

**Comment by GpointChen** [comment]
My Games裡面的是遊戲設定檔，遊戲檔案通常是下載時自訂的位置。你可以從平常開遊戲的地方右鍵→開啟檔案位置來確定遊戲檔案的位置。

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/5219f5ea-6e25-4160-9a8b-7ad4e719080e)

以我為例，這樣會打開`G:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\boot`資料夾，其中`G:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn`就是目標路徑，也就是你在`global.properties`裡面看到的`GamePath`那一行。你需要換成你的路徑。

**Comment by chun1324** [comment]
預設安裝路徑
C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by GpointChen** [comment]
如有問題可再回應。
