### ISSUE TITLE
翻譯問題

### ISSUE THREAD

**Issue by peckcat** [GpointChen/FFXIVChnTextPatch-GP#358]
### 符號倒置
\resource\rawexd\Item.csv
35804 行 : 」非請勿入，違者後果自負「
```csv
35799,迷津警示牌,,想來你看過很多類似的警示牌了。這塊也大同小異，上面寫著」非請勿入，違者後果自負「。,迷津警示牌
```
\resource\rawexd\quest\047\FesGsc702_04728.csv
95 行 : 」仙人刺先生「
```csv
90,TEXT_FESGSC702_04728_GODBERT_000_036,拚命工作的人們堅韌得就像是荒野中的仙人掌。<hex:02100103>因此我們遊樂場選用了仙人刺作為吉祥物，<hex:02100103>為表敬意，將它稱為」仙人刺先生「。
```
-----
### 缺失翻譯
『死宮』以及『天宮』的 入口 NPC 、道具交換 NPC、鑑定 NPC 對話及視窗都變為日文

**Comment by GpointChen** [comment]
感謝回報，前半部分已修正於最新的release中。

缺失翻譯的部分，如果可以幫忙貼一下顯示的日文，可以方便我找到相關檔案位置。

**Comment by peckcat** [comment]
剛查了一下，雖然 `content\` 裡還是有 Deep Dungeon 的相關條目，
不過在 `custom\008\` 資料夾底下也有關於`死宮`與`天宮`的翻譯條目在這裡，
看來應該是 FF14 改成讀取以下的檔案了。
> CtsDdd1Entrance_00821.csv
> CtsDdd1Gacha_00822.csv
> CtsDdd1Reward_00823.csv
> CtsDdd2Achievement_00827.csv
> CtsDdd2Entrance_00824.csv
> CtsDdd2Gacha_00825.csv
> CtsDdd2Reward_00826.csv
看起來除了文本變數名稱不同，文本也有一些差異


另外 `custom\008\` 的日文原檔裡有 40 個檔案，
但目前中文裡只有約 20 個，我還沒仔細看過個內容。

**Comment by GpointChen** [comment]
已先push，預計於下次更新時一起release。

有需要的人可先自行取用附檔，取代漢化器的`resource/rawexd`資料夾。

[rawexd-20230713.zip](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/12037615/rawexd-20230713.zip)

**Comment by GpointChen** [comment]
已更新。
