### ISSUE TITLE
你好，極戰6.0第二個BOSS

### ISSUE THREAD

**Issue by LeoTaiwanBL** [GpointChen/FFXIVChnTextPatch-GP#36]
打的時候會出現技能名稱被縮減XD 
此招為同招名稱卻被砍一半
 一瞬間會反應不過來
是王會噴左右旁 要躲上下
 
![image](https://user-images.githubusercontent.com/95277639/146904291-2a4959fe-a0db-4763-a428-a78f0a04df05.png)

**Comment by awaww333** [comment]
有另外載rawexd-1220.rar重新打一次漢化嗎
之前也有人反應 20號這個應該有修正了
試試看吧

**Comment by 3-season** [comment]
1217的補丁要再打一個1220的rawexd
之前有提出過的, 我看改動紀錄是已經修正了

**Comment by GpointChen** [comment]
如上面兩位所說，麻煩手動更新。
