### ISSUE TITLE
FFXIVChnTextPatch-GP.exe 下載後啟動失敗

### ISSUE THREAD

**Issue by MCSC2021** [GpointChen/FFXIVChnTextPatch-GP#361]
我把FFXIVChnTextPatch-20230711.rar 解壓後
執行FFXIVChnTextPatch-GP.exe時出現以下Error message:
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/80908717/d626eb40-840a-41ab-b98f-58246ec1d822)

然後FFXIVChnTextPatch-GP.exe就消失了
已經查過java 是最新版本
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/80908717/f72222ee-4e9f-4e0a-be1d-7ef5c065aa03)

**Comment by GpointChen** [comment]
檔案不見，會是被你防毒幹掉的嗎？

**Comment by MCSC2021** [comment]
原本被Panda Dome 防毒幹掉
Thx
