### ISSUE TITLE
翻譯錯誤 抱歉拖很久才回報

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#362]
![ac91e87a4e37145a88da973d3b86dfe2](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/101965725/b76a936b-f679-4db3-87ef-b11e1eb53abe)
60,TEXT_VOICEMAN_06300_000580_ALPHINAUD,尤盧斯也帶著很吐司兵加入了重建活動，<hex:02100103>此外還有不少其他的志願者，<hex:02100103>不分國籍，不分種族，大家都為了同一個目標努力。
\resource\rawexd\cut_scene\063\VoiceMan_06300.csv

抱歉忙者打零式... 6/21就發現的東西拖到現在才回報 對不起...

**Comment by GpointChen** [comment]
感謝回報，修正於新的release。
