### ISSUE TITLE
请教下CSV用什么软体编辑啊？

### ISSUE THREAD

**Issue by wingchaos** [GpointChen/FFXIVChnTextPatch-GP#37]
大大请问CSV文件用什么编辑，我用excel的打开的话会导致那些 分号“”全部去掉了，导致汉化失败

**Comment by ayimayday** [comment]
對 我也是用excel 編輯 存檔後 分號都不見了~~還是這樣沒差

**Comment by GpointChen** [comment]
我是用sublime text 3進行文字編輯。理論上任何普通的文本編輯器也可以。使用Excel會被變成Microsoft自己的形狀導致格式全部跑掉。
