### ISSUE TITLE
翻譯錯誤

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#370]
6.4 起 的紅蓮劇情更動 導致一些翻譯發生錯誤 
--------------------------------
resource/rawexd/quest/025/StmBda705_02552.csv
114 | TEXT_STMBDA705_02552_RAUBAHN_000_106 | `不滅隊の指揮は、呪剣と共にピピンに託した。<hex:02100103>ゆえに此度は将ではなく、ひとりの武人として戦おう。`
--------------------------
6.35CN

114 | TEXT_STMBDA705_02552_RAUBAHN_000_106 | `找到芝諾斯後不要猶豫，立即將他擊斃。<hex:02100103>我們來比一比誰先找到他。`
這個檔案也需要校正
紅蓮導致的更動看起來不少

**Comment by GpointChen** [comment]
應該於最新版中修正了，如有問題可再回報。
