### ISSUE TITLE
翻譯錯誤或者版本差異問題

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#372]
[https://github.com/GpointChen/FFXIVChnTextPatch-GP/tree/master/resource/rawexd/SpecialShop.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/tree/master/resource/rawexd/SpecialShop.csv)

錯誤  1770436,亞拉戈天文神典石（其他）  
正確  1770436,亞拉戈因果神典石（其他）

**Comment by GpointChen** [comment]
感謝回報，已修正。
