### ISSUE TITLE
想要開啟FFXIVChnTextPatchGP的exe毫無反應

### ISSUE THREAD

**Issue by busfsf** [GpointChen/FFXIVChnTextPatch-GP#377]
開啟exe時他說要java16以上才能開啟，後來我去載完後開啟變成毫無反應

**Comment by GpointChen** [comment]
試試看release頁面這一行的連結：

FFXIVChnTextPatch-20230603.jar：如果你有遇到JNI error，請參考 #90 放到與exe同位置使用。

**Comment by busfsf** [comment]
解壓縮檔案後放進漢化檔案裏面也沒反應
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/144150382/dae38a74-4132-42fc-82b7-d72c5455f885)

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/144150382/af7c1c12-2a99-4d19-82b5-b3b1e1ebfe8a)

**Comment by busfsf** [comment]
然後這是我java的版本
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/144150382/2e685782-24ed-4d95-aaa9-88562f473b08)

**Comment by GpointChen** [comment]
怪怪的
方便看一下你資料夾長怎樣嗎

**Comment by busfsf** [comment]
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/144150382/20ca3db2-c7dd-4749-a05a-6c1a8394dd7b)

**Comment by GpointChen** [comment]
請確認你是下載正確的檔案
https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v3.1.1.5/FFXIVChnTextPatch-20230813.rar

你缺少了幾個資料夾

**Comment by busfsf** [comment]
感謝大大，已解決
