### ISSUE TITLE
翻译后 iinact cactbot - raidboss timeline 不正常

### ISSUE THREAD

**Issue by ziegfeld** [GpointChen/FFXIVChnTextPatch-GP#378]
你好，首先非常感謝這個小工具！

在我使用MacOS （MacBookPro M1Mac） XIV on Mac 客戶端，國際服，翻譯英文- 正體中文後，
Dalamut 衛月插件安裝 iinact， BunnyHUD （等同於win系統下Horizoverlay）打開 "Raidboss - timeline"後，經過測試（ 按此網頁說明 https://github.com/quisquous/cactbot/blob/main/docs/zh-CN/README.md#添加懸浮窗模塊） 
無法顯示任何boss時間軸。 （但"Raidboss - Alert Only"是有部分提示文字和聲音的； raidboss test也有測試信息）

我推測是因為翻譯了內部信息，所以iinact抓下來的network log也變成了部分中文、部分英文的狀況，所以無法解析。

因為ff14程式改成日文版啓動，再次測試 raidboss 時間軸（在盛夏農莊木人處輸入 /coutdown 5），其他設置都不變，BunnyHUD的對應時間軸窗口就可以正常出現時間軸信息倒計時了（英文的）。（"Raidboss - Alert Only"會出現更多的提示文字和聲音）

不知道有沒有可能fix呢？需要我提供什麼樣的log來幫助debug請告訴我。

再次非常感謝！

**Comment by GpointChen** [comment]
試著刪除Action.csv和BNpcName.csv後重新漢化看看？

**Comment by ziegfeld** [comment]
感謝回復！

首先，的確如果完全復原，不僅日文版，英文版 iinact是可以完全正常工作的， raidboss timeline overlay 會有信息出來。

我按照您的建議試了刪掉這兩個文件，好像還是不夠，至少盛夏農莊測試還是沒有timeline。
我看了iinact保存下來的log，發現這些還是中文：

```
距離戰鬥開始還有5秒
。。發動了「Tomahawk」
|| striking dummy受到了336點傷害。|
戰鬥開始！
```
但 DPS overlay是有數值跳出來的，所以說可能 「發動技能」「受到傷害」並不太重要？ （至少在盛夏農莊木人測試這個場景里）。

所以想著 戰鬥倒計時和戰鬥開始這兩個string是在哪個csv文件里呢？ 

我發現是 LogMessage.csv 所以準備試一試把它還原後也刪除了再漢化，看會不會成功。

**Comment by chun1324** [comment]
Cactbot 是基於文本去辦認技能&基制
所以只支援簡體中文、英文、法文、德文、日文
有時因為繁體和簡體共用同一個文字才會有反應

如果你會自行 compile 則可以自行下載 cactbot 把所有簡體修改成繁體

**Comment by Souma-Sumire** [comment]
只删除BNpcName全部与LogMessage的5255-5264的就可以了。
与IINACT无关

**Comment by ziegfeld** [comment]
> Cactbot 是基於文本去辦認技能&基制
所以只支援簡體中文、英文、法文、德文、日文

感謝大佬！ 這下理解了。那這個「簡體中文」，是說FF14程序設置裡面一定要有這個選項嗎？國際服現在我是把英文用這個漢化補丁翻譯成簡體中文的，但好像還沒成功顯示timeline （盛夏農莊木人測試）
就是說，我試了下用了 GpointChen 最新發佈的簡體中文版，並且上面所說移除漢化BNpcName等等，好像還不行。
不知道您有什麼建議嗎？

**Comment by ziegfeld** [comment]
> 只删除BNpcName全部与LogMessage的5255-5264的就可以了。
> 与IINACT无关

哇感谢大佬回复！
我这就测试下来update。

**Comment by chun1324** [comment]
> > Cactbot 是基於文本去辦認技能&基制
> > 所以只支援簡體中文、英文、法文、德文、日文
> 
> 感謝大佬！ 這下理解了。那這個「簡體中文」，是說FF14程序設置裡面一定要有這個選項嗎？國際服現在我是把英文用這個漢化補丁翻譯成簡體中文的，但好像還沒成功顯示timeline （盛夏農莊木人測試） 就是說，我試了下用了 GpointChen 最新發佈的簡體中文版，並且上面所說移除漢化BNpcName等等，好像還不行。 不知道您有什麼建議嗎？

如果是從 ACT 使用 Cactbot, 需要去 ACT Plugins > FFXIV ACT Plugin > Parse Options > Language 設定為中文
其他打開Cactbot的方法未嘗試過

**Comment by ziegfeld** [comment]
> > > Cactbot 是基於文本去辦認技能&基制
> > > 所以只支援簡體中文、英文、法文、德文、日文
> > 
> > 
> > 感謝大佬！ 這下理解了。那這個「簡體中文」，是說FF14程序設置裡面一定要有這個選項嗎？國際服現在我是把英文用這個漢化補丁翻譯成簡體中文的，但好像還沒成功顯示timeline （盛夏農莊木人測試） 就是說，我試了下用了 GpointChen 最新發佈的簡體中文版，並且上面所說移除漢化BNpcName等等，好像還不行。 不知道您有什麼建議嗎？
> 
> 如果是從 ACT 使用 Cactbot, 需要去 ACT Plugins > FFXIV ACT Plugin > Parse Options > Language 設定為中文 其他打開Cactbot的方法未嘗試過

哦哦，那就講通了。因為XIV on Mac現在不支持ACT了，所以我是用的IINACT這個Dalamut衛月插件，很遺憾裡面沒有這個選項；而Cactbot裡面的開發者選項只能修改輸出的顯示時間軸/警示標語的語言，沒提供修改輸入語言的選項（或者說就是沒辦法改）。

感謝分享！以後有人看到這個帖子也能對其有幫助！

**Comment by Souma-Sumire** [comment]
> > 只删除BNpcName全部与LogMessage的5255-5264的就可以了。
> > 与IINACT无关
> 
> 哇感谢大佬回复！ 我这就测试下来update。

Cactbot是取解析挿件的對應語言去做對應的i18n替換。 所以我們要跳過處理這些部分。
主要用到的是敵人的名稱（BNpcName），另外就是部分系統消息（LogMessage），除了countdown的文字之外還有就是情感動作的揮手、告別之類，這樣才會被Cactbot檢測到。

所以我一直是這樣使用：解析挿件的語言選漢化前的用戶端語言（修改後需要重新啟動ACT（不知道IINACT有什麼區別））。

樓上說的改成中文我沒有試過，不確定會不會影響opcode的讀取。

**Comment by ziegfeld** [comment]
https://www.iinact.com/installation/

對，IINACT這個新東西很簡單，我看NGA上面討論也就一個帖子。設置也就這三個頁面，還沒提供語言選項：

<img width="767" alt="Screen Shot 2023-09-10 at 10 49 19 AM" src="https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/220582/7140e6a6-6726-4daf-82f1-7d82f23c355d">


<img width="583" alt="Screen Shot 2023-09-10 at 10 50 34 AM" src="https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/220582/392b9cef-403d-4b88-a57c-0065c5034c0b">

<img width="577" alt="Screen Shot 2023-09-10 at 10 51 06 AM" src="https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/220582/04b8c7fc-9fc3-403c-b555-68df33bec7cf">
