### ISSUE TITLE
發現黑騎技能説明出現錯誤

### ISSUE THREAD

**Issue by itsbosco1025** [GpointChen/FFXIVChnTextPatch-GP#38]
![image](https://user-images.githubusercontent.com/95491003/146920617-d303c2dd-2650-44b3-bbb6-c2e10f324b08.png)
此處的“此技能與腐穢黑暗共用複唱時間”應該改爲“此技能與精雕怒斬共用複唱時間”

**Comment by GpointChen** [comment]
了解，預計下版修正，感謝回報。

**Comment by GpointChen** [comment]
修正於[v2.44](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.44)。
