### ISSUE TITLE
按下“詳細設定”中的“選擇漢化範圍”視窗的關閉鍵 將會同時關閉主程式

### ISSUE THREAD

**Issue by Souma-Sumire** [GpointChen/FFXIVChnTextPatch-GP#386]
這似乎不太對

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/33572696/8793959c-1de5-43e8-9314-a21e55812da0)

**Comment by GpointChen** [comment]
確實，預計下次更新時修正。

**Comment by GpointChen** [comment]
修正於新版。
