### ISSUE TITLE
檔案路徑錯誤

### ISSUE THREAD

**Issue by Mizu0301** [GpointChen/FFXIVChnTextPatch-GP#389]
請問一下這個問題要如何解決
我是選FINAL FANTASY XIV - A Realm Reborn這個檔案
![螢幕擷取畫面 2023-09-25 225148](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/146005578/9f84d0fb-d728-470e-a525-d025ef2ec9c6)

**Comment by GpointChen** [comment]
你所選擇的資料夾內有一個名叫game的資料夾嗎？裡面應該要有一個ffxiv.exe的檔案。

**Comment by Mizu0301** [comment]
> 你所選擇的資料夾內有一個名叫game的資料夾嗎？裡面應該要有一個ffxiv.exe的檔案。

沒有 點進去裡面沒有game的資料夾 這樣是遊戲檔案出了什麼問題嗎

**Comment by GpointChen** [comment]
喔 你可能選錯了資料夾

可以參考這篇看看 https://github.com/GpointChen/FFXIVChnTextPatch-GP/issues/357

**Comment by Mizu0301** [comment]
> 喔 你可能選錯了資料夾
> 
> 可以參考這篇看看 #357

有了 感謝 那以後更新遊戲時只要按還原就行了嗎

**Comment by GpointChen** [comment]
對 先還原後再更新遊戲 通常主程式登入後跳提示就是有更新 按否退出去先還原

**Comment by Mizu0301** [comment]
> 對 先還原後再更新遊戲 通常主程式登入後跳提示就是有更新 按否退出去先還原

好的 謝謝
