### ISSUE TITLE
P9S技能不顯示

### ISSUE THREAD

**Issue by itistimetobed** [GpointChen/FFXIVChnTextPatch-GP#390]
P9S王的前後刀那招(英文會有front/rear)但是漢化之後直接不顯示了

**Comment by GpointChen** [comment]
不顯示是指技能名稱變成空白嗎？

**Comment by itistimetobed** [comment]
是的，技能名稱直接空白，但很奇怪的是只有第一次的前後刀完全沒有顯示，第二次的前後刀會顯示英文

**Comment by GpointChen** [comment]
我確認一下，你是指這兩招嗎？

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/42e873e7-03d1-491a-98f3-8ad69b38475c)
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/d9113d1a-bbe8-4c69-b877-3b4f4fc42699)

**Comment by GpointChen** [comment]
[Action.zip](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/12742200/Action.zip)

我有找到一個地方會導致技能不顯示，原因和 #259 相同。

可以試試看將檔案解壓後丟到resource\rawexd裡面取代同名檔案，然後還原、重新漢化。

**Comment by GpointChen** [comment]
修正於新版。
