### ISSUE TITLE
翻譯錯字

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#394]
[resource/rawexd/quest/046/AktKra201_04635.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/quest/046/AktKra201_04635.csv)

3,TEXT_AKTKRA201_04635_SEQ_03,拉哈布雷亞院收到了獄卒長髮來的「一切正常」的報告。和厄爾庇斯忘海附近的傳送裝置前的特彌斯談談，返回萬魔殿。

"獄卒長發來"

**Comment by GpointChen** [comment]
感謝回報，預計下次更新時修正。

**Comment by Liteya** [comment]
14496,還有<hex:022003E80203>秒火山噴髮結束
Logmessage 吧

**Comment by GpointChen** [comment]
fixed.
