### ISSUE TITLE
6.5 閃退

### ISSUE THREAD

**Issue by Ninisun** [GpointChen/FFXIVChnTextPatch-GP#395]
今天更新 6.5 版之後, 
使用  0928 漢化包 會還沒進主畫面就閃退  (換到其他語言也是閃退)
換回原本的 6 個檔案後, 才正常.

**Comment by GpointChen** [comment]
可能是大版本更新導致的相容性問題，晚點我會更新相容版。

**Comment by Ninisun** [comment]
使用 0910 漢化包也是會閃退...  
謝謝您的無私分享 ~  讓我不用抱著字典或是塔塔路翻譯 玩這個遊戲

**Comment by chun1324** [comment]
「直接用」的檔案只能在當前版本使用 (之前: 6.4, 現在: 6.5)
雖然你可以考慮試用漢化器, 但每次改版也很大機會會當掉
