### ISSUE TITLE
6.5国际服无法汉化？

### ISSUE THREAD

**Issue by jamesxiang11** [GpointChen/FFXIVChnTextPatch-GP#397]
![1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/38471190/cf404bc9-40c0-46a1-a43a-4195c0c1f7f6)
请问我汉化失败是什么情况，进游戏还是日文，设置就是上面这样，感觉也没问题，6.5国际服

**Comment by GpointChen** [comment]
請參考教學使用CSV選項進行漢化。

你的設置是使用中國服檔案進行漢化，需要你自備中國服檔案，且此方式容易因國際服改版、檔案結構改變而失效，故一律推薦使用CSV。

**Comment by jamesxiang11** [comment]
好的谢谢，汉化成功了！

**Comment by jamesxiang11** [comment]
另外我发现进游戏后部分字体会变得模糊，不如技能名字，角色名字
![1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/38471190/43f03b9f-1775-4f9f-b5d9-1c7e9d041840)

**Comment by GpointChen** [comment]
可以試著使用高畫質字體包，不過漢化會跑比較久

詳情可參考：https://github.com/GpointChen/FFXIVChnTextPatch-GP/wiki/6.-%E5%AD%97%E9%AB%94

**Comment by jamesxiang11** [comment]
可以了，再次感谢大佬！！

**Comment by jamesxiang11** [comment]
![1](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/38471190/64ed0ede-a2d5-40a4-9231-89d6b06639bd)
还有一个小反馈就是技能cd的字体大一号，不知道有没有解决方法，我用的普通的高清字体包（非4k）
