### ISSUE TITLE
請問我只想漢化職業技能、技能簡介和角色面板上是哪些文件呀。

### ISSUE THREAD

**Issue by AnyoneCn** [GpointChen/FFXIVChnTextPatch-GP#40]
物品名字我自己找到了是Item.csv，但面板上面的信息並沒有。
![321312312](https://user-images.githubusercontent.com/86087425/147349407-0b489a1b-ee1b-459c-a819-9e69c6e24222.png)
![3123123123](https://user-images.githubusercontent.com/86087425/147349411-2cbda25a-e4e1-42dc-a21b-fca80c410102.png)
![31231231233123](https://user-images.githubusercontent.com/86087425/147349414-4d54d49f-7c92-4413-be9c-a599e1550d45.png)
感謝您的奉獻，可以的話也想支持您。

**Comment by GpointChen** [comment]
技能名稱 Action
技能介紹 ActionTransient
狀態 Sratus
特性 Trait
特性介紹 TraitTransient
其他的散落在各個文件當中
