### ISSUE TITLE
text bug求助

### ISSUE THREAD

**Issue by NgaiHoChan** [GpointChen/FFXIVChnTextPatch-GP#403]
多處出現等於號即“=”

**Comment by NgaiHoChan** [comment]
改用高清patch後修復，希望Lobby也可以中文化

**Comment by hydai** [comment]
你有試過高畫質字體包了嗎？
https://github.com/GpointChen/FFXIVChnTextPatch-GP/wiki/6.-%E5%AD%97%E9%AB%94

我目前用的是這個， Lobby 有成功中文化，並不會出現 `=`
