### ISSUE TITLE
占星技能描述问题

### ISSUE THREAD

**Issue by ksledu** [GpointChen/FFXIVChnTextPatch-GP#41]
作者您好,请看下图,技能描述有异,显示了16进制地址.谢
![ffxiv_26122021_160848_873](https://user-images.githubusercontent.com/96337656/147399514-7d859c5c-4779-44ab-b627-e275abaecd0c.jpg)

**Comment by ksledu** [comment]
我是用简体版的

**Comment by GpointChen** [comment]
此問題在繁體版中已被修復，簡體版會於下次更新時修復。感謝。

**Comment by GpointChen** [comment]
修正於[v2.44](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.44)。
