### ISSUE TITLE
替換字體出錯

### ISSUE THREAD

**Issue by lovelywings** [GpointChen/FFXIVChnTextPatch-GP#413]
你好 想詢問一下 我在使用漢化器+高畫質字體包來更換字體的時候 會卡在font1-MSI.tex這個檔並跳出程式錯誤的訊息 想問怎麼處理

**Comment by GpointChen** [comment]
你是用哪一包呢？

**Comment by lovelywings** [comment]
我是用4K高畫質字體包 後來我把相關檔案刪除之後就能正常運作了 不太曉得原理為何

**Comment by GpointChen** [comment]
Release中附的[font-custom-4k-smaller-20230131.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v3.0.1/font-custom-4k-smaller-20230131.rar)和[font-custom-20230111.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.72.2/font-custom-20230111.rar)應該都沒有包含你所說的那個檔案，你可能用到了別人提供的版本？

**Comment by lovelywings** [comment]
我都是用大大提供的字體包 不曉得是什麼原因才會產生附有MSI名字的檔案

**Comment by GpointChen** [comment]
那我先當解決了，關閉本串。之後問題復發可在本串回覆或另開新串。
