### ISSUE TITLE
漢化程式錯誤

### ISSUE THREAD

**Issue by Mullee7099** [GpointChen/FFXIVChnTextPatch-GP#415]
更新後載了新的漢化器
使用新高畫質字體包之後在 "正在替代文本:EXD/QuestRedoChapterUI.EXH" 時跳出程式錯誤

**Comment by GpointChen** [comment]
新版本可能有不兼容的改動，要等我有空更新一下

**Comment by GpointChen** [comment]
已釋出新版本，如仍有問題可再回覆。
