### ISSUE TITLE
即使用了高畫質字幕,也改了設定也有不少字幕是=

### ISSUE THREAD

**Issue by neko61127** [GpointChen/FFXIVChnTextPatch-GP#417]
即使用了高畫質字幕,也改了設定也有不少字幕是=

**Comment by GpointChen** [comment]
有相關截圖嗎？你是用哪一個高畫質字體包？

**Comment by neko61127** [comment]
![螢幕擷取畫面 (676)](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/157025654/f0acab0e-8a9f-4fa3-b982-5746a741cd89)

**Comment by GpointChen** [comment]
剛測試了一下，三種字體包均能正常顯示。

使用預設的字體包
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/f99d6db7-a09a-429f-88ad-de1fb7005ce4)

使用[font-custom-4k-smaller-20230131.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v3.0.1/font-custom-4k-smaller-20230131.rar)
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/eaa41371-c354-4f67-b2f3-6267a17a35e8)

使用[font-custom-20230111.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.72.2/font-custom-20230111.rar)
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/6de631bf-de8d-4693-9844-36cb266d0b3d)


我猜可能是漢化器的設定沒有勾選到替換字體。你可以確認一下，
1. `conf/global.properties`的設定中，是否為`ReplaText=1`

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/9f8934b7-8474-4b00-8840-6541655310cb)

2. `debug.log`內是否有`[CONFIG ] 替換字體：1`

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/34565875/9f6ec837-3181-4c2d-822b-dbde7b4734d1)

**Comment by chun1324** [comment]
現在漢化器好像不是預設替換字體

**Comment by GpointChen** [comment]
Closed as inactive.
