### ISSUE TITLE
無法下載漢化

### ISSUE THREAD

**Issue by 8888pp** [GpointChen/FFXIVChnTextPatch-GP#427]
由於我無法使用漢化器,故我是直接覆蓋遊戲檔案, 但是今天更新後一直無法下載, 已經把防火牆以及掃毒關閉亦無法下載, 請問有甚麼方法可以解決?

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/20887092/9e7b5f7f-432d-4c90-9c26-ddb084747d55)

**Comment by GpointChen** [comment]
不清楚，我個人環境沒掃到病毒

**Comment by 8888pp** [comment]
更新 今天突然又能下載到了 謝謝
