### ISSUE TITLE
煩請調整翻譯

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#429]
https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/master/resource/rawexd/quest/047/AktKml103_04746.csv

現行

25,TEXT_AKTKML103_04746_TODO_01,在「說話」頻道下輸入「阿金托塔」<hex:02100103>和魯納爾打招呼
95,TEXT_AKTKML103_04746_SAYTODO_000_140,阿金托塔

建議更改為
25,TEXT_AKTKML103_04746_TODO_01,在「說話」頻道下輸入「阿金托塔」<hex:02100103>和魯納爾打招呼(allin tuta)
95,TEXT_AKTKML103_04746_SAYTODO_000_140,allin tuta

**Comment by Liteya** [comment]
咒發 咒髮 這邊是指頭髮的髮
[resource/rawexd/Status.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/0125459995411cd1bf42bd7e7bb33e713dbfc68e/resource/rawexd/Status.csv#L2435)
現
3284,咒發束縛,被巴爾巴莉希婭的咒發所束縛，移動速度降低，體力逐漸減少<hex:02100103>和相連的對象距離過遠時將會受到吸引效果，同時附加持續傷害狀態
建議
3284,咒髮束縛,被巴爾巴莉希婭的咒髮所束縛，移動速度降低，體力逐漸減少<hex:02100103>和相連的對象距離過遠時將會受到吸引效果，同時附加持續傷害狀態

[resource/rawexd/PlaceName.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/0125459995411cd1bf42bd7e7bb33e713dbfc68e/resource/rawexd/PlaceName.csv#L4050)
現
4045,咒發風塔,,

4197,咒發風塔,,
建議
4045,咒髮風塔,,

4197,咒髮風塔,,
[resource/rawexd/CompanionTransient.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/0125459995411cd1bf42bd7e7bb33e713dbfc68e/resource/rawexd/CompanionTransient.csv#L493)
現
488,召喚出寵物「迷你巴爾巴莉希婭」。<hex:02100103>以巴爾巴莉希婭為原型製作的魔法人偶。這次我會讓你徹底消失！,以高貝扎四天王的其中一人風之巴爾巴莉希婭為原型製作的魔法人偶。某位雕金匠在放浪的旅途中，為了將目擊到的大妖異的美傳頌給後世，特地將此製作配方公之於眾。他似乎對該妖異頭髮的靈動感以及野性的美感表現出了強烈的執著。,快、快看那個！<hex:02100103>是風之巴爾巴莉希婭！<hex:02100103>她來了！<hex:02100103>　　　　　——西裡阿多,咒發突襲,打消範圍內敵我雙方身上的附加效果。
建議
488,召喚出寵物「迷你巴爾巴莉希婭」。<hex:02100103>以巴爾巴莉希婭為原型製作的魔法人偶。這次我會讓你徹底消失！,以高貝扎四天王的其中一人風之巴爾巴莉希婭為原型製作的魔法人偶。某位雕金匠在放浪的旅途中，為了將目擊到的大妖異的美傳頌給後世，特地將此製作配方公之於眾。他似乎對該妖異頭髮的靈動感以及野性的美感表現出了強烈的執著。,快、快看那個！<hex:02100103>是風之巴爾巴莉希婭！<hex:02100103>她來了！<hex:02100103>　　　　　——西裡阿多,咒髮突襲,打消範圍內敵我雙方身上的附加效果。

**Comment by GpointChen** [comment]
已更新，仍有問題可再回報。
