### ISSUE TITLE
功能問題

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#435]
[resource/rawexd/quest/044/AktKme107_04425.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/472b5a6d822b3594f8701d0062d4b7a232310038/resource/rawexd/quest/044/AktKme107_04425.csv#L33)

28,TEXT_AKTKME107_04425_TODO_04,在「說話」頻道下輸入「求你了，愛梅特賽爾克」<hex:02100103>(Please, Emet-Selch) 拜託愛梅特賽爾克
142,TEXT_AKTKME107_04425_SAYTODO_000_210,Please, Emet-Selch
--------------------------------
後文要追加 " " 不然裡面的 ,會被截斷

**Comment by GpointChen** [comment]
感謝回報，已更新。
