### ISSUE TITLE
翻譯瑕疵

### ISSUE THREAD

**Issue by Liteya** [GpointChen/FFXIVChnTextPatch-GP#437]
[resource/rawexd/quest/047/AktKva210_04734.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/blob/472b5a6d822b3594f8701d0062d4b7a232310038/resource/rawexd/quest/047/AktKva210_04734.csv#L75)

<html>
<body>

70 | TEXT_AKTKVA210_04734_HANCOCK_000_023 | 假設同樣的一枚價值100的金幣，<hex:02100103>如果用於投資未來，或許最終能變成200甚至1000金幣。<hex:02100103>但是如果用於享樂，那隻會變成0。

</body>
</html>

那隻會 (X)
那只會 (O)
---------
另外 中國6.55上了

**Comment by GpointChen** [comment]
感謝回報，已更新。
