### ISSUE TITLE
傳送選單的字體對齊

### ISSUE THREAD

**Issue by liuedd** [GpointChen/FFXIVChnTextPatch-GP#44]
設定返回點的字沒對齊到，因為很常會用到，再麻煩作者修正一下，非常感謝!!

![ffxiv_dx11_pin0E1IdQO](https://user-images.githubusercontent.com/51795301/147895120-928ae834-3fbf-42b0-9191-3c4cbbadfee6.png)

**Comment by GpointChen** [comment]
這個我也有發現，不過因為不算緊急所以還沒改，下次更新時會改。感謝回報。

**Comment by GpointChen** [comment]
修正於[v2.44](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.44)。
