### ISSUE TITLE
多个技能描述依然是日文

### ISSUE THREAD

**Issue by cerrorism** [GpointChen/FFXIVChnTextPatch-GP#444]
使用6/28的release汉化器，和rawexd-zhcn-20240628.rar简体中文CSV

![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/1614015/c188e1ef-8c19-49e2-bb8d-3db5cee1bca6)
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/1614015/1767e610-c0c7-48e8-9b56-541f8a7f47d2)
![image](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/1614015/c9c07174-e1c7-479b-a799-17a3766f541c)

感谢汉化！

**Comment by Souma-Sumire** [comment]
因為這些文字包含指令碼更新，我認為作者為了防止遊戲崩潰而删除了它們

**Comment by GpointChen** [comment]
是的，7.0更新包含比較多的技能改動，其中包含大量牽涉指令碼的內容，先將這部分拿掉了

**Comment by cerrorism** [comment]
谢谢，期待后续的更新！
