### ISSUE TITLE
Pictomancer 任務 NPC 消失

### ISSUE THREAD

**Issue by chun1324** [GpointChen/FFXIVChnTextPatch-GP#448]
80級任務 Mind over Manor 完成後, 提交任務時發現NPC頭上結束任務的圖示不會消失, NPC不能對話, 重新登入後NPC會消失不見
使用還原檔案即可修復
![image (1)](https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/15475075/c2ee081c-8dd7-4a90-9787-a928babb5d8e)

**Comment by casperhsia** [comment]
有同樣的狀況

**Comment by GpointChen** [comment]
了解，再找時間研究

**Comment by GpointChen** [comment]
7.0漢化已更新，可至release下載。
如仍有遇到同樣問題可再回報。
