### ISSUE TITLE
6.01 新 NPC 及裝備無法正常顯示

### ISSUE THREAD

**Issue by iveslazycat** [GpointChen/FFXIVChnTextPatch-GP#45]
根據朋友說
6.01 開啟萬磨殿任務的 NPC 會變透明
6.01 新增的道具裝備，也會無法顯示

**Comment by GpointChen** [comment]
說實話我沒有遇到這個問題，如使用新版（[v2.44](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.44)）仍遇到類似狀況，歡迎截圖回報。

感謝。
