### ISSUE TITLE
萨维奈岛白滨村dx11报错

### ISSUE THREAD

**Issue by Nymiad** [GpointChen/FFXIVChnTextPatch-GP#452]
<img width="944" alt="image" src="https://github.com/GpointChen/FFXIVChnTextPatch-GP/assets/141546889/43a0863b-7386-494a-8c88-daf05492b694">

好几次飞到这附近就会报错闪退
还原档案一切正常

**Comment by GpointChen** [comment]
了解，再找時間研究

**Comment by GpointChen** [comment]
7.0漢化已更新，可至release下載。
如仍有遇到同樣問題可再回報。
