### ISSUE TITLE
各工匠或採集的職業任務

### ISSUE THREAD

**Issue by qwe3410475** [GpointChen/FFXIVChnTextPatch-GP#46]
職業任務在6.0是不是有更改物品數量？
說99個結果都是10 或 15~
或者HQ素材等等~ 
不過不影響實際上的內容 所以不是很要緊~
只是回報一下~ 等作者您有空再修改
謝謝！辛苦了

**Comment by GpointChen** [comment]
了解，我會抽空檢查相關任務文本，感謝回報。

**Comment by GpointChen** [comment]
已修正於v2.51。
