### ISSUE TITLE
2024/07/17漢化包解壓縮後的執行檔打開後無法更動遊戲路徑

### ISSUE THREAD

**Issue by LeeSzt** [GpointChen/FFXIVChnTextPatch-GP#462]
![問題1](https://github.com/user-attachments/assets/a2cad1ac-3164-4a4a-8002-c72eae390e9c)
![問題2](https://github.com/user-attachments/assets/1845d5f2-597e-4e28-9a87-f0b86e0a494b)
![問題5](https://github.com/user-attachments/assets/70d843cf-ca5b-4e6f-945f-232a3740770e)
作者您好，我使用第二個方法漢化出現如標題問題 [(相關問題照片如附件)，目前已嘗試過:
1.登入遊戲中遊玩一會 
2.下載除7/17以外釋出的漢化包 (仍然遇到相同狀況)
補充:  1.電腦的規格為W11，詳細內容如附件 2.我的FF14是載在外接硬碟中
有詢問過安裝0717漢化包的其他玩家，並沒有與我有相同問題的情形發生.....
謝謝您。

**Comment by GpointChen** [comment]
你所選擇的資料夾內有一個名叫game的資料夾嗎？

裡面應該要有一個ffxiv.exe的檔案。

**Comment by GpointChen** [comment]
可以參考 https://github.com/GpointChen/FFXIVChnTextPatch-GP/issues/357 確認自己所選的路徑是否正確

**Comment by LeeSzt** [comment]
> 可以參考 #357 確認自己所選的路徑是否正確
作者您好，我已詳閱#357的問題，並且利用global property 更改了遊戲路徑(如附件)，但目前依然是跳出[請選擇正確的遊戲根目錄]。
另外我有在 game中找到 ffxiv_dx11 的執行檔之路徑，但更改了其遊戲路徑也無果。
不曉得還能做什麼嘗試，謝謝您。
![討論1](https://github.com/user-attachments/assets/c045eae3-7202-4e09-917d-ae6d06037c66)
![討論2](https://github.com/user-attachments/assets/6f760370-5793-4e69-b409-638bd65e97a8)
![討論3](https://github.com/user-attachments/assets/720d5173-2892-477e-a015-001acf4810df)
![討論4](https://github.com/user-attachments/assets/8cf80292-7b02-46fe-95af-976493cdf152)

**Comment by GpointChen** [comment]
或者，按照你顯示的路徑，global properties應該要修改成：
```
D\:\\FINAL FANTASY XIV - A Realm Reborn
```
需要加額外的斜線。

**Comment by kalispp** [comment]
最後一張圖看到少了ffxiv.exe，不是ffxiv_dx11.exe

![image](https://github.com/user-attachments/assets/cd801740-448b-485b-ba7e-4d2be31bee4b)
