### ISSUE TITLE
覆蓋版本 更新後野外死亡回城會無法進入遊戲

### ISSUE THREAD

**Issue by yoyoys** [GpointChen/FFXIVChnTextPatch-GP#463]
![image](https://github.com/user-attachments/assets/df10ae8d-4545-4b3e-97b6-ec33622b0f48)
我回歸目標是喪靈鐘 Q_Q

**Comment by GpointChen** [comment]
這週有更新，要等我找時間更新一版

**Comment by yoyoys** [comment]
我後來發現是 ACT 的問題，關掉就沒事了，和這週更新無關，謝謝🥺
