### ISSUE TITLE
缺少翻譯文本

### ISSUE THREAD

**Issue by dks50217** [GpointChen/FFXIVChnTextPatch-GP#468]
文本路徑內缺少以下兩個檔案，這兩個為**魔法大學採集製作**其中的一個職任
- \resource\rawexd\quest\041\AktKla403_04155.csv
- \resource\rawexd\quest\041\AktKla503_04162.csv

**Comment by GpointChen** [comment]
7.0漢化已更新，可至release下載。
如仍有遇到同樣問題可再回報。
