### ISSUE TITLE
部分技能及介面使用漢化工具後仍為日文

### ISSUE THREAD

**Issue by NS157** [GpointChen/FFXIVChnTextPatch-GP#469]
您好我是剛玩的新手(職業選白魔法師)，使用漢化工具後有部分技能名稱及說明仍顯示日文以及部分介面上面說明文仍是日文，不知道是否屬正常?
![1](https://github.com/user-attachments/assets/0990c1ed-5831-46eb-aa22-a75e9fe32dad)

**Comment by Souma-Sumire** [comment]
你好，請參攷 #444

**Comment by GpointChen** [comment]
7.0漢化已更新，可至release下載。
如仍有遇到同樣問題可再回報。
