### ISSUE TITLE
技能說明錯誤

### ISSUE THREAD

**Issue by ndk28319** [GpointChen/FFXIVChnTextPatch-GP#47]
正確：
![1](https://user-images.githubusercontent.com/95951780/148003905-bd8e0ef1-5cec-4112-9301-f0bd767d87cf.png)
![2](https://user-images.githubusercontent.com/95951780/148003910-9383d7cf-f5ab-4d65-b22a-5bdc87a4b5b8.png)
錯誤：
![3](https://user-images.githubusercontent.com/95951780/148003940-1b877543-7f8c-40f2-8ad1-094293ba2ee3.png)
![4](https://user-images.githubusercontent.com/95951780/148003945-ff1cc90a-11a9-4729-8b0e-87c0aed7bb99.png)

**Comment by GpointChen** [comment]
已修正於[v2.45](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.45)。

感謝回報。
