### ISSUE TITLE
跨界轉送會崩潰

### ISSUE THREAD

**Issue by alvinyeung** [GpointChen/FFXIVChnTextPatch-GP#478]
當在主城想傳送到其他WORLD時，遊戲就會崩潰，可以幫忙看看嗎？
![image](https://github.com/user-attachments/assets/ff2aef6b-8354-4ce1-b95e-1a7666ceb26b)
![image](https://github.com/user-attachments/assets/e922b666-df81-4a35-96f3-d4c0daa07e75)

**Comment by GpointChen** [comment]
已有修正於最新版，請重新下載。

**Comment by yoyoys** [comment]
@alvinyeung 你的字體怎麼特別漂亮 XD

**Comment by alvinyeung** [comment]
> @alvinyeung 你的字體怎麼特別漂亮 XD

是巴哈另一個大佬提供的字型

**Comment by yoyoys** [comment]
> > @alvinyeung 你的字體怎麼特別漂亮 XD
> 
> 是巴哈另一個大佬提供的字型

方便提供嗎？謝謝😊

**Comment by alvinyeung** [comment]
> > > @alvinyeung 你的字體怎麼特別漂亮 XD
> > 
> > 
> > 是巴哈另一個大佬提供的字型
> 
> 方便提供嗎？謝謝😊

我不太確定能怎麼給你，畢竟在這裡分享其他大佬的資源好像不太適合XD
