### ISSUE TITLE
任務名稱變成false

### ISSUE THREAD

**Issue by ryanho** [GpointChen/FFXIVChnTextPatch-GP#48]
安裝PatchTool 6.05 1/4
檔案語言選擇CSV，原始語言選擇日文

邊獄的任務進入點與任務搜尋器中的標題都變成false
![2022-01-04 20_35_22-FINAL FANTASY XIV](https://user-images.githubusercontent.com/204075/148060847-ea4be3cb-9000-460a-bc2e-64bac3475a45.png)
![2022-01-04 20_40_07-Window](https://user-images.githubusercontent.com/204075/148060868-df3e6cdf-5e5b-419e-9c52-65eb6dc2d1f4.png)

**Comment by GpointChen** [comment]
我也發現了，可能是部分任務漢化後出現問題，預計於下版修正。

感謝回報。
