### ISSUE TITLE
简体中文包好像里面依然是繁体

### ISSUE THREAD

**Issue by HRFleur** [GpointChen/FFXIVChnTextPatch-GP#485]
我下载了两次打开csv检查了，应该是繁体无误。不知是否也有用简体的朋友帮忙验证一下。

**Comment by GpointChen** [comment]
看了一下應該是我沒替換到
晚上重傳一份

**Comment by GpointChen** [comment]
updated.

**Comment by HRFleur** [comment]
感谢感谢。
另中国服已更新至7.05，如果空闲可否考虑也更新一下翻译内容。
7.1技改的技能描述也是老版本，特别是pvp部分改了很多描述和实际效果都对应不上。

**Comment by GpointChen** [comment]
已更新7.05
