### ISSUE TITLE
Release的PatchTool 7.10 11/14 版本問題

### ISSUE THREAD

**Issue by iTouiTOUEiki** [GpointChen/FFXIVChnTextPatch-GP#487]
不好意思打擾了，PatchTool 7.10 11/14的
Source code (zip)
Source code (tar.gz)
似乎還是10/5的檔案
使用mac版編譯出來使用文字仍顯示為3.3.1.1適用7.05
可以的話再麻煩您上傳提供 非常感謝

**Comment by GpointChen** [comment]
👌
