### ISSUE TITLE
天書轉圈圈

### ISSUE THREAD

**Issue by ZecGG** [GpointChen/FFXIVChnTextPatch-GP#49]
使用最新版的(1/4發布)的之後
天書一直卡在轉圈圈
問了一下谷歌老師後是說中文化有問題
我還原之後仍然在轉圈圈
之後使用遊戲內建的修復功能之後就正常了(全檔案重跑一遍)
不知道是發生了什麼事

**Comment by GpointChen** [comment]
我的天書是正常的，按照你的敘述，我猜可能是你原本檔案有損毀，和漢化沒有關係？

修復後再使用漢化是正常的嗎？

**Comment by ZecGG** [comment]
> 我的天書是正常的，按照你的敘述，我猜可能是你原本檔案有損毀，和漢化沒有關係？
> 
> 修復後再使用漢化是正常的嗎？

我目前還沒再使用
想說先解完天書試試看
不然重跑一遍花了我兩個小時
如果沒問題我再回報

**Comment by qwe3410475** [comment]
我這邊天書也沒問題哦~

**Comment by ZecGG** [comment]
我重新裝回12/17發布的目前沒問題了
1/4發布的我沒有勇氣再度嘗試
