### ISSUE TITLE
翻譯錯誤

### ISSUE THREAD

**Issue by iveslazycat** [GpointChen/FFXIVChnTextPatch-GP#5]
1.  \resource\rawexd\quest\014\HeaVnz026_01476.csv
    阿拉米格猛牛『隻要』在烏爾達哈一天 -> 阿拉米格猛牛『只要』在烏爾達哈一天

2. resource\nlpcn\traditional.txt
    弔死 -> 吊死
    弔橋 -> 吊橋
    繁簡轉換特例這邊就不對了
    所以其他依此轉換的文本也都錯誤

3. 製作技能的 『閒靜』 -> 『閑靜』
    雖然好像有一本兩岸文字對照辭典的是用『閒』
    但是台灣教育部的國語辭典沒有使用『閒』的情況
    http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi
    
另外請問一下，像這種少量臨時遇到的翻譯錯誤，
會希望累積多一點還是隨時可以回報?
以及發 issue 或 pull request 哪個會比較方便?

**Comment by GpointChen** [comment]
> 1. \resource\rawexd\quest\014\HeaVnz026_01476.csv
>    阿拉米格猛牛『隻要』在烏爾達哈一天 -> 阿拉米格猛牛『只要』在烏爾達哈一天
> 2. resource\nlpcn\traditional.txt
>    弔死 -> 吊死
>    弔橋 -> 吊橋
>    繁簡轉換特例這邊就不對了
>    所以其他依此轉換的文本也都錯誤
> 3. 製作技能的 『閒靜』 -> 『閑靜』
>    雖然好像有一本兩岸文字對照辭典的是用『閒』
>    但是台灣教育部的國語辭典沒有使用『閒』的情況
>    http://dict.revised.moe.edu.tw/cgi-bin/cbdic/gsweb.cgi
> 

感謝回報，已修正。

> 另外請問一下，像這種少量臨時遇到的翻譯錯誤，
> 會希望累積多一點還是隨時可以回報?
> 以及發 issue 或 pull request 哪個會比較方便?

兩個問題都是「都可以」，選自己方便的就好。

當然比較小的修正不一定會馬上打包新的release。

**Comment by iveslazycat** [comment]
那我再視情況選擇方式。
然後 release 的部分，
我想會有指令影響的時候再發布應該就很夠了。
不然平常也都是錯字修正比較多，
應該不太影響遊戲體驗。
