### ISSUE TITLE
無法直接使用中國服檔案進行漢化

### ISSUE THREAD

**Issue by iceheat** [GpointChen/FFXIVChnTextPatch-GP#50]
大大你好
首先感謝大大您的付出, 沒有您的犧牲及奉獻, 我們大家都沒辦法享受中文版的FF14, 但我在使用的時候卻發現了以下的問題

我之前是使用提莫苑, 可以完成漢化並遊玩, 但南方戰線卻不能進去, 改用你的這個漢化版本就沒有這方面的問題, 但前提是必須要選CSV才能完成漢化

我有遵從你的說明直接提取中國服的0a0000三個檔案並放至resource/text資料夾下
一切都照你的說明(檔案語言選簡體中文, 原始語言選日文, 目標語言選正體中文), 結果最後卻出現漢化錯誤-程式錯誤的圖示, 進遊戲也還是日文

請問該如何解決?

**Comment by GpointChen** [comment]
現在中國服檔案還在5.X，6.0有許多檔案結構有變，所以目前無法用於漢化。
