### ISSUE TITLE
自翻的白票商人!!

### ISSUE THREAD

**Issue by ayimayday** [GpointChen/FFXIVChnTextPatch-GP#51]
[InclusionShopCategory.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/7819807/InclusionShopCategory.csv)
[InclusionShopWelcomText.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/7819808/InclusionShopWelcomText.csv)
[InclusionShop.csv](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/7819809/InclusionShop.csv)

請問我自翻的可以給你用嗎

**Comment by GpointChen** [comment]
可以啊，感謝你的翻譯。預計會在下次更新添加。
