### ISSUE TITLE
庫洛的奇談書 沒反應

### ISSUE THREAD

**Issue by tarues** [GpointChen/FFXIVChnTextPatch-GP#52]
1/4漢化更新 -> 打完任務後 奇談書 沒有顯示完成

![image](https://user-images.githubusercontent.com/97215598/148340000-f3b72568-2814-4ad6-9f78-50587544a715.png)

嘗試關掉漢化之後 ->  打完任務 奇談書才顯示完成

![image](https://user-images.githubusercontent.com/97215598/148340045-aa96f694-9b14-44f9-8a1d-7c6d6cc9fc27.png)

**Comment by GpointChen** [comment]
你這是同一本奇談書嗎？我看兩張圖內的圖示不一樣

**Comment by GpointChen** [comment]
補充一下，我的天書是正常的。

![螢幕擷取畫面 (1540)](https://user-images.githubusercontent.com/34565875/148382037-ebc1aac1-648c-444a-a05a-9953c1d4f8f2.png)
![螢幕擷取畫面 (1541)](https://user-images.githubusercontent.com/34565875/148381763-cad5a224-0c84-4f59-b284-45328d8f44b6.png)

**Comment by tarues** [comment]
不同本
但只是想示意一下圖案
我再測試 謝謝!
