### ISSUE TITLE
1/5更新後無法進住宅區

### ISSUE THREAD

**Issue by SuperQvQ** [GpointChen/FFXIVChnTextPatch-GP#53]
已經兩台電腦都這樣了
還原也無效，是不是只能重灌

**Comment by GpointChen** [comment]
還原是直接還原成漢化前的檔案。因此如果還原也無法進入住宅區，代表你可能原本檔案就有損毀。

你可能需要重灌或跟別人要遊戲檔案。

**Comment by Hungtree** [comment]
我也是遇到同樣的問題 但不只 在 住宅區 在水都也發生過 重登就會好 住宅區直接卡死  跳出幾個檔案有問題 無法進入 研情況判 似乎是1/5號後更新的物品  只要有遇到就會 錯誤斷開  住宅區 擺設新物品(1/5號新增的) 就會錯誤 提供參考 目前修復檔案中QQ

**Comment by SuperQvQ** [comment]
> 還原是直接還原成漢化前的檔案。因此如果還原也無法進入住宅區，代表你可能原本檔案就有損毀。
> 
> 你可能需要重灌或跟別人要遊戲檔案。
> 
> Edit: 我個人測試可以進入住宅區，你是從哪裡進入住宅區？（傳送選單還是與NPC對話？）無法進入是跳錯誤閃退還是？

海都的住宅區，只要一傳送過去就會卡讀取畫面
除了重灌遊戲其他的方法都試過了

**Comment by GpointChen** [comment]
感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？

因為我進得去海都房區，目前沒有發現任何問題。

**Comment by Hungtree** [comment]
> 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> 
> 因為我進得去海都房區，目前沒有發現任何問題。

可以請大大去找看看有沒有人擺放1/5號更新的擺飾嗎? 我覺得沒問題是因為沒遇到有擺放新擺飾 的物品 所以顯示正常 沒閃退
畢竟是1/5更新後才出現的 這之前我使用都很正常 一更新後 我們公會房就擺放 更新後的 物品 導致 回公會房就 錯誤  也是跟其他人一樣 卡讀取畫面 之後再連 都是錯誤

**Comment by GpointChen** [comment]
> > 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> > 因為我進得去海都房區，目前沒有發現任何問題。
> 
> 可以請大大去找看看有沒有人擺放1/5號更新的擺飾嗎? 我覺得沒問題是因為沒遇到有擺放新擺飾 的物品 所以顯示正常 沒閃退 畢竟是1/5更新後才出現的 這之前我使用都很正常 一更新後 我們公會房就擺放 更新後的 物品 導致 回公會房就 錯誤 也是跟其他人一樣 卡讀取畫面 之後再連 都是錯誤

OK我找找看

方便知道你們擺了哪些新擺飾嗎？

**Comment by Hungtree** [comment]
https://jp.finalfantasyxiv.com/lodestone/topics/detail/aad51cf6b01c929163b90d8f8b757255cb574207  這是6.05更新的物品



> > > 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> > > 因為我進得去海都房區，目前沒有發現任何問題。
> > 
> > 
> > 可以請大大去找看看有沒有人擺放1/5號更新的擺飾嗎? 我覺得沒問題是因為沒遇到有擺放新擺飾 的物品 所以顯示正常 沒閃退 畢竟是1/5更新後才出現的 這之前我使用都很正常 一更新後 我們公會房就擺放 更新後的 物品 導致 回公會房就 錯誤 也是跟其他人一樣 卡讀取畫面 之後再連 都是錯誤
> 
> OK我找找看
> 
> 方便知道你們擺了哪些新擺飾嗎？



> > > 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> > > 因為我進得去海都房區，目前沒有發現任何問題。
> > 
> > 
> > 可以請大大去找看看有沒有人擺放1/5號更新的擺飾嗎? 我覺得沒問題是因為沒遇到有擺放新擺飾 的物品 所以顯示正常 沒閃退 畢竟是1/5更新後才出現的 這之前我使用都很正常 一更新後 我們公會房就擺放 更新後的 物品 導致 回公會房就 錯誤 也是跟其他人一樣 卡讀取畫面 之後再連 都是錯誤
> 
> OK我找找看
> 
> 方便知道你們擺了哪些新擺飾嗎？

https://jp.finalfantasyxiv.com/lodestone/topics/detail/aad51cf6b01c929163b90d8f8b757255cb574207

這是6.05 官方公布更新的事項 
我也不清楚公會擺放那些新物品  但更新後 在頻道看過公會人員 在頻道展示 新物品  滑鼠移過去觀看 都沒圖案
聽它們擺放過後 才回公會 就 一直呈現讀取畫面 猜測(純屬個人猜測)是找不到新物品對照日文 所以一直讀取  我強制關遊戲  就檔案損毀了 提供參考

提供參考

**Comment by SuperQvQ** [comment]
> 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> 
> 因為我進得去海都房區，目前沒有發現任何問題。

我們是海都17-39
FC隊長說他沒有新增擺設
目前在懷疑是官方聖誕節的東西

**Comment by Hungtree** [comment]
> > 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> > 因為我進得去海都房區，目前沒有發現任何問題。
> 
> 我們是海都17-39 FC隊長說他沒有新增擺設 目前在懷疑是官方聖誕節的東西

你們加沒擺設 那...隔壁家有更新擺設嗎XD

**Comment by GpointChen** [comment]
> > 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> > 因為我進得去海都房區，目前沒有發現任何問題。
> 
> 我們是海都17-39 FC隊長說他沒有新增擺設 目前在懷疑是官方聖誕節的東西

Typhon  17-39 正常 沒有出現閃退情形

**Comment by SuperQvQ** [comment]
> > > 感謝回報。有更詳細的資訊嗎？例如是在第幾區或是哪間房子會引起閃退？
> > > 因為我進得去海都房區，目前沒有發現任何問題。
> > 
> > 
> > 我們是海都17-39 FC隊長說他沒有新增擺設 目前在懷疑是官方聖誕節的東西
> 
> Typhon 17-39 正常 沒有出現閃退或卡讀取情形

嗚嗚..看來我是個案了
睡醒準備來重灌😔

**Comment by ReMioco** [comment]
我是Typhon 17-39的FC隊長 那天成員有反應問題 他是版本只有到5.0 沒買6.0
我測試過 可以正常loading 所以應該是沒買到6.0的關係

**Comment by ReMioco** [comment]
> 我是Typhon 海都17-39的FC隊長 那天成員有反應問題 他是版本只有到5.0 沒買6.0 我測試過 可以正常loading 所以應該是沒買到6.0的關係

剛剛跟成員確認過有買到6.0...
那可能真的是檔案損毀了QQ

**Comment by GpointChen** [comment]
感謝各位的排查，目前看似不是漢化的問題。先關閉此issue。
