### ISSUE TITLE
新手問題><

### ISSUE THREAD

**Issue by PinkEvo** [GpointChen/FFXIVChnTextPatch-GP#55]
是不是6.0依然沒有完成漢化呢
玩到了6.0後
關於6.0的內容全部變成原文了

先謝謝解答!

**Comment by GpointChen** [comment]
> 是不是6.0依然沒有完成漢化呢 玩到了6.0後 關於6.0的內容全部變成原文了
> 
> 先謝謝解答!

目前幾乎所有主線劇情都是沒有漢化的，只有極少數過場有人提供了漢化文本。

如果想玩劇情，推薦使用Tataru Helper；我記得巴哈上有人做出改良版本，我個人認為看懂劇情沒有問題。
