### ISSUE TITLE
占星術士一個技能未翻譯

### ISSUE THREAD

**Issue by ndk28319** [GpointChen/FFXIVChnTextPatch-GP#56]
![FINAL FANTASY XIV 2022_1_9 上午 01_49_56](https://user-images.githubusercontent.com/95951780/148654562-ff773eb9-d094-44f5-bbfd-be92066a4633.png)
星天交差是日文，天星交錯才是中文翻譯。

**Comment by GpointChen** [comment]
感謝回報，預計下次更新修正。

**Comment by GpointChen** [comment]
已修正於v2.51。
