### ISSUE TITLE
关于简体中文文本

### ISSUE THREAD

**Issue by xgugugua** [GpointChen/FFXIVChnTextPatch-GP#58]
首先非常感谢您的repo，这是我看到的最好用的汉化tool。我是国际版玩家但希望使用简体中文，下列是我发现在rawexd-zhcn-0107.rar中一些未完全的简体转化，不知道可不可以在您以后的release中得到反映 (目前本地我是用atom对所有cvs做批量修改的)

翻译基于：https://github.com/thewakingsands/ffxiv-datamining-cn
https://ff14.huijiwiki.com/wiki/%E9%A6%96%E9%A1%B5

乙太->以太
苍天街->天穹街
技术力->鉴别力
"はい"->"是"     （ 这个有点特殊，我发现有的地方的”是“日文的，我这边建议只replace cvs中被双引号框住的 ）
"いいえ"->"否"    （ 这个有点特殊，我发现有的地方的”否“日文的，我这边建议只replace cvs中被双引号框住的 ）
巨集->宏
介面->界面
菁英->精英
麽->么
於->于

**Comment by GpointChen** [comment]
我是直接用工具繁轉簡，如果有時間下一版會手動添加部分詞語轉換。簡繁轉換後字數不同可能會導致部分遊戲內指令碼失效，所以可能不會全數轉換，視情況而定。

> 技术力->鉴别力

另外順便一提，鑒別力改名技術力是6.0採集職業的改動，所以這個和簡繁轉換無關。

感謝回饋。

**Comment by GpointChen** [comment]
已於v2.51新增。
