### ISSUE TITLE
請問是否能只安裝中文字型不漢化?

### ISSUE THREAD

**Issue by class2u** [GpointChen/FFXIVChnTextPatch-GP#59]
您好！
請問是否有辦法只安裝中文字型，可以看到別人在聊天視窗輸入的中文字，但是不會漢化遊戲內容呢？
我是使用英文版的，謝謝您！

**Comment by GpointChen** [comment]
理論上將resource/rawexd內的csv全數刪除後再進行漢化即可。

**Comment by class2u** [comment]
成功了!! 非常謝謝你~~
