### ISSUE TITLE
[討論]藏寶圖名稱的翻譯

### ISSUE THREAD

**Issue by iveslazycat** [GpointChen/FFXIVChnTextPatch-GP#6]
目前的藏寶圖都是使用『陳舊的XX革地圖』，
但是我覺得除了跟一般玩家溝通上不好溝通以外，
同時也很難根據名稱來瞭解等級的區別。

日文原文是『隠された地図G1~12』，
目前的翻譯則是使用英文的意譯，
是不是改用日文的意譯會比較好？

**Comment by iveslazycat** [comment]
或者乾脆直接在後面標示 G幾 ?

**Comment by GpointChen** [comment]
考慮到一般玩家會在灰機wiki之類的地方查資料，譯名沒有簡繁用語差異的話，通常不予改動。

不過確實可以考慮在物品說明之類的地方加上GX。之後有空就會改。

**Comment by iveslazycat** [comment]
我理解在對於查詢資料上，一致的譯名可以找到精準的結果。
但是僅對於藏寶圖而言，加上編號應該可以更容易使玩家找到答案。

對於譯名的改動以『陈旧的鞣革地图 G1』這種方式為目標的話
(先不考慮繁簡問題，因為灰機只能搜尋簡體)，
在地圖名稱跟編號間加上一個空格，會有以下的優點。

- 即便是在灰機，因為編號與名稱有個空格，雖然沒辦法精準進入條目，
但是卻還是有搜尋結果，而其中一個搜尋結果也有編號
(因為尋寶條目裡也有記載藏寶圖的編號)，
應該不至於使查詢者無法分辨。
https://imgur.com/a/togKaWs (灰機搜尋結果的截圖)
若是以一般搜尋引擎的話，我想多了一個搜尋條件，
找到的結果應該反而會更精簡。

- 基於需要漢化的玩家都是在國際服，在使用『展示道具名稱』功能上，
不同於定型文，他只能以發送者的客戶端語言進行發送。
雖然對方如果滑鼠移到該名稱上，可以顯示本地語言的說明，
但不管是對於英語或日語玩家而言，應該都無法一眼理解這個道具，
在有編號的情況下，至少日語玩家可以懂，英語玩家應該多了一個理解的可能。

有鑑於大家都有很大的機會跟不同語系的玩家互動，
我想雖然少了一點點的搜尋精度以及破壞原本的翻譯模式，
但是應該多了更多方便。
而且也可以讓新進玩家也可以更快速理解別人在講的藏寶圖編號。

以上是我的想法，
至於在說明文本里增加編號的說明，
也是很不錯的，我認為也是個很好的方法，
畢竟這樣也不會破壞整個文本的感覺。

**Comment by GpointChen** [comment]
參照其他物品名稱的命名方式，目前先試行「陳舊的纏尾蛟革地圖（G12）」這樣的格式。

**Comment by iveslazycat** [comment]
感謝願意採納建議，不過因為與編號間沒有空格，
所以對於灰機的搜尋，如果直接搜尋可能會搜尋不到。

不過就先試行看看吧。
