### ISSUE TITLE
個人訊息 文字覆蓋

### ISSUE THREAD

**Issue by HSIA0116** [GpointChen/FFXIVChnTextPatch-GP#62]
![image](https://user-images.githubusercontent.com/37303531/149651139-b4d172a3-3d02-41f0-8dc7-36c76df042a3.png)
個人訊息 文字覆蓋

**Comment by GpointChen** [comment]
很遺憾，4k字體是別人提供的，所以正如 #42 中所提到的一樣，我無法對此進行改善。

感謝你的回報。
