### ISSUE TITLE
捕魚人53等的職業任務問題

### ISSUE THREAD

**Issue by rozen1987** [GpointChen/FFXIVChnTextPatch-GP#63]
我接了捕魚人53等職業任務"不打不相識"到隼巢跟NPC對話完之後任務日誌無法顯示文本，同時任務情報介面會卡住。

**Comment by GpointChen** [comment]
感謝回報，已於[rawexd-0116.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.51/rawexd-0116.rar)修正，請下載後覆蓋原本的rawexd資料夾。

**Comment by rozen1987** [comment]
辛苦您了

**Comment by GpointChen** [comment]
> > 感謝回報，已於[rawexd-0116.rar](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/download/v2.51/rawexd-0116.rar)修正，請下載後覆蓋原本的rawexd資料夾。
> 
> 需要重新執行patch還是覆蓋就可?

請覆蓋後重新執行patch（還原和漢化）。

**Comment by jinnit90876** [comment]
請問6.08的漢化文字有簡體的嗎
