### ISSUE TITLE
關於4.x 副本閃退

### ISSUE THREAD

**Issue by bigball0630** [GpointChen/FFXIVChnTextPatch-GP#66]
你好，當我到4.x 版本任務 廢王的黃金 打副本 沉沒神殿卡拉遺跡 時，進副本的那一刻閃退，重新開遊戲也是一樣. PLease help T.T

**Comment by bigball0630** [comment]
我是用最新chntextpatch 0113。每次從副本閃退後 可以開得到遊戲 進入選擇角色大廳 但排隊進入 出現loading in 畫面時 都自動閃退

**Comment by GpointChen** [comment]
請問你是一進副本就閃退嗎？我是正常的

![image](https://user-images.githubusercontent.com/34565875/150285001-ccd2b118-6ba7-4e0a-ba7c-a1f8925b3177.png)

**Comment by bigball0630** [comment]
大神 我修復檔案後 問題解決了 可能是我一路以來chn都沒有回復 就用新版本的chn覆蓋 導致檔案破損
