### ISSUE TITLE
關於 釤鐮客 與 賢者 的職業任務

### ISSUE THREAD

**Issue by SkylineCrazy** [GpointChen/FFXIVChnTextPatch-GP#68]
你好，關於這兩個職業的職業任務好像幾個版本下來都未翻譯，不知道是甚麼原因沒翻譯想詢問一下，謝謝!
然後也非常謝謝您的漢化讓我們遊戲體驗更佳!

**Comment by lai909909911** [comment]
因為這是6.0的新職業啊
 職業劇情要漢化應該還是要等3月中文的發售才有吧

**Comment by qwe3410475** [comment]
因為是新版本的內容
漢化目前他是漢化技能.道具等等的翻譯而已
劇情可能要等一段時間了

**Comment by GpointChen** [comment]
如上面兩位所回答，單純是我沒有那麼多時間可以處理這麼大量的遊戲文本，所以任務與劇情的優先順序放在非常後面，或者可以說很有可能不會翻譯。

如果想要體驗劇情，推薦使用Tataru Helper之類的自動機翻，巴哈有人有做改良版，我個人用起來覺得算不錯。

**Comment by SkylineCrazy** [comment]
好的，非常感謝回覆!
