### ISSUE TITLE
漢化失敗

### ISSUE THREAD

**Issue by Knox30663** [GpointChen/FFXIVChnTextPatch-GP#69]
[debug.log](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/7933542/debug.log)
請問有人有遇過這樣的問題嗎
在漢化日文會出現失敗
在EXD/item.EXH時失敗
英文的不會 可以漢化成功
但Bug log不是很理解哪裡產生問題...

**Comment by Ninisun** [comment]
遇到同樣的問題呢    日文不行  停在同樣的地方  英文還沒試  等等試試看

**Comment by GpointChen** [comment]
看起來是你檔案有損毀，剛好壞在日文那一塊；我看log裡面少了最後一次replace。

有可能是遊戲改版時沒有還原就更新或再次漢化造成，當然也有可能本來就是壞的。

好像只能建議你使用修復功能或跟朋友拿原本的遊戲檔案（0a0000.win32.*）。

**Comment by Knox30663** [comment]
成功了  大感謝QQ

**Comment by Ninisun** [comment]
真的是這樣 昨天一開就自動更新了 沒有做復原   剛剛重新修復後 日文漢化成功了
