### ISSUE TITLE
（不知道起什么标题）

### ISSUE THREAD

**Issue by wingchaos** [GpointChen/FFXIVChnTextPatch-GP#72]
大大，所以说开头的strat game ，config之类的汉化不了，应该是字库字体font里面没有对应的贴图么？还有lobby里面很多==之类的也是这个原因吧，可以下一步考虑下补全它们呢？最后春节快乐。

**Comment by GpointChen** [comment]
沒錯，不過這個部份我不會，就要看有沒有其他厲害的人可以處理了。
