### ISSUE TITLE
使用已漢化過的檔案進行漢化失敗問題

### ISSUE THREAD

**Issue by kalispp** [GpointChen/FFXIVChnTextPatch-GP#73]
[debug.log](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/7988053/debug.log)

由於預設沒有text目錄，自行新增text目錄後，將已繁體漢化過的000000.win32.*、0a0000.win32.*，六個檔案放置text目錄內
\FFXIVChnTextPatch-0125-4k\resource\text
執行後會出現程式錯誤

正常遊戲目錄內是原始日文、已漢化六個檔是覆蓋日文版本

設置嘗試過不同組合都一樣

檔案語言：日文
原始語言：日文
目標語言：正體中文、簡體中文

檔案語言：簡體中文
原始語言：日文
目標語言：正體中文、簡體中文

請問流程是否有漏或是順序錯誤?

謝謝您的協助

**Comment by GpointChen** [comment]
感謝回報，已修正於v2.53。

**Comment by pia508** [comment]
我用0125和0209版本均汉化不成功，用0113版就没有问题，请帮助

**Comment by kalispp** [comment]
我用0209可以正常，謝謝

**Comment by HeroyaOvan** [comment]
原本是裝0125，解除後改裝0209，漢化沒有正常打上去，看漢化的進度條是顯示有更換字體，但是沒有後面更換文庫的進度顯示。

**Comment by lee871108** [comment]
想請問一下 也是把之前的漢化還原裝上新的嗎?因為 2/9的漢化跑了之後並沒有漢化到.

**Comment by GpointChen** [comment]
> 想請問一下 也是把之前的漢化還原裝上新的嗎?因為 2/9的漢化跑了之後並沒有漢化到.

是的，如果有出現漢化失敗問題，可以貼上log方便讓我確認問題在哪。

**Comment by lee871108** [comment]
用了211的版本可以了

**Comment by HeroyaOvan** [comment]
我看debug.log檔案大小是0KB，好像是空的，
不過改用0211版本的就正常了，感謝大大!
