### ISSUE TITLE
5.X 副本魔法宮殿宇宙宮 進入後, 一開啟副本, 介面就崩潰了

### ISSUE THREAD

**Issue by bigball0630** [GpointChen/FFXIVChnTextPatch-GP#74]
使用的是 6.08 1/25 號的漢化，
5.X 副本 魔法宮殿宇宙宮 進入後, 一開啟副本, 介面就崩潰了。
![ff14](https://user-images.githubusercontent.com/97968560/152644527-cd8fc081-53b3-4b6c-ab9a-6a14eb42ffbf.png)

**Comment by GpointChen** [comment]
我之前用各種版本均未遇到這個問題，後來忘記回覆了。請問現在還有這個問題嗎？

**Comment by GpointChen** [comment]
Closed due to inactivity. 如果仍有相同問題發生可另開新串。
