### ISSUE TITLE
RERPER巨集問題

### ISSUE THREAD

**Issue by PongChan123** [GpointChen/FFXIVChnTextPatch-GP#75]
Reaper88lv技能豐收 在巨集內會變左生活技能的豐收

**Comment by PongChan123** [comment]
# @

> Reaper88lv技能豐收 在巨集內會變左生活技能的豐收

**Comment by GpointChen** [comment]
感謝回報，預計會在下版將釤鐮客技能改為其他名稱。

**Comment by GpointChen** [comment]
已修正於[0211](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.53)。
