### ISSUE TITLE
请问一下职业名字的文本是在哪个文件？

### ISSUE THREAD

**Issue by huaxianyan** [GpointChen/FFXIVChnTextPatch-GP#76]
因为在 PC 和 PS5 平台同时游玩，职业套装保存都是用的日文原版的，但是打了汉化后因为套装名和职业名不同导致后面的平均品级不会自动更新，就想把这部分去掉保留原文

**Comment by GpointChen** [comment]
應該是 rawexd\ClassJob.csv
