### ISSUE TITLE
新版本好像不能汉化了，0125和现在的0209我的都不行，以前版本没问题

### ISSUE THREAD

**Issue by pia508** [GpointChen/FFXIVChnTextPatch-GP#77]

**Comment by GpointChen** [comment]
有log嗎？

**Comment by noxerow** [comment]
我也有一樣的問題，我已經重新下載了也不行，也試過0125和0209的都不行，用0113的可以

**Comment by noxerow** [comment]
[debug.log](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/8048691/debug.log)
這是0209的debug log

**Comment by GpointChen** [comment]
> [debug.log](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/8048691/debug.log) 這是0209的debug log

我確認一下，你是使用別的已漢化檔來漢化？

**Comment by GpointChen** [comment]
已修正於 [0211](https://github.com/GpointChen/FFXIVChnTextPatch-GP/releases/tag/v2.53)。
