### ISSUE TITLE
漢化錯誤

### ISSUE THREAD

**Issue by aiolia1984** [GpointChen/FFXIVChnTextPatch-GP#78]
![1644725831471](https://user-images.githubusercontent.com/99574087/153738594-6e88f190-f81f-42f7-9990-1abf047ca024.jpg)

大家好，我有先按還原再漢化，但出現上面的畫面，導致漢化無法完成，請問要怎麼解決阿?謝謝。

**Comment by kalispp** [comment]
建議提供下目錄內的debug.log，比較可以看一下狀況

還有就是用哪種方式漢化的?(csv?別人漢化過的重新漢化?也可以截圖一下漢化前的設定畫面)

**Comment by GpointChen** [comment]
無後續回覆，關閉本串。
