### ISSUE TITLE
純日文4K font

### ISSUE THREAD

**Issue by Leon0pt3ryX** [GpointChen/FFXIVChnTextPatch-GP#80]
想請問是否有辦法做到不漢化，但能把原來的CSV日文原文都改成4K font呢？
謝謝

**Comment by qwe3410475** [comment]
000000.win32 的兩個檔案 換掉
不要替換0a0000就好
前提是字體有支援到日文 你可以試試

**Comment by GpointChen** [comment]
如上所回覆，感謝。
