### ISSUE TITLE
5.57主線沒有漢化

### ISSUE THREAD

**Issue by Dustpaper** [GpointChen/FFXIVChnTextPatch-GP#82]
[debug.log](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/8093285/debug.log)

打開遊戲後主線沒有漢化

![BUG](https://user-images.githubusercontent.com/99931288/154598126-926bd030-2177-43df-8624-f042aca5d81a.png)

**Comment by lolbob** [comment]
やがて流れは海へと注ぐ　为6.0第一个晓月主线任务，一个月后陆服更新6.0后就会有翻译。

**Comment by GpointChen** [comment]
如上所回覆，感謝。
