### ISSUE TITLE
简中错别字

### ISSUE THREAD

**Issue by KaliMae** [GpointChen/FFXIVChnTextPatch-GP#83]
PatchTool 6.08 2/9版本的简中rawexd里面汉化“鱼”字一律显示为“吁”
![dgaddd](https://user-images.githubusercontent.com/100011255/154786974-0a7d96e2-9b29-4b37-9443-2b80cb64e2aa.png)

**Comment by GpointChen** [comment]
應已於v2.54中修正。如有問題歡迎繼續回報。
