### ISSUE TITLE
程式錯誤

### ISSUE THREAD

**Issue by ROTT-YC** [GpointChen/FFXIVChnTextPatch-GP#84]
您好，也遇到了漢化錯誤，以下是漢化前的相關操作，請您幫我看一下問題在哪邊：

![image](https://user-images.githubusercontent.com/66822676/154839960-6230bc20-1ea9-41de-b805-83be3632eb50.png)
![image](https://user-images.githubusercontent.com/66822676/154839970-e7bfc423-ae2f-478d-a4af-3a3c72d80ac8.png)

大多都停在這個 item.EXH的檔案
![image](https://user-images.githubusercontent.com/66822676/154839944-d8f53e6d-0890-4097-8dad-e58f7266ff57.png)
![image](https://user-images.githubusercontent.com/66822676/154840070-c445648a-1e09-49fe-98a3-f8b3f3329bbe.png)
![image](https://user-images.githubusercontent.com/66822676/154840078-be9f762a-6632-454d-a695-976cc2e97879.png)

之後將debug.log打開時也沒有印出錯誤訊息無從測試起，再麻煩您了!

**Comment by sai750310** [comment]
我也是同樣卡在EXD/Item.EXH
[debug.log](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/8178022/debug.log)
求解惑，非常感謝

**Comment by GpointChen** [comment]
看起來是原檔案（0a0000）毀損，導致裡面Item的數量對不上，問題與 #69 類似。
