### ISSUE TITLE
選擇路徑時，一直跳出路徑錯誤

### ISSUE THREAD

**Issue by Mikailei** [GpointChen/FFXIVChnTextPatch-GP#89]
新入的玩家，剛下載完主程式而已，想安裝漢化
不知道是哪邊出問題，把資料夾改下面那一串名稱也沒用

![未命名](https://user-images.githubusercontent.com/100490935/155857589-cdcabe6a-ada8-45c5-92f2-8c79f355bec8.png)

**Comment by ueuuop8591** [comment]
我也遇到相同的問題 有解決了嗎
