### ISSUE TITLE
遇到jni error

### ISSUE THREAD

**Issue by yoyo1226** [GpointChen/FFXIVChnTextPatch-GP#90]
不好意思請問一下，開啟exe檔的時候遇到A Jni error has occurred,please check your installation and try again.    
                                                                    A java Exception has occurred
看到您之前的回覆，我有下載過Java SE Development Kit 16.0.1，exe檔跟jre資料夾是在同一個資料夾裡面的，還是會遇到Jni error的問題
想請問有什麼解決辦法嗎？
感謝回復

**Comment by GpointChen** [comment]
理論上exe會抓JRE資料夾，應該不用額外下載Java SE。

你是用哪個release版本？

**Comment by aikenoushin** [comment]
借串問一下 我有相同的問題 JAVAC和JAVE顯示的版本也一樣 我回去用舊版也無法開啟

**Comment by aikenoushin** [comment]
版本是16.0.2

**Comment by GpointChen** [comment]
> 借串問一下 我有相同的問題 JAVAC和JAVE顯示的版本也一樣 我回去用舊版也無法開啟

我自己之前遇到類似的問題是電腦舊版的Java 8沒有移除導致電腦抓錯版本，在移除後就正常了。

(Before)
![image](https://user-images.githubusercontent.com/34565875/159382965-d90366bb-e708-4818-9b87-e56f6f354319.png)
(After)
![image](https://user-images.githubusercontent.com/34565875/159382870-38afb68b-ebd8-4767-9331-aca08e5d93f7.png)

你也可以確認一下電腦裡面的環境變數是否有指向正確的Java版本。

![image](https://user-images.githubusercontent.com/34565875/159383130-723bd184-cbed-4ebb-b2b3-01334f3e7553.png)

**Comment by aikenoushin** [comment]
![image](https://user-images.githubusercontent.com/56306647/159526235-971caa16-5c62-4d18-b7eb-105d8863ea80.png)
![image](https://user-images.githubusercontent.com/56306647/159526580-6788427b-983f-4f19-860e-a0631d77605b.png)
![image](https://user-images.githubusercontent.com/56306647/159526611-13a9dc66-8f00-466e-b3f9-8d9b76e1a47c.png)
不好意思 還是不行....

**Comment by GpointChen** [comment]
[FFXIVChnTextPatch.zip](https://github.com/GpointChen/FFXIVChnTextPatch-GP/files/8329527/FFXIVChnTextPatch.zip)

你有空的話可以幫我測試看看。把這個檔案解壓縮後，jar檔放到與exe同一個位置，然後command line切到該資料夾（`cd /d D:\xxxxxxxx`）後輸入：

```
java -jar FFXIVChnTextPatch.jar
```
看看會跳什麼訊息。

**Comment by aikenoushin** [comment]
![image](https://user-images.githubusercontent.com/56306647/159640354-f5df45fd-907b-4eeb-ba41-f5a5c919bc58.png)
輸入後成功開起來了 0.0 那我是直接就這樣用嗎?

**Comment by GpointChen** [comment]
好喔，那你就用吧XD

**Comment by aikenoushin** [comment]
感謝!

**Comment by cmcmcmcm2** [comment]
我這邊最簡單的解法是
除了版本不同  注意執行的路徑不要有英文以外的語言
例如:可以直接解壓縮到D槽下
